const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const server=http.createServer((req,res)=>{const f=path.join(__dirname,decodeURIComponent(req.url.split('?')[0]));fs.readFile(f,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:320,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const W=Worker;window.Worker=class extends W{constructor(...args){super(...args);this.groups=[];this.addEventListener('message',({data})=>{window.lastPhase=data.type;if(data.type==='group')this.groups[data.groupIndex]=data.group;if(data.type==='complete')window.testReport={...data.report,groups:this.groups};});}};});
 await page.goto('http://127.0.0.1:'+server.address().port+'/engine-lab.html');
 const scenario=process.env.SL_STRESS_SCENARIO||'steal';await page.locator('#quickPreset').selectOption(scenario);await page.evaluate(id=>{const s=SL_LAB.config(id);Object.assign(s,{inning:id==='steal'?6:8,half:'top',outs:0,runnerGrade:id==='steal'?'S':'C'});document.querySelector('#custom').value=JSON.stringify(s);document.querySelector('#applyCustom').click();},scenario);await page.locator('#axis').selectOption(scenario==='steal'?'runnerTrait':'buntTrait');await page.locator('#comparisonMode').selectOption('matrix');await page.locator('#axisB').selectOption(scenario==='steal'?'catcherArm':'runnerSpeed');
 const n=Number(process.env.SL_STRESS_N||100);await page.locator('#count').selectOption('custom');await page.locator('#customCount').fill(String(n));await page.locator('#run').click();
 await page.waitForFunction(()=>window.testReport&&!document.querySelector('#run').disabled,null,{timeout:900000});
 const report=await page.evaluate(()=>({scenario:testReport.groups[0].bundle.scenario,metrics:SL_LAB_PRESENTATION.metrics(testReport).primary,groups:testReport.groups.map(g=>({label:g.label,summary:g.summary,count:g.trials.length})),elapsedMs:testReport.elapsedMs,storage:testReport.storage,phase:lastPhase,status:document.querySelector('#status').textContent}));
 assert.equal(report.groups.length,9);assert(report.groups.every(g=>g.count===n&&g.summary.trials===n));assert(!report.status.includes('失敗'));assert(await page.locator('#results').isVisible());
 await page.locator('#saveName').fill('0911-stress-'+n);await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('保存しました'),null,{timeout:120000});
 await page.locator('#solJson').click();assert.deepEqual(errors,[]);fs.writeFileSync('test-artifacts/daily-0911-'+scenario+'-'+(n*9)+'.json',JSON.stringify({trials:n*9,...report,errors},null,2));
 await page.evaluate(players=>localStorage.setItem('sl_world_players_v01',JSON.stringify(players)),JSON.parse(fs.readFileSync('SL_WORLD_PLAYERS_2026-09-10.json','utf8')).players);
 await page.goto('http://127.0.0.1:'+server.address().port+'/engine006.html');await page.locator('#reset').click();assert.equal(await page.locator('.live-lineups tbody tr').count(),18);assert.equal(await page.locator('.live-lineups .live-batter').count(),1);assert(await page.evaluate(()=>document.querySelector('.live-lineups').scrollWidth<=innerWidth));assert(await page.locator('.live-lineups tbody tr').evaluateAll(rows=>rows.every(r=>Array.from(r.cells).slice(3).every(c=>/^[SABCDEFG]$/.test(c.textContent)))));const first=await page.locator('.live-batter').getAttribute('data-player-key');await page.locator('#atbat').evaluate(e=>e.closest('details').open=true);await page.locator('#atbat').click();assert.notEqual(await page.locator('.live-batter').getAttribute('data-player-key'),first);await page.locator('.live-lineups').screenshot({path:'test-artifacts/daily-0911-lineups.png'});
 assert.deepEqual(errors,[]);console.log('PASS actual browser Worker, render, IndexedDB save, SOL export:',n*9,'trials; 320px live lineups');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
