const fs=require('fs'),vm=require('vm'),cp=require('child_process'),assert=require('node:assert/strict');
const files=['engine006-fielding.js','engine006-tactics.js','engine006.js','engine-lab-core.js','engine-lab-presentation.js'];
function context(old){const c=vm.createContext({console,TextEncoder});for(const f of files)vm.runInContext(old?cp.execFileSync('git',['show','be73bb264fd062117fb91414c60b57d5d669265f:'+f],{encoding:'utf8'}):fs.readFileSync(f,'utf8'),c);return c;}
const c=context(false),old=context(true),L=c.SL_LAB,E=c.SL_ENGINE,P=c.SL_LAB_PRESENTATION,plain=x=>JSON.parse(JSON.stringify(x));
function simulation(t){const x=plain(t);for(const k of Object.keys(x.reason))if(k.startsWith('SECURE_RETURN:'))delete x.reason[k];for(const k of Object.keys(x.decision))if(k==='DEFENSE:SECURE_RETURN')delete x.decision[k];return x;}
let trials=0;
for(const id of Object.keys(L.scenarios))for(let seed=0;seed<100;seed++){const a=L.trial(L.setup(L.config(id)),seed),b=old.SL_LAB.trial(old.SL_LAB.setup(old.SL_LAB.config(id)),seed);assert.deepEqual(simulation(a),simulation(b),id+' '+seed);trials++;}
for(const i of [6,7,8])for(const result of ['single','double','triple','flyout','error']){const g=L.create(L.setup(L.config('steal')),7),e={outcome:'inPlay',result,battedResult:result,fielderIndex:i,landingPoint:[400,65],ballType:'fly',outsAfter:1,runnersAfter:[{},null,null],actions:[]};const state=JSON.stringify(g.state);c.SL_FIELDING.annotate(g,e);assert.equal(e.defenseDecision.decision,'SECURE_RETURN');assert.equal(e.transfers[0].kind,'return');assert.equal(JSON.stringify(g.state),state);}
const g=L.create(L.setup(L.config('steal')),7);assert.equal(c.SL_TACTICS.defenseDecision(g,{fielderIndex:2,landingPoint:[553,302]},E.currentBatter(g),{settled:true}).decision,'HOLD_BALL');
const cases=[{initialDecision:'HIT_AND_RUN',decision:{HIT_AND_RUN:1}},{initialDecision:'SWING_AWAY',decision:{HIT_AND_RUN:2}},{initialDecision:'HIT_AND_RUN',decision:{HIT_AND_RUN:3}},{initialDecision:'SWING_AWAY',decision:{}}];const report={groups:[{trials:cases,summary:{initialDecision:{HIT_AND_RUN:2}}}]};assert.equal(P.metric(report,'initial:HIT_AND_RUN').values[0].numerator,2);assert.deepEqual(plain(P.metric(report,'observed:HIT_AND_RUN').values[0]),{conditionId:'A',numerator:3,denominator:4,rate:.75,occurrences:6});assert.deepEqual(plain(P.metric(report,'later:HIT_AND_RUN').values[0]),{conditionId:'A',numerator:2,denominator:4,rate:.5,occurrences:4});
for(const control of ['S','C','G'])for(const fatigue of [80,140]){const s=L.config('relief');Object.assign(s,{pitcherGrade:control,fatigue});const t=L.trial(L.setup(s),7);assert.equal(t.operations[0].decision,fatigue===80?'CONTINUE':'RELIEF');}
for(const [outs,score,expected] of [[1,[1,0],'IN'],[1,[2,0],'NORMAL'],[2,[1,0],'DEEP']]){const s=L.config('alignment');Object.assign(s,{outs,score});assert.equal(c.SL_TACTICS.alignment(L.create(L.setup(s),7)).decision,expected);}
console.log('PASS daily corrections: '+trials+' old/new seed trials preserve initial decisions, offensive counts, traces, operations, executions, outcomes and anomalies; 15 deep returns; H&R aggregation; relief/alignment baselines');
