const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const plain=x=>JSON.parse(JSON.stringify(x));
function context(lab){const c=vm.createContext({console});for(const f of lab?['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js']:['engine-fielding.js','engine-tactics.js','match-replay.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);if(!lab)vm.runInContext(fs.readFileSync('engine-test.html','utf8').match(/<script>\s*([\s\S]*?)<\/script>/)[1],c);return c;}
for(const lab of [false,true]){const c=context(lab),E=c.SL_ENGINE,F=c.SL_FIELDING;const teams=[E.makeTeam('A','away',[],E.CONFIG),E.makeTeam('B','home',[],E.CONFIG)];let seen={};
 for(let seed=0;seed<300;seed++){const g=E.newGame(teams,seed),b=E.currentBatter(g),p=E.currentPitcher(g);g.state.bases[0]=g.teams[0].lineup[2];g.state.playActions=[];if(seed%4===1){g.state.outs=2;g.tacticalRng=()=>.99999;}const ball={battedResult:'groundout',fielderIndex:5,landingPoint:[325,250],battedQuality:.5,...(seed%4===0?{trajectory:{fieldTime:4}}:{})};const result=F.field(g,ball,b,p),d=ball.defenseDecision;
 if(result==='single'){assert(!ball.error&&!ball.fieldersChoice);assert(d.decision==='HOLD_BALL'||d.toBase===1);assert.equal(g.state.batting[b.key].H,1);assert.equal(g.state.pitching[p.key].H,1);}
 if(result==='fieldersChoice'){assert(d.toBase>1);assert.equal(g.state.batting[b.key].H,0);}
 if(result==='error'){assert(ball.error);assert.equal(g.state.errors[1],1);assert.equal(g.state.batting[b.key].H,0);}seen[result]=(seen[result]||0)+1;
 }
 for(const key of ['single','fieldersChoice','error'])assert(seen[key],key);console.log(lab?'LAB':'LIVE',seen);
 for(const fielderIndex of [6,7,8])for(const result of ['single','double','triple','error','flyout']){const g=E.newGame(teams,1),e={outcome:'inPlay',result,battedResult:result,fielderIndex,landingPoint:[400,90],outsAfter:1,runnersAfter:[{},null,null],actions:[],batter:{key:'b',name:'B'}};const before=JSON.stringify(g.state);F.annotate(g,e);assert.equal(e.defenseDecision.decision,'SECURE_RETURN');assert.equal(e.transfers[0].kind,'return');assert.equal(JSON.stringify(g.state),before);const r=c.SL_MATCH_REPLAY.toReplayEvent(e),p=c.SL_MATCH_REPLAY.animationPlan(r);assert(p.resultAt>p.transfers[0].end);assert(p.end>p.resultAt);assert.equal(c.SL_MATCH_REPLAY.ballAnimation(r,p,(p.transfers[0].start+p.transfers[0].end)/2).phase,'throw');}
}
const c=context(true),L=c.SL_LAB;
let s=L.config('squeeze');s.players.batter=L.preset('BATTER','C','バント○');const before=JSON.stringify(s);for(const g of L.compare(s,'batterMeet','runnerSpeed')){assert.equal(g.bundle.scenario.buntTrait,'バント○');assert.equal(L.effectiveInputs(g.bundle).buntTrait.join(','),'バント○');assert.equal(g.bundle.scenario.batterGrade,g.changed.value);assert(g.bundle.teams[1].lineup[0].name.includes('meet='+L.effectiveInputs(g.bundle).batterMeet));}assert.equal(JSON.stringify(s),before);
s.players.batter.specials=[];for(const g of L.compare(s,'batterMeet')){assert.equal(g.bundle.scenario.buntTrait,'none');assert.equal(L.effectiveInputs(g.bundle).buntTrait.length,0);}
s=L.config('relief');s.comparisonPitchCounts='90 / 100 / 110';assert.equal(L.compare(s,'fatigue').map(g=>g.bundle.scenario.fatigue).join(','),'90,100,110');assert.equal(L.executionSize('fatigue','pitcherControl',100,s).totalTrials,900);for(const g of L.compare(s,'fatigue','pitcherControl'))assert.equal(L.effectiveInputs(g.bundle).fatigue,g.changed.value);
for(const v of ['90 / bad','90 / 90','-1 / 100','90.5 / 100','90']){s.comparisonPitchCounts=v;assert.throws(()=>L.compare(s,'fatigue'));}
console.log('PASS daily 0910: FC/error/hit stats, both return timelines, fixed traits, matrix metadata, custom pitch counts');

// Preserve other runners and round-trip the canonical comparison through exported JSON.
const multi=L.config('bunt');multi.bases=[true,true,false];for(const g of L.compare(multi,'runnerSpeed')){assert.equal(g.bundle.scenario.players.runner2.batting.speed,14);assert.equal(g.bundle.scenario.players.runner1.batting.speed,L.gradeValue('speed',g.changed.value));}
vm.runInContext(fs.readFileSync('engine-lab-presentation.js','utf8'),c);const groups=L.compare(L.config('pinchHit'),'benchMeet');for(const g of groups){assert.equal(g.bundle.scenario.benchGrade,g.changed.value);g.trials=[L.trial(g.bundle,'json:0')];g.summary=L.summarize(g.trials);}const report={format:'SL_WORLD_ENGINE_LAB',schemaVersion:1,version:c.SL_ENGINE.CONFIG.version,date:'2026-09-10',axis:'benchMeet',trialCount:1,seedPrefix:'json',groups,anomalies:[],savedSeeds:[]};const exported=c.SL_LAB_PRESENTATION.exportReport(report);assert.deepEqual(plain(c.SL_LAB_PRESENTATION.importReport(plain(exported)).groups),plain(groups));assert(c.SL_LAB_PRESENTATION.solReport(report).primaryMetrics.length);console.log('PASS other occupied runners fixed; bench metadata; export/import and SOL metrics');
