const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({console});for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js','engine-lab-presentation.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);
const E=c.SL_ENGINE,F=c.SL_FIELDING,T=c.SL_TACTICS,L=c.SL_LAB,R=c.SL_MATCH_REPLAY;
const bundle=L.setup(L.config('bunt')),g=L.create(bundle,1),b=E.currentBatter(g),pitcher=E.currentPitcher(g);
for(let mask=0;mask<8;mask++){const bases=[0,1,2].map(i=>mask&(1<<i)?g.teams[0].lineup[i+1]:null),plan=F.forcePlan(bases,b);for(const a of plan)assert.equal(a.force,a.fromBase===0||(mask&((1<<a.fromBase)-1))===((1<<a.fromBase)-1));}
assert.equal(F.receiverIndex(1,2,[470,260]),0);assert.equal(F.receiverIndex(1,2,[545,315]),2);
for(const [index,at,relay] of [[6,[200,140],5],[7,[400,100],5],[8,[600,140],3]]){
 const e={outcome:'inPlay',result:'single',fielderIndex:index,ballType:'line',landingPoint:at,outsAfter:1,runnersAfter:[{},null,null],actions:[]};F.annotate(g,e);assert.equal(e.returnFormation.relayIndex,relay);assert.equal(e.transfers[0].toIndex,relay);assert.notDeepEqual(Array.from(e.transfers[0].toPoint),Array.from(F.layout.bases[2]));assert.equal(e.transfers[1].toIndex,relay===5?3:5);
}
const modes=new Set();for(const arm of [1,20]){const x=L.create(bundle,1),fielders=F.defense(x);fielders[8].profile.batting.arm=arm;fielders[3].profile.batting.arm=20;const e={outcome:'inPlay',result:'sacrificeFly',fielderIndex:8,ballType:'fly',landingPoint:[630,110],outsAfter:1,runnersAfter:[null,null,null],tagUp:true,actions:[{type:'tagUp',runner:{key:'r'},fromBase:3,toBase:4,result:'safe'}]};F.annotate(x,e);modes.add(e.returnDecision.mode);}assert.equal(modes.size,2,'direct and relay are separate evaluated paths');
const targets=new Set();for(let seed=0;seed<150;seed++){
 const x=L.create(bundle,seed);x.state.half='top';x.state.bases=x.teams[0].lineup.slice(2,5);const batter=E.currentBatter(x),p=E.currentPitcher(x),before=x.state.bases.map(r=>r.key),ball={battedResult:'groundout',fielderIndex:5,landingPoint:[325,250],battedQuality:.5};
 F.field(x,ball,batter,p);assert(ball.forceTrace.atContact.every(a=>a.force));targets.add(ball.defenseDecision.toBase);assert.equal(new Set(x.state.bases.filter(Boolean).map(r=>r.key)).size,x.state.bases.filter(Boolean).length);
 if(ball.defenseDecision.toBase===1&&!ball.error&&x.state.outs<3){assert.equal(x.state.bases[1]?.key,before[0]);assert.equal(x.state.bases[2]?.key,before[1]);assert(x.state.playActions.some(a=>a.runner.key===before[2]&&a.toBase===4));}
}assert(targets.has(1)&&targets.size>1);
const groundDirections=new Set();for(let seed=0;seed<500;seed++){const x=E.newGame([E.makeTeam('A','away',[],E.CONFIG),E.makeTeam('B','home',[],E.CONFIG)],seed),p={battedResult:'groundout',battedQuality:.8};F.geometry(x,p);if(p.battedResult==='single'){assert.equal(p.ballType,'ground');assert(p.fielderIndex>=6);groundDirections.add(p.fielderIndex);}}assert.equal(groundDirections.size,3,'ground balls reach all outfields through interception failures');
const original=L.trial(bundle,'compact-contract'),summary=JSON.stringify(L.summarize([original])),copy=JSON.parse(JSON.stringify(original)),bytes=JSON.stringify(copy).length;L.compactTrial(copy);assert.equal(JSON.stringify(L.summarize([copy])),summary);assert(JSON.stringify(copy).length<bytes);assert.equal(copy.traces[0]?.matchup?.decision,original.traces[0]?.matchup?.decision);
for(const arm of ['S','C','G']){const chances=[];for(const trait of ['盗塁○','none','盗塁×']){const s=L.config('steal');s.runnerGrade='S';s.runnerTrait=trait;s.catcherGrade=arm;const x=L.create(L.setup(s),1),r=x.state.bases[0];chances.push(F.stealExecution(x,r,E.currentPitcher(x),1).chance);}assert(chances[0]>chances[1]&&chances[1]>chances[2]);console.log('steal',arm,chances);}
const forcedSteals=[];for(const arm of ['S','C','G']){const rows=[];for(const trait of ['盗塁○','none','盗塁×']){const s=L.config('steal');Object.assign(s,{runnerGrade:'S',runnerTrait:trait,catcherGrade:arm});const x=L.create(L.setup(s),1),runner=x.state.bases[0],pitcher=E.currentPitcher(x),row={arm,trait,attempts:10000,safe:0};for(let seed=0;seed<row.attempts;seed++){x.rng=E.createRNG('paired-steal:'+seed);x.state.bases=[runner,null,null];x.state.outs=0;x.state.virtualOuts=0;x.state.playActions=[];const event=F.steal(x,pitcher,{fromBase:1});assert.equal(event.stealExecution.trait,trait==='none'?null:trait);row.safe+=event.stolenBase;}rows.push(row);forcedSteals.push(row);}assert(rows[0].safe>rows[1].safe&&rows[1].safe>rows[2].safe);}fs.writeFileSync('test-artifacts/daily-0911-forced-steal.json',JSON.stringify(forcedSteals,null,2));
const bunt=[];for(const trait of ['バント○','none','バント×']){const s=L.config('bunt');Object.assign(s,{inning:8,half:'top',horizon:'pa',buntTrait:trait});const bundle=L.setup(s),row={trait,count:1500,success:0};for(let seed=0;seed<row.count;seed++){const x=L.create(bundle,seed),b=E.currentBatter(x),p=E.currentPitcher(x);for(let n=0;n<100;n++){const ball=T.resolveBunt(x,p,b),a=E.applyPitch(x,ball,b,p);if(a.ended){row.success+=a.result==='sacrificeBunt';break;}}}bunt.push(row);}console.log('forced bunt',bunt);
assert(bunt[0].success>bunt[1].success&&bunt[1].success>bunt[2].success,'trait reaches completed sacrifice result');
// Same observed trajectory, different terminal outcome / throw: identical early defense.
const base={eventVersion:2,outcome:'inPlay',ballType:'fly',fielderIndex:7,landingPoint:[400,100],fieldingPoint:[400,100],batter:{key:'b'},runnersBefore:[],runnersAfter:[],actions:[]};
const a=R.toReplayEvent({...base,result:'single',transfers:[{fromIndex:7,toIndex:5,toBase:2}]}),z=R.toReplayEvent({...base,result:'flyout',transfers:[]}),pa=R.animationPlan(a),pz=R.animationPlan(z);
for(let i=0;i<9;i++)for(const dt of [200,500])assert.deepEqual(JSON.parse(JSON.stringify(R.fieldingAnimation(a,pa,pa.pitchEnd+dt,i).position)),JSON.parse(JSON.stringify(R.fieldingAnimation(z,pz,pz.pitchEnd+dt,i).position)));
console.log('PASS force masks, pitcher cover, steal execution trait, bunt final outcome, outcome-blind early defense');
const alignmentGame=E.newGame(g.teams,'alignment-before-contact');for(let i=0;i<150&&!alignmentGame.state.finished;i++){const expected=JSON.stringify(T.alignment(alignmentGame).positions),e=E.onePitch(alignmentGame);assert.equal(JSON.stringify(e.defensivePositions),expected,'defensive origin captured before result changes outs/score');}
