const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js','custom-match-core.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=SL_ENGINE,F=SL_FIELDING,L=SL_LAB,names=['P','C','1B','2B','3B','SS','LF','CF','RF'];
const report={fixtures:[],matches:[],bunts:[],failures:[]};
const game=seed=>E.newGame(['away','home'].map(s=>E.makeTeam('オールC',s,[],E.CONFIG)),seed);
function fly(depth,angle,hang=3){return {outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:hang*9.81/(2*Math.sin(Math.PI/4)),launchAngle:45,sprayAngle:angle,type:'FLY',hangTime:hang,horizontalSpeed:(depth<=180?depth:180+(depth-180)/.55)/hang,deceleration:62}};}
function movement(p){const end=p.interception.time;return p.defensivePlan.tracks.map((track,index)=>{const legs=track.legs.filter(l=>l.start<end).map(l=>({...l,end:Math.min(end,l.end),to:F.trackPosition(track,Math.min(end,l.end))}));return {position:names[index],distance:legs.reduce((d,l)=>d+Math.hypot(l.to[0]-l.from[0],l.to[1]-l.from[1]),0),maxDepth:Math.max(Math.hypot(track.origin[0]-400,track.origin[1]-430),...legs.map(l=>Math.hypot(l.to[0]-400,l.to[1]-430))),legs};});}
function inspect(p,normal=false){const rows=p.roleEvaluations||[];for(const row of rows){assert.equal(row.fielders[1].base,4,'catcher left home responsibility');assert(!['PRIMARY FIELDING','SECONDARY CHASE','BACKUP'].includes(row.fielders[0].role),'pitcher chases/backs up an outfield fly');if(normal&&row.at>=.8){for(const i of [0,1,2,3,4,5])assert(!['PRIMARY FIELDING','SECONDARY CHASE'].includes(row.fielders[i].role),names[i]+' chased normal fly');}}
 const moves=movement(p);assert(moves[0].legs.every(l=>!['primary','secondary','backup'].includes(l.role)),'P actual chase');assert(moves[1].legs.every(l=>l.to[0]===400&&l.to[1]>=430),'C actual movement away from home');
 return {fielder:names[p.fielderIndex],caught:p.interception.airborne,movement:moves,roles:rows.filter(r=>r.fielders.some(f=>f.roleChangeTime!=null)).map(r=>({at:r.at,primary:r.primary,secondary:r.secondary,baseEvaluations:r.baseEvaluations,fielders:r.fielders.map(f=>({position:f.position,naturalCandidate:f.naturalCandidate,candidateReason:f.candidateReason,catchability:f.catchability,interceptETA:f.interceptETA,role:f.role,roleReason:f.roleReason,chaseStart:f.chaseStart,chaseEnd:f.chaseEnd,chaseExitReason:f.chaseExitReason,nextResponsibility:f.nextResponsibility,base:f.base}))}))};}
for(const [id,depth,angle,expected]of [['A',320,0,7],['B',245,0,null],['C',320,.6,8],['D',240,.5,null],['E',320,-.6,6],['F',230,.35,null],['G',320,0,7],['H',320,.6,8]]){const g=game('emergency-'+id);if(id==='H')g.state.bases[1]=g.teams[0].lineup[2];g.rng=()=>.5;g.tacticalRng=()=>.999;const p=fly(depth,angle);E.applyPitch(g,p,E.currentBatter(g),E.currentPitcher(g));if(expected!=null)assert.equal(p.fielderIndex,expected);const result=inspect(p,expected!=null);if(id==='B'){assert(p.roleEvaluations[0].fielders[3].naturalCandidate&&p.roleEvaluations[0].fielders[5].naturalCandidate&&p.roleEvaluations[0].fielders[7].naturalCandidate);assert(p.roleEvaluations.some(r=>r.fielders.some(f=>f.chaseEnd!=null)));}if(id==='G')assert(p.roleEvaluations.every(r=>r.baseEvaluations.filter(b=>b.assignedFielder!=null).length<4));if(id==='H'){const b=p.roleEvaluations[0].baseEvaluations;assert.equal(b.find(b=>b.base===2).requiredState,'POTENTIAL');assert.equal(b.find(b=>b.base===3).requiredState,'POTENTIAL');}report.fixtures.push({id,...result});console.log('PASS fixture',id,result.fielder);}
{const g=game('reproduced-catcher-regression');const p={outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:38.05901440722361,launchAngle:60.18672574777156,sprayAngle:-.5738985646530783,type:'FLY',hangTime:6.73229662439763,horizontalSpeed:61.89833305962655,deceleration:62,height:277.8916581246068}};g.rng=()=>.5;g.tacticalRng=()=>.999;E.applyPitch(g,p,E.currentBatter(g),E.currentPitcher(g));assert.equal(p.fielderIndex,6);report.fixtures.push({id:'observed-old-C-to-3B',...inspect(p,true)});console.log('PASS reproduced P chase / C third-base regression');}
{const g=game('outfield-gap-not-forced-catch'),p=fly(326,-.35,3);g.rng=()=>.5;g.tacticalRng=()=>.999;E.applyPitch(g,p,E.currentBatter(g),E.currentPitcher(g));assert(p.fielderIndex>=6);assert.equal(p.interception.airborne,false,'outfield ownership must not force an impossible catch');report.fixtures.push({id:'deep-gap-missed-catch',...inspect(p,true)});console.log('PASS deep gap: outfielder pickup, no forced catch');}
// Direct physical bunt fixtures prove P and C are still allowed to field locally.
for(const [position,v,angle]of [['P',14,0],['C',4,0]]){const g=game('local-bunt-'+position);g.rng=()=>.5;g.tacticalRng=()=>.999;g.state.bases[0]=g.teams[0].lineup[2];const p={outcome:'inPlay',bunt:true,battedQuality:.5,physical:{exitVelocity:v,launchAngle:0,sprayAngle:angle,type:'GROUND',hangTime:0,horizontalSpeed:v*6,deceleration:48}};E.applyPitch(g,p,E.currentBatter(g),E.currentPitcher(g));assert.equal(names[p.fielderIndex],position);assert(p.defensivePlan.tracks[p.fielderIndex].legs.some(l=>l.role==='primary'&&Math.hypot(l.to[0]-l.from[0],l.to[1]-l.from[1])>0));report.bunts.push({position,fielder:names[p.fielderIndex],result:p.record,movement:movement(p)});console.log('PASS local bunt',position);}
{const g=game('fixture-J-543');g.state.bases[0]=g.teams[0].lineup[3];g.rng=()=>.5;g.tacticalRng=()=>.999;
 const p={outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:35,launchAngle:0,sprayAngle:-.75,type:'GROUND',hangTime:0,horizontalSpeed:210,deceleration:48,height:0}};
 const result=E.applyPitch(g,p,E.currentBatter(g),E.currentPitcher(g));assert.equal(result.result,'doublePlay');assert.deepEqual(p.throws.map(t=>[t.fromIndex,t.toIndex,t.toBase]),[[4,3,2],[3,2,1]]);assert.equal(g.state.outs,2);report.fixtures.push({id:'J',result:result.result,throws:p.throws,movement:movement(p)});console.log('PASS fixture J 5-4-3');}
// Translating the defensive structure does not introduce an absolute territory wall.
{const origins=F.layout.positions,point=[410,170],shift=p=>[p[0]+130,p[1]-100];assert.deepEqual(F.process.naturalAt(origins,origins,point).map(x=>x.naturalCandidate),F.process.naturalAt(origins.map(shift),origins.map(shift),shift(point)).map(x=>x.naturalCandidate));}
for(const [position,depth]of [['P',90],['C',5]]){const g=game('local-pop-'+position),p=fly(depth,0,2);F.geometry(g,p);assert.equal(names[p.fielderIndex],position);console.log('PASS local popup',position);}
for(let i=0;i<6;i++){const seed='emergency-night-C-C-'+i,g=game(seed);E.advance(g,'game');assert(g.state.finished);const entries=[];for(const e of g.state.events){if(!e.physical||e.ballType!=='fly'||e.result==='homeRun'||!e.pursuit)continue;const depth=F.process.ballAt(e,e.physical.hangTime).depth;if(depth<220)continue;const descent=Array.from({length:Math.ceil(e.physical.hangTime/.04)},(_,j)=>({at:j*.04,...F.process.ballAt(e,j*.04)})).find(b=>b.at>e.physical.hangTime/2&&b.height<=11);
 const ds=descent?e.defensivePositions.map(o=>Math.hypot(o[0]-descent.point[0],o[1]-descent.point[1])):[],nearest=ds.indexOf(Math.min(...ds));
 const normal=nearest>=6&&e.defense[nearest].reaction+ds[nearest]*1.16/e.defense[nearest].moveSpeed<=descent.at;try{inspect(e,normal);}catch(error){fs.writeFileSync('test-artifacts/emergency-failure.json',JSON.stringify({seed,event:e},null,2));throw error;}entries.push({sequence:e.sequence,inning:e.inning,half:e.half,depth,normal,...inspect(e,normal)});}assert(entries.some(e=>e.normal));assert.deepEqual(g.state.events.flatMap(e=>SL_CUSTOM_MATCH.anomalies(e)),[]);report.matches.push({seed,score:g.state.score,finished:g.state.finished,events:g.state.events.length,inspectedFlies:entries});console.log('PASS normal C-C',i,g.state.score,'inspected flies',entries.length);}
fs.writeFileSync('test-artifacts/emergency-fielding-movement.json',JSON.stringify(report,null,2));
