(()=>{'use strict';const L=SL_LAB,E=SL_ENGINE,$=id=>document.getElementById(id);let scenario=L.config(),report=null,before=null,worker=null,viewer=null,replay=null,replayScope=null,replayStartPA=0,replayDone=false,dbPlayers=[];
try{dbPlayers=E.readDB(localStorage).players;}catch{}
const roles={batter:'現打者',next:'次打者',pitcher:'投手',catcher:'捕手',runner:'共通走者',runner1:'一塁走者',runner2:'二塁走者',runner3:'三塁走者',bench:'攻撃控え',relief:'救援 / 抑え',defensiveBench:'守備控え'};
function node(tag,text,parent){const n=document.createElement(tag);if(text!==null)n.textContent=text;if(parent)parent.append(n);return n;}
function options(el,items,value){el.replaceChildren();for(const [v,t] of items){const o=node('option',t,el);o.value=v;}if(!items.some(([v])=>String(v)===String(value))){const o=node('option','CUSTOM / '+value,el);o.value=value;}el.value=String(value);}
function status(s){$('status').textContent=s;}
function gradeRaw(role){const r=role.startsWith('runner')?'RUNNER':role==='pitcher'||role==='relief'?'PITCHER':role==='catcher'?'CATCHER':'BATTER';return L.preset(r,role.startsWith('runner')?scenario.runnerGrade:role==='batter'?scenario.batterGrade:role==='next'?scenario.nextGrade:role==='catcher'?scenario.catcherGrade:role==='pitcher'?scenario.pitcherGrade:scenario.benchGrade,role.startsWith('runner')?scenario.runnerTrait:role==='batter'?scenario.buntTrait:'none');}
function getPlayer(){return scenario.players[$('role').value]||gradeRaw($('role').value);}
function editPlayer(){const role=$('role').value;scenario.players[role]??=gradeRaw(role);return scenario.players[role];}
function settings(){const root=$('settings');root.replaceChildren();function select(label,key,items){const l=node('label',label,root),s=node('select',null,l);s.dataset.setting=key;options(s,items,scenario[key]);s.onchange=()=>{scenario[key]=typeof scenario[key]==='number'?Number(s.value):s.value;};}
 select('回','inning',Array.from({length:9},(_,i)=>[i+1,`${i+1}回`]));select('表 / 裏','half',[['top','表'],['bottom','裏']]);select('アウト','outs',[[0,'0死'],[1,'1死'],[2,'2死']]);select('打順','order',Array.from({length:9},(_,i)=>[i+1,`${i+1}番`]));select('投手疲労（投球数）','fatigue',[[0,'0球 / fresh'],[40,'40球'],[80,'80球'],[110,'110球'],[140,'140球'],[180,'180球']]);select('観測範囲','horizon',[['half','半イニング終了まで'],['pa','1打席終了まで'],['game','試合終了まで']]);
 for(let i=0;i<2;i++){const l=node('label',i?'HOME score':'AWAY score',root),n=node('input',null,l);n.type='number';n.min=0;n.value=scenario.score[i];n.onchange=()=>scenario.score[i]=Number(n.value);}
 const l=node('label','走者配置',root),sel=node('select',null,l);options(sel,Array.from({length:8},(_,m)=>[m,m?['一','二','三'].filter((_,i)=>m&(1<<i)).join('・')+'塁':'走者なし']),scenario.bases.reduce((m,b,i)=>m+(b?(1<<i):0),0));sel.onchange=()=>scenario.bases=[0,1,2].map(i=>!!(Number(sel.value)&(1<<i)));
 const lr=node('label','救援候補',root),sr=node('select',null,lr);options(sr,[[0,'なし'],[1,'あり']],scenario.relief?1:0);sr.onchange=()=>scenario.relief=sr.value==='1';}
function players(){const p=getPlayer();const root=$('abilities');root.replaceChildren();for(const [k,title]of Object.entries({meet:'ミート',power:'パワー',speed:'走力',arm:'肩',fielding:'守備',catching:'捕球',velocity:'球速',control:'制球',stamina:'スタミナ'})){const group=['velocity','control','stamina'].includes(k)?'pitching':'batting',range=E.CONFIG.ranges[k]||[1,20],value=p[group]?.[k],l=node('label',`${title} / 現在 ${value??'未設定'}`,root),s=node('select',null,l);options(s,[['keep','現在値'],['S','HIGH / S'],['C','MID / C'],['G','LOW / G']],'keep');s.onchange=()=>{if(s.value==='keep')return;const raw=editPlayer();raw[group]??={};raw[group][k]=L.gradeValue(k,s.value);players();};}
 const trait=(p.specials||[]).find(x=>['盗塁○','盗塁×','バント○','バント×'].includes(x));$('trait').value=trait||'none';}
options($('role'),Object.entries(roles),'runner');options($('playerSource'),[['preset','TEST PRESET'],...dbPlayers.map((p,i)=>[i,`${p.name||'名称未設定'} / ${p.team||'—'}`])],'preset');
$('role').onchange=()=>{const raw=scenario.players[$('role').value],i=raw?dbPlayers.findIndex(p=>p.id!=null&&p.id===raw.id):-1;$('playerSource').value=i>=0?String(i):'preset';players();};$('playerSource').onchange=()=>{const role=$('role').value;scenario.players[role]=$('playerSource').value==='preset'?gradeRaw(role):JSON.parse(JSON.stringify(dbPlayers[Number($('playerSource').value)]));players();};
$('trait').onchange=()=>{const p=editPlayer();p.specials=(p.specials||[]).filter(x=>!['盗塁○','盗塁×','バント○','バント×'].includes(x));if($('trait').value!=='none')p.specials.push($('trait').value);};
options($('axis'),[['none','比較なし'],...Object.entries(L.axes).map(([k,a])=>[k,a.label])],'runnerSpeed');
for(const [id,s]of Object.entries(L.scenarios)){const b=node('button',s.label,$('presets'));b.onclick=()=>{scenario=L.config(id);settings();players();for(const n of $('presets').children)n.setAttribute('aria-pressed',String(n===b));};}
$('readCustom').onclick=()=>$('custom').value=JSON.stringify(scenario,null,2);$('applyCustom').onclick=()=>{try{const s=JSON.parse($('custom').value);L.setup(s);scenario=s;settings();players();status('CUSTOMを適用しました。');}catch(e){status(e.message);}};
function launch(input,axis,count,seed){try{L.setup(input);if(!Number.isInteger(count)||count<1||count>10000)throw Error('試行数は1〜10000');if(location.protocol==='file:')throw Error('Workerを利用するためHTTP(S)で開いてください。');worker?.terminate();worker=new Worker('engine-lab-worker.js');$('run').disabled=true;$('cancel').disabled=false;status('ENGINE実行中…');$('progress').value=0;worker.onmessage=({data})=>{if(data.type==='progress'){status(`${data.completed} / ${data.total} trials · ${(data.elapsedMs/1000).toFixed(1)} sec`);$('progress').value=data.completed/data.total;}if(data.type==='complete'){report=data.report;report.savedSeeds=[];renderReport();status('完了');$('progress').value=1;stop();}if(data.type==='error'){status(data.message);stop();}};worker.onerror=e=>{status(e.message||'Worker load failed');stop();};worker.postMessage({scenario:input,axis,count,seed});}catch(e){status(e.message);}}
function stop(){worker?.terminate();worker=null;$('run').disabled=false;$('cancel').disabled=true;}
$('run').onclick=()=>launch(scenario,$('axis').value,Number($('count').value==='custom'?$('customCount').value:$('count').value),$('seed').value);$('cancel').onclick=()=>{stop();status('中止しました。未完了データは保存されていません。');};
const percent=(n,d)=>d?`${(100*n/d).toFixed(2)}%`:'—';
function table(root,heads,rows){const t=node('table',null,root),h=node('tr',null,node('thead',null,t));heads.forEach(x=>node('th',x,h));const body=node('tbody',null,t);for(const row of rows){const tr=node('tr',null,body);row.forEach(x=>node('td',x,tr));}}
function renderReport(){const r=report;$('results').hidden=false;$('timing').textContent=`${r.version} · ${r.groups.reduce((n,g)=>n+g.trials.length,0)} trials completed in ${(r.elapsedMs/1000).toFixed(2)} sec · ${r.date}`;const root=$('summary');root.replaceChildren();const rows=[],keys=[...new Set(r.groups.flatMap(g=>Object.keys(g.summary.initialDecision)))];for(const key of keys)rows.push([key+'（初回）',...r.groups.map(g=>percent(g.summary.initialDecision[key]||0,g.trials.length))]);
 for(const key of ['PINCH_HIT','PINCH_RUN','DEFENSIVE_SUB','CONTINUE','RELIEF','CLOSER','MATCHUP:CHALLENGE','MATCHUP:CAUTIOUS','MATCHUP:INTENTIONAL_WALK','ALIGNMENT:NORMAL','ALIGNMENT:IN','ALIGNMENT:DEEP','DEFENSE:SECURE_RETURN','DEFENSE:HOLD_BALL'])rows.push([key+'（trial内）',...r.groups.map(g=>percent(g.trials.filter(t=>t.decision[key]).length,g.trials.length))]);
 for(const [key,label]of Object.entries({scored:'得点率',noScore:'無得点率',tookLead:'勝ち越し率',tiedAtEnd:'観測終了時 同点率',draw:'試合引き分け率',outEnded:'アウト終了率'}))rows.push([label,...r.groups.map(g=>percent(g.summary.outcome[key]||0,g.trials.length))]);
 rows.push(['盗塁成功率',...r.groups.map(g=>{const x=g.summary.execution;return percent(x.stolenBase||0,(x.stolenBase||0)+(x.caughtStealing||0));})]);
 for(const key of ['SAC_BUNT','SAFETY_BUNT','SQUEEZE','HIT_AND_RUN'])rows.push([key+' 成功率',...r.groups.map(g=>{const x=g.summary.execution;return percent(x[key+':success']||0,(x[key+':success']||0)+(x[key+':failure']||0));})]);
 table(root,['指標 / 分母',...r.groups.map(g=>g.label+' n='+g.trials.length)],rows);$('flags').replaceChildren();const flags=[...r.anomalies,...r.groups.flatMap(g=>g.summary.anomalies)];node('p',`異常候補 ${flags.length}件。失敗結果だけでは異常と判定しません。最終判断は人間が行ってください。`,$('flags'));for(const flag of flags.slice(0,20))node('p',`${flag.severity} / ${flag.rule} / ${flag.detail}`,$('flags'));renderTrials();renderBeforeAfter();}
function renderTrials(){const root=$('trials');root.replaceChildren();if(!report)return;let shown=0;for(let gi=0;gi<report.groups.length;gi++){const g=report.groups[gi];for(const t of g.trials){const key=gi+'|'+t.seed,saved=report.savedSeeds?.includes(key);if($('filter').value==='flagged'&&!t.anomalies.length||$('filter').value==='saved'&&!saved||!t.seed.includes($('search').value))continue;if(shown++>=50)break;const row=node('div',null,root);row.className='trial';node('span',t.classification,row).className='badge '+t.classification;node('span',`${g.label} · ${t.seed} · ${t.initialDecision} · ${t.outcome.finalScore.join('–')}`,row);const save=node('button',saved?'★ 保存済み':'☆ seed保存',row);save.onclick=async()=>{report.savedSeeds??=[];if(!report.savedSeeds.includes(key))report.savedSeeds.push(key);try{await putReport($('saveName').value||'saved-seeds',report);renderTrials();history();status('seedと再現条件を保存しました。');}catch(e){status('保存失敗: '+e.message);}};node('button','2D再生',row).onclick=()=>play(g,t);node('button','理由',row).onclick=()=>{$('replaySection').hidden=false;$('trace').textContent=JSON.stringify(t,null,2);$('trace').parentElement.open=true;};}}}
$('filter').onchange=renderTrials;$('search').oninput=renderTrials;
function play(group,t){try{if(group.bundle.config.version!==E.CONFIG.version)throw Error('このENGINEでは別versionのseed再計算はできません。対応versionで開いてください。');replay=L.create(group.bundle,t.seed);viewer?.reset();$('replaySection').hidden=false;$('replayLabel').textContent=`${group.label} / ${t.seed} / 保存時の選手コピーで再生`;replayDone=false;replayScope=group;replayStartPA=replay.state.paCompleted;if(!viewer)viewer=SL_MATCH_VIEWER.create({root:$('matchViewer'),getGame:()=>replayDone?{...replay,state:{...replay.state,finished:true,finishReason:replay.state.finishReason||'scenarioReplayComplete'}}:replay,step:mode=>{if(replayDone)return [];const records=[];do{const e=E.onePitch(replay);if(!e)break;records.push(e);const s=replayScope.bundle.scenario;replayDone=replay.state.finished||(s.horizon==='half'&&(replay.state.inning!==s.inning||replay.state.half!==s.half))||(s.horizon==='pa'&&replay.state.paCompleted!==replayStartPA);if(mode!=='game')break;}while(!replayDone);return records;},onChange:()=>{}});$('trace').textContent=JSON.stringify(t,null,2);$('matchViewer').querySelector('[data-action="view"]').click();$('replaySection').scrollIntoView({behavior:'smooth'});}catch(e){status(e.message);}}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=node('a',null);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('json').onclick=()=>download(JSON.stringify(report,null,2),'sl-engine-lab.json','application/json');$('csv').onclick=()=>download(L.csv(report),'sl-engine-lab.csv','text/csv');
function openDB(){return new Promise((resolve,reject)=>{const q=indexedDB.open('sl_world_engine_lab_006',1);q.onupgradeneeded=()=>q.result.createObjectStore('reports',{keyPath:'name'});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function storage(mode,action){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('reports',mode),req=action(tx.objectStore('reports'));tx.oncomplete=()=>{db.close();resolve(req.result);};tx.onerror=()=>{db.close();reject(tx.error);};tx.onabort=()=>{db.close();reject(tx.error||Error('保存中断'));};});}
const putReport=(name,data)=>storage('readwrite',store=>store.put({name,date:new Date().toISOString(),report:data}));
$('save').onclick=async()=>{try{await putReport($('saveName').value.trim()||'engine-lab-'+Date.now(),report);status('履歴保存完了');history();}catch(e){status('保存失敗。JSON exportで保存してください: '+e.message);}};
async function history(){try{const list=await storage('readonly',s=>s.getAll());$('history').replaceChildren();for(const item of list.reverse()){const row=node('div',null,$('history'));row.className='trial';node('span',`${item.name} · ${item.date}`,row);node('button','開く',row).onclick=()=>{report=item.report;renderReport();};node('button','BEFOREに指定',row).onclick=()=>{before=item.report;renderBeforeAfter();status('BEFOREを指定しました。');};node('button','同じ条件を再実行',row).onclick=()=>{before=item.report;const r=item.report;scenario=JSON.parse(JSON.stringify(r.groups[0].bundle.scenario));if(r.axis!=='none'){
 // The first group is already A. Reapplying the axis reconstructs B/C from its unchanged fields.
 }settings();players();launch(scenario,r.axis,r.trialCount,r.seedPrefix);};}}catch(e){node('p','履歴が利用できません: '+e.message,$('history'));}}
function renderBeforeAfter(){const root=$('beforeAfter');root.replaceChildren();if(!before||!report||before===report)return;node('p',`BEFORE ${before.version} → AFTER ${report.version}。条件・seed群が同じか確認してください。`,root);const rows=[];for(let i=0;i<report.groups.length;i++){const a=before.groups[i],b=report.groups[i];if(!a)continue;const same=JSON.stringify(a.bundle.scenario)===JSON.stringify(b.bundle.scenario)&&before.seedPrefix===report.seedPrefix;for(const k of new Set([...Object.keys(a.summary.initialDecision),...Object.keys(b.summary.initialDecision)]))rows.push([b.label,k,same?'同条件':'条件差あり',percent(a.summary.initialDecision[k]||0,a.trials.length),percent(b.summary.initialDecision[k]||0,b.trials.length)]);}table(root,['条件','初回判断','互換性','BEFORE','AFTER'],rows);}
$('import').onchange=async()=>{try{const r=JSON.parse(await $('import').files[0].text());if(r.format!=='SL_WORLD_ENGINE_LAB'||r.schemaVersion!==1||!Array.isArray(r.groups))throw Error('対応するLAB JSONではありません');for(const g of r.groups){L.validate(g.bundle.scenario);if(!Array.isArray(g.trials))throw Error('trial list missing');g.summary=L.summarize(g.trials);}report=r;renderReport();status('JSONを読み込みました。');}catch(e){status(e.message);}};
settings();players();history();
})();
