// Directed roads and diagnostic checks, independent of aggregate frequency.
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({console});for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006-viewer.js','engine006.js','engine-lab-core.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);const E=c.SL_ENGINE,L=c.SL_LAB,T=c.SL_TACTICS,V=c.SL_MATCH_VIEWER;
const mk=id=>L.create(L.setup(L.config(id)),7);
for(const [id,road]of [['squeeze','SQUEEZE'],['steal','HIT_AND_RUN']]){const g=mk(id);assert(T.extraOptions(g,E.currentBatter(g)).find(x=>x.decision===road).legal);g.state.outs=2;assert(!T.extraOptions(g,E.currentBatter(g)).find(x=>x.decision===road).legal);}
const clear=mk('steal');clear.state.bases=[null,null,null];assert(T.extraOptions(clear,E.currentBatter(clear)).find(x=>x.decision==='SAFETY_BUNT').legal);
const closer=L.config('relief');closer.inning=9;assert(L.trial(L.setup(closer),1).operations.some(x=>x.decision==='CLOSER'));
const def=L.config('alignment');def.players.defensiveBench=L.preset('BATTER');def.players.defensiveBench.batting.fielding=20;assert(L.trial(L.setup(def),1).operations.some(x=>x.decision==='DEFENSIVE_SUB'));
const alignment=mk('alignment'),p=E.currentPitcher(alignment),b=E.currentBatter(alignment);assert.equal(T.alignment(alignment).decision,'IN');alignment.state.bases=[null,null,null];assert.equal(T.alignment(alignment).decision,'DEEP');alignment.state.inning=1;assert.equal(T.alignment(alignment).decision,'NORMAL');
const w=mk('walk'),batter=E.currentBatter(w),pitcher=E.currentPitcher(w),d={decision:'INTENTIONAL_WALK',matchup:{decision:'INTENTIONAL_WALK'}};const pitch=T.execute(w,pitcher,batter,d);assert(pitch.intentionalWalk);w.state.balls=3;E.applyPitch(w,pitch,batter,pitcher);assert.equal(w.state.bases[0].key,batter.key);assert.equal(w.state.pitching[pitcher.key].pitches,0);
const known={sequence:1,outsBefore:2,outsAfter:2,runnersBefore:[{},null,null],runnersAfter:[null,null,null],tactics:{decision:'SAC_BUNT'},eventType:'pitch'};assert(L.anomalies(known).some(x=>x.rule==='TWO_OUT_SACRIFICE'));
known.tactics.decision='STEAL_2B';known.eventType='baserunning';known.toBase=2;known.runnersBefore[1]={};assert(L.anomalies(known).some(x=>x.rule==='OCCUPIED_STEAL'));
const groups=L.compare(L.config('steal'),'runnerSpeed');const scrub=b=>{b=JSON.parse(JSON.stringify(b));for(const t of b.teams)for(const p of t.lineup){if(p.profile.id==='LAB_RUNNER'){p.effective.speed=0;p.profile.batting.speed=0;p.name='RUNNER';p.profile.name='RUNNER';}}for(const [key,p]of Object.entries(b.scenario.players))if(key.startsWith('runner')){p.batting.speed=0;p.name='RUNNER';}b.scenario.runnerGrade='compared';return b;};assert.deepEqual(scrub(groups[0].bundle),scrub(groups[1].bundle));
let seen=new Set();for(let seed=0;seed<150;seed++){const s=L.config(seed%2?'squeeze':'steal');s.runnerGrade='S';const t=L.trial(L.setup(s),seed,{events:true});for(const e of t.events){seen.add(e.tactics.decision);const r=V.toReplayEvent(e),p=V.animationPlan(r);if(e.runningExecution){assert(p.steal);assert(p.transfers.length);}assert(!t.anomalies.some(x=>x.severity==='CRITICAL'));}}
assert(seen.has('SQUEEZE')&&seen.has('HIT_AND_RUN'));console.log('PASS directed: safety/squeeze/hit-run legality, IBB, closer, defensive replacement, three alignments, diagnostic injections, single-axis identity, hybrid replay');
// Existing official grade tables must recognize every advertised test grade.
vm.runInContext(fs.readFileSync('lineup-display.js','utf8'),c);for(const [stat,values]of Object.entries(L.gradeValues))for(const [grade,value]of Object.entries(values))assert.equal(c.SL_ABILITY_DISPLAY.getAbilityRank(stat,value),grade);
// A pitcher-slot pinch hitter is followed by a legal bullpen replacement.
const pg=mk('pinchHit'),off=pg.teams[1],old=off.pitcher;pg.state.order[1]=8;old.effective.meet=1;old.effective.power=20;off.lineup[8].effective.meet=1;off.lineup[8].effective.power=20;off.bench.push(E.adaptPlayer(L.preset('PITCHER','C'),'extra_relief',E.CONFIG));const ops=T.prepare(pg);assert(ops.some(x=>x.decision==='PINCH_HIT'));assert.equal(off.pendingPitcherSlot,8);pg.state.half='top';pg.state.inning=9;pg.state.prepared=null;T.prepare(pg);assert.equal(off.pitcher.key,'extra_relief');assert.equal(off.lineup[8].key,'extra_relief');assert.equal(off.pendingPitcherSlot,undefined);
console.log('PASS: official S/C/G grades and pitcher-slot pinch hitter/relief continuity');

