// Both contexts use the corrected return annotation; daily-corrections.test.cjs compares against original fielding separately.
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto'),cp=require('child_process');
const files=['engine006-fielding.js','engine006-tactics.js','engine006.js','engine-lab-core.js','engine-lab-presentation.js'];
function context(old=false){const c=vm.createContext({console,TextEncoder});for(const f of files)vm.runInContext(old&&f!=='engine006-fielding.js'?cp.execFileSync('git',['show','b6c8bc3eb1034631232aac70a3994550aa1b7983:'+f],{encoding:'utf8',maxBuffer:5e6}):fs.readFileSync(f,'utf8'),c);return c;}
const c=context(),old=context(true),L=c.SL_LAB,P=c.SL_LAB_PRESENTATION,hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const groups=L.compare(L.config('steal'),'runnerSpeed'),oldGroups=old.SL_LAB.compare(old.SL_LAB.config('steal'),'runnerSpeed');
const sizes=[];
for(const total of [3000,10000]){for(let gi=0;gi<3;gi++){const g=groups[gi],n=Math.floor(total/3)+(gi<total%3?1:0);g.trials=[];for(let i=0;i<n;i++){const seed='daily-001:'+i,t=L.trial(g.bundle,seed);assert.equal(hash(t),hash(old.SL_LAB.trial(oldGroups[gi].bundle,seed)),'seed drift '+gi+' '+seed);g.trials.push(t);}g.summary=L.summarize(g.trials);}
const r={format:'SL_WORLD_ENGINE_LAB',schemaVersion:1,version:c.SL_ENGINE.CONFIG.version,date:'2026-09-08T00:00:00.000Z',seedPrefix:'daily-001',axis:'runnerSpeed',trialCount:total%3?null:total/3,elapsedMs:0,groups,anomalies:L.sensitivity(groups,'runnerSpeed'),savedSeeds:[]},digest=hash(r),sol=P.solReport(r,r),bytes=Buffer.byteLength(JSON.stringify(sol));assert.equal(hash(r),digest);assert(!sol.groups);assert(sol.interestingSeeds.length<=60);assert(bytes<500000);assert.deepEqual(JSON.parse(JSON.stringify(sol.primaryMetrics)),JSON.parse(JSON.stringify(P.metrics(r).primary)));assert(sol.allMetrics.rawByCondition.every(g=>!g.summary.anomalies));sizes.push({total,bytes,seeds:sol.interestingSeeds.length,candidates:sol.anomalySummary.candidateCount});
if(total===3000){const archive=P.exportReport(r);assert.equal(hash(P.importReport(JSON.parse(JSON.stringify(archive))).groups),hash(groups));assert.equal(L.csv(r),L.csv(archive));}
}
// Mass anomalies: retain exact occurrence and affected-trial rates without unbounded logs.
const g=groups[0];g.trials=g.trials.slice(0,1000).map((t,i)=>({...t,anomalies:i<500?[{rule:'TWO_OUT_SACRIFICE',severity:'CRITICAL',sequence:1}]:[]}));g.summary=L.summarize(g.trials);
const mass={version:c.SL_ENGINE.CONFIG.version,date:'2026-09-08',axis:'none',trialCount:1000,groups:[g],savedSeeds:[],anomalies:[]};const out=P.solReport(mass);assert.equal(out.anomalySummary.candidateCount,500);assert.equal(out.anomalySummary.categories[0].affectedTrialRate,.5);assert.equal(out.interestingSeeds.length,5);assert(out.interestingSeeds.every(x=>x.detail.traces.length));assert(Buffer.byteLength(JSON.stringify(out))<500000);
const giant=JSON.parse(JSON.stringify(mass));giant.groups[0].trials[0].traces.push({...giant.groups[0].trials[0].traces[0],reason:['x'.repeat(50000)]});const limited=P.solReport(giant);assert(limited.interestingSeeds[0].omittedRecords.traces>0);assert.throws(()=>P.importReport(out),/完全ログJSON/);
const normal=JSON.parse(JSON.stringify(mass));normal.groups[0].trials.forEach(t=>t.anomalies=[]);normal.groups[0].summary=L.summarize(normal.groups[0].trials);assert.equal(P.solReport(normal).interestingSeeds.length,0);normal.savedSeeds=normal.groups[0].trials.map(t=>'0|'+t.seed);assert.equal(P.solReport(normal).interestingSeeds.length,60);
console.log('PASS lightweight export; 13,000 trials match pre-change policy with corrected return annotation; mass anomalies 500/1000 preserved; archive/CSV unchanged',JSON.stringify(sizes));fs.writeFileSync('test-artifacts/sol-export-sizes.json',JSON.stringify(sizes,null,2));
