const fs=require('fs'),vm=require('vm'),http=require('http'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const c=vm.createContext({console});for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006.js','engine-lab-core.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);const L=c.SL_LAB,groups=L.compare(L.config('steal'),'runnerSpeed');for(const g of groups){g.trials=Array.from({length:5},(_,i)=>L.trial(g.bundle,'daily-001:'+i));g.summary=L.summarize(g.trials);}const legacy=JSON.parse(JSON.stringify({format:'SL_WORLD_ENGINE_LAB',schemaVersion:1,version:c.SL_ENGINE.CONFIG.version,date:'2026-09-08T00:00:00.000Z',axis:'runnerSpeed',seedPrefix:'daily-001',trialCount:5,elapsedMs:12,groups,anomalies:[],savedSeeds:['0|daily-001:0']}));
(async()=>{const server=http.createServer((req,res)=>{const f=path.resolve(__dirname,'.'+decodeURIComponent(req.url.split('?')[0]));if(!f.startsWith(__dirname+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(e,b)=>{if(e)res.writeHead(404).end();else{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);}});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{let frameClock=1;window.requestAnimationFrame=fn=>setTimeout(()=>fn(frameClock+=10000),0);window.cancelAnimationFrame=clearTimeout;window.workerStarts=0;const Base=Worker;window.Worker=class extends Base{constructor(...a){super(...a);window.workerStarts++;}};});const url='http://127.0.0.1:'+server.address().port+'/engine-lab.html';await page.goto(url);
 const playerDB='[{"id":"preserve-existing-db","name":"保存選手","team":"TEST"}]';await page.evaluate(async({legacy,playerDB})=>{localStorage.setItem('sl_world_players_v01',playerDB);await new Promise((ok,no)=>{const q=indexedDB.open('sl_world_engine_lab_006',1);q.onsuccess=()=>{const db=q.result,tx=db.transaction('reports','readwrite');tx.objectStore('reports').put({name:'daily-001',date:legacy.date,report:legacy});tx.oncomplete=()=>{db.close();ok();};tx.onerror=no;};q.onerror=no;});},{legacy,playerDB});await page.reload();await page.waitForFunction(()=>document.querySelector('#history').textContent.includes('daily-001'));
 const saved=()=>page.evaluate(()=>new Promise((ok,no)=>{const q=indexedDB.open('sl_world_engine_lab_006',1);q.onsuccess=()=>{const db=q.result,tx=db.transaction('reports'),r=tx.objectStore('reports').get('daily-001');tx.oncomplete=()=>{db.close();ok(r.result.report);};tx.onerror=no;};q.onerror=no;}));assert.deepEqual(await saved(),legacy);
 assert(!(await page.locator('#advanced').evaluate(e=>e.open)));assert((await page.locator('#runSummary').innerText()).includes('3,000試行'));await page.locator('#history .history-card>button').first().click();await page.waitForFunction(()=>document.querySelector('#timing').textContent.includes('15試行')); assert(!(await page.locator('#allMetrics').evaluate(e=>e.open)));assert((await page.locator('#primaryMetrics').innerText()).includes('盗塁選択率'));
 await page.locator('#history button').filter({hasText:'BEFOREに指定'}).first().click();await page.waitForFunction(()=>document.querySelector('#beforeAfter').textContent.includes('BEFORE'));
 // Share files without leaving the test browser. All payloads come from the actual UI.
 await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async(payload)=>{window.shareKeys=Object.keys(payload);const {files}=payload;window.sharedFileCount=files.length;window.shared=JSON.parse(await files[0].text());window.sharedName=files[0].name;}});});await page.locator('#solJson').click();await page.waitForFunction(()=>window.shared);const enriched=await page.evaluate(()=>window.shared);assert.deepEqual(await page.evaluate(()=>window.shareKeys),['files']);assert.equal(await page.evaluate(()=>window.sharedFileCount),1);assert.equal(enriched.testId,'daily-001');assert.equal(enriched.totalTrialCount,15);assert(enriched.beforeAfter);assert.equal(enriched.format,'SL_WORLD_ENGINE_LAB_SOL');assert(!enriched.groups);assert.equal(enriched.comparison.conditions.length,3);assert((await page.locator('#solMeta').innerText()).includes('KB'));assert(enriched.interestingSeeds[0].detail.traces.length);assert((await page.locator('#solMeta').innerText()).includes((Buffer.byteLength(JSON.stringify(enriched))/1024).toFixed(1)+' KB'));assert((await page.evaluate(()=>window.sharedName)).includes('daily-001'));
 let downloads=0;page.on('download',()=>downloads++);await page.evaluate(()=>Object.defineProperty(navigator,'share',{configurable:true,value:async()=>{throw new DOMException('cancel','AbortError');}}));await page.locator('#solJson').click();assert((await page.locator('#shareStatus').innerText()).includes('キャンセル'));assert.equal(downloads,0);
 await page.evaluate(()=>Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false}));const download=page.waitForEvent('download');await page.locator('#solJson').click();const dl=await download,chunks=[];for await(const chunk of await dl.createReadStream())chunks.push(chunk);assert.equal(JSON.parse(Buffer.concat(chunks).toString()).schemaVersion,1);assert.equal(downloads,1);assert(await page.locator('#solCopy').isVisible());await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copied=text;}}}));await page.locator('#solCopy').click();assert.equal((await page.evaluate(()=>JSON.parse(window.copied))).testId,'daily-001');
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('unavailable');}}}));await page.locator('#solCopy').click();assert(await page.locator('#copyFallback').isVisible());
 // Full archive retains all details; lightweight shares are explicitly not import archives.
 await page.locator('#json').evaluate(e=>e.closest('details').open=true);const archiveDownload=page.waitForEvent('download');await page.locator('#json').click();const archiveChunks=[];for await(const chunk of await (await archiveDownload).createReadStream())archiveChunks.push(chunk);const archive=JSON.parse(Buffer.concat(archiveChunks).toString());assert.equal(archive.groups.length,3);
 await page.locator('#import').setInputFiles({name:'full-log.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(archive))});await page.waitForFunction(()=>document.querySelector('#importStatus').textContent.includes('読み込みました'));assert.deepEqual(await saved(),legacy);await page.locator('#saveName').fill('daily-001');await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#history').textContent.includes('daily-001 (2)'));assert.deepEqual(await saved(),legacy);
 const prior=await page.evaluate(()=>workerStarts);await page.locator('#nextAction').click();assert.equal(await page.locator('#axis').inputValue(),'catcherArm');assert((await page.locator('#fixedConditions').innerText()).includes('走者走力 S'));assert.equal(await page.evaluate(()=>workerStarts),prior);assert((await page.locator('#status').innerText()).includes('準備しました'));
 // All presets: select C for every role's key ability, inspect the actual Worker/export snapshot.
 for(const id of Object.keys(L.scenarios)){
  await page.locator('#quickPreset').selectOption(id);await page.locator('#advanced').evaluate(e=>e.open=true);
  for(const [role,stat]of [['batter','meet'],['next','meet'],['runner','speed'],['catcher','arm'],['pitcher','control'],['bench',id==='pinchRun'?'speed':'meet']]){
   await page.locator('#role').selectOption(role);if(id==='pinchRun'&&role==='bench')assert.equal(await page.locator('#abilities select').nth(2).inputValue(),'S');const index=['meet','power','speed','arm','fielding','catching','velocity','control','stamina'].indexOf(stat);await page.locator('#abilities select').nth(index).selectOption('C');assert.equal(await page.locator('#abilities select').nth(index).inputValue(),'C');
  }
  await page.locator('#readCustom').evaluate(e=>e.closest('details').open=true);await page.locator('#readCustom').click();const scenario=JSON.parse(await page.locator('#custom').inputValue());const bundle=L.setup(scenario),off=scenario.half==='top'?0:1;assert.equal(bundle.teams[off].lineup[scenario.order-1].profile.batting.meet,7);assert.equal(bundle.teams[off].lineup[scenario.order%9].profile.batting.meet,7);assert.equal(bundle.teams[1-off].pitcher.profile.pitching.control,142);for(const index of bundle.runnerIndices)if(index!=null)assert.equal(bundle.teams[off].lineup[index].profile.batting.speed,14);
  for(const group of L.compare(scenario,({walk:'nextMeet',pinchRun:'benchSpeed',pinchHit:'benchMeet'})[id]||'batterMeet')){const saved=JSON.parse(JSON.stringify(group.bundle));assert.deepEqual(saved.teams,JSON.parse(JSON.stringify(L.setup(saved.scenario).teams)));}
  if(id==='walk')assert((await page.locator('#fixedConditions').innerText()).includes('打者ミート C'));
 }
 // Inherited common runner overrides remain visible and survive editing another ability.
 await page.locator('#quickPreset').selectOption('steal');await page.locator('#advanced').evaluate(e=>e.open=true);await page.locator('#role').selectOption('runner');await page.locator('#abilities select').nth(2).selectOption('S');await page.locator('#role').selectOption('runner1');assert.equal(await page.locator('#abilities select').nth(2).inputValue(),'S');await page.locator('#abilities select').nth(0).selectOption('C');await page.locator('#readCustom').evaluate(e=>e.closest('details').open=true);await page.locator('#readCustom').click();assert.equal(JSON.parse(await page.locator('#custom').inputValue()).players.runner1.batting.speed,20);
 // Every preset has a useful primary set, and both result tables fit phone widths.
 for(const id of Object.keys(L.scenarios)){await page.locator('#quickPreset').selectOption(id);assert.equal(await page.locator('#axis').inputValue(),({steal:'runnerSpeed',bunt:'buntTrait',squeeze:'buntTrait',hitRun:'batterMeet',walk:'nextMeet',pinchHit:'benchMeet',pinchRun:'benchSpeed',relief:'fatigue',alignment:'none'})[id]);}
 await page.locator('#quickPreset').selectOption('steal');await page.locator('#count').selectOption('100');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('300試行 完了'),null,{timeout:120000});assert((await page.locator('#primaryMetrics').innerText()).includes('H&R'));await page.locator('#allMetrics').evaluate(e=>e.open=true);for(const width of [320,375,390,430]){await page.setViewportSize({width,height:844});assert(await page.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),'body overflow '+width);for(const id of ['primaryMetrics','summary','beforeAfter'])assert(await page.locator('#'+id).evaluate(e=>e.scrollWidth<=e.clientWidth),id+' overflow '+width);assert(await page.locator('#primaryMetrics td').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth)),'cell overflow '+width);}
 // Candidate -> exact seed -> viewer path (injected structural candidate only in an imported test fixture).
 const flagged=JSON.parse(JSON.stringify(legacy));flagged.groups[0].trials[0].anomalies=[{severity:'CRITICAL',rule:'TWO_OUT_SACRIFICE',sequence:1}];flagged.groups[0].trials[0].classification='CRITICAL';await page.locator('#import').setInputFiles({name:'candidate-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(flagged))});await page.waitForFunction(()=>document.querySelector('#flags').textContent.includes('2死'));await page.locator('#flags button').filter({hasText:'2Dで再生'}).first().click();assert(await page.locator('#matchViewer canvas').isVisible());await page.locator('[data-action="auto"]').click();await page.waitForFunction(()=>document.querySelector('#replayLabel').textContent.includes('一致しました'));assert.deepEqual(await saved(),legacy);
 const mismatch=JSON.parse(JSON.stringify(legacy));mismatch.groups[0].trials[0].outcome.finalScore=[99,99];await page.locator('#import').setInputFiles({name:'mismatch-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(mismatch))});await page.waitForFunction(()=>document.querySelector('#timing').textContent.includes('15試行'));await page.locator('#trialDetails').evaluate(e=>e.open=true);await page.locator('#trials button').filter({hasText:'2D再生'}).first().click();await page.locator('[data-action="auto"]').click();await page.waitForFunction(()=>document.querySelector('#flags').textContent.includes('保存結果とseed再実行が不一致'));assert.deepEqual(await saved(),legacy);
 // All UI trial counts execute through the unchanged worker. Use a single condition for bulk runs.
 await page.locator('#advanced').evaluate(e=>e.open=true);await page.locator('#axis').selectOption('none');await page.locator('#advanced').evaluate(e=>e.open=false);
 for(const count of (process.argv.includes('--quick')?[1,100]:[1,100,1000,10000])){await page.locator('#count').selectOption(String(count));await page.locator('#run').click();await page.waitForFunction(n=>document.querySelector('#status').textContent.includes(n.toLocaleString()+'試行 完了'),count,{timeout:180000});console.log('Worker UI count',count,await page.locator('#timing').innerText());}
 // Final screenshots contain actual engine results, not the diagnostic fixture.
 await page.locator('#quickPreset').selectOption('steal');await page.locator('#count').selectOption('100');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('300試行 完了'),null,{timeout:120000});await page.setViewportSize({width:390,height:844});fs.mkdirSync('test-artifacts',{recursive:true});await page.locator('#results').screenshot({path:'test-artifacts/engine-lab-ux-results.png'});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(400);await page.screenshot({path:'test-artifacts/engine-lab-ux-phone.png'});await page.locator('#results').evaluate(e=>e.scrollIntoView({behavior:'instant',block:'start'}));await page.screenshot({path:'test-artifacts/engine-lab-ux-phone-results.png'});
 assert.deepEqual(await saved(),legacy);assert.equal(await page.evaluate(()=>localStorage.getItem('sl_world_players_v01')),playerDB);assert.deepEqual(errors,[]);console.log('PASS UI browser: legacy daily-001 unchanged, 320/375/390/430 no horizontal metric scroll, all requested counts, lightweight share/download/copy/cancel and full archive import, NEXT without execution, BEFORE/AFTER, structural seed viewer, player DB preserved');
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
