const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({console});for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006-viewer.js','engine006.js','engine-lab-core.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});const E=c.SL_ENGINE,L=c.SL_LAB,T=c.SL_TACTICS,F=c.SL_FIELDING,V=c.SL_MATCH_VIEWER,copy=x=>JSON.parse(JSON.stringify(x));
assert.equal(E.CONFIG.version,'test-match-006-engine-lab-alpha1');
let eventCount=0;const baselineFiles=['engine-test.html','engine-tactics.js','engine-fielding.js','match-replay.js'];
const teams=[E.makeTeam('A','away',[],E.CONFIG),E.makeTeam('B','home',[],E.CONFIG)],snapshot=JSON.stringify(teams);
for(let seed=0;seed<30;seed++){const g=E.newGame(teams,seed);E.advance(g,'game');assert(g.state.finished);for(const e of g.state.events){eventCount++;assert.deepEqual(copy(L.anomalies?.(e)||[]),[]);const keys=e.runnersAfter.filter(Boolean).map(p=>p.key);assert.equal(new Set(keys).size,keys.length);assert(e.outsAfter<=3&&e.outsAfter>=e.outsBefore);assert(e.tactics.reason.length);if(e.eventType==='baserunning')assert(!e.runnersBefore[e.toBase-1]);if(e.defenseDecision?.decision==='HOLD_BALL'){assert(e.fielderIndex<6);assert(!e.transfers.length);}if(e.defenseDecision?.decision==='SECURE_RETURN'){assert(e.transfers.some(t=>t.kind==='return'));assert(e.defenseDecision.candidates.filter(x=>x.toBase).every(x=>x.outChance===0));}const r=V.toReplayEvent(e),p=V.animationPlan(r);for(const time of [0,p.caught,p.resultAt,p.end])assert(V.ballAnimation(r,p,time).ground.every(Number.isFinite));}
 if(seed<3)for(const mode of ['FULL','MINI','HIGHLIGHT','SKIP']){const h=E.newGame(teams,seed);while(!h.state.finished)E.advance(h,mode==='SKIP'?'game':'pitch');assert.equal(JSON.stringify(h.state),JSON.stringify(g.state));}}
assert.equal(JSON.stringify(teams),snapshot);
for(const id of Object.keys(L.scenarios)){const bundle=L.setup(L.config(id)),frozen=JSON.stringify(bundle);for(let seed=0;seed<100;seed++){const t=L.trial(bundle,seed);assert(!t.anomalies.some(a=>a.severity==='CRITICAL'),id+' '+seed);if(seed<3){assert.equal(JSON.stringify(t),JSON.stringify(L.trial(bundle,seed)));const replay=L.trial(bundle,seed,{events:true});assert.deepEqual(copy(replay.outcome),copy(t.outcome));assert.deepEqual(copy(replay.decision),copy(t.decision));}}assert.equal(JSON.stringify(bundle),frozen);}
const b=L.setup(L.config('steal')),g=L.create(b,'legal');g.state.bases[1]=g.teams[1].lineup[3];assert.equal(F.canSteal(g,1),false);assert.equal(T.stealOption(g,E.currentPitcher(g),1).weight,0);g.state.outs=2;assert.equal(T.buntOption(g,E.currentBatter(g)).weight,0);
const deep={fielderIndex:7,landingPoint:[400,90]};assert.equal(T.defenseDecision(g,deep,E.currentBatter(g),{settled:true}).decision,'SECURE_RETURN');assert.equal(T.defenseDecision(g,{fielderIndex:2,landingPoint:[550,310]},E.currentBatter(g),{settled:true}).decision,'HOLD_BALL');
const rates=[];let elapsed=performance.now();for(const group of L.compare(L.config('steal'),'runnerSpeed')){let n=0;for(let i=0;i<1000;i++){const t=L.trial(group.bundle,'sense:'+i);if(t.initialDecision==='STEAL_2B')n++;}rates.push(n);}assert(rates[0]>rates[1]&&rates[1]>=rates[2]);console.log('speed sensitivity /1000',rates);
const bulkStart=performance.now();for(let i=0;i<10000;i++){const t=L.trial(b,'bulk:'+i);assert(!t.anomalies.some(a=>a.severity==='CRITICAL'));}console.log('10000 half-inning trials ms',Math.round(performance.now()-bulkStart));
for(const id of ['pinchHit','pinchRun','relief']){const t=L.trial(L.setup(L.config(id)),0);assert(t.operations.some(x=>x.decision===({pinchHit:'PINCH_HIT',pinchRun:'PINCH_RUN',relief:'RELIEF'}[id])));}
console.log('PASS 006: 30 full games, 12 mode games, '+eventCount+' events; 900 scenario trials; deterministic replay; 3000 sensitivity + 10000 bulk trials; DB/team copies unchanged');
