(()=>{'use strict';const L=SL_LAB,E=SL_ENGINE,P=SL_LAB_PRESENTATION,$=id=>document.getElementById(id);let scenario=L.config(),report=null,before=null,worker=null,viewer=null,replay=null,replayScope=null,replayStartPA=0,replayDone=false,replayTrial=null,replayReport=null,replayGroupIndex=null,view=null,renderedReport=null,candidateScope=null,dbPlayers=[];
try{dbPlayers=E.readDB(localStorage).players;}catch{}
const roles={batter:'現打者',next:'次打者',pitcher:'投手',catcher:'捕手',runner:'共通走者',runner1:'一塁走者',runner2:'二塁走者',runner3:'三塁走者',bench:'攻撃控え',relief:'救援 / 抑え',defensiveBench:'守備控え'};
function node(tag,text,parent){const n=document.createElement(tag);if(text!==null)n.textContent=text;if(parent)parent.append(n);return n;}
function options(el,items,value){el.replaceChildren();for(const [v,t] of items){const o=node('option',t,el);o.value=v;}if(!items.some(([v])=>String(v)===String(value))){const o=node('option','CUSTOM / '+value,el);o.value=value;}el.value=String(value);}
function status(s){$('status').textContent=s;}
function gradeRaw(role){const r=role.startsWith('runner')||role==='bench'&&scenario.id==='pinchRun'?'RUNNER':role==='pitcher'||role==='relief'?'PITCHER':role==='catcher'?'CATCHER':'BATTER';return L.preset(r,role.startsWith('runner')?scenario.runnerGrade:role==='batter'?scenario.batterGrade:role==='next'?scenario.nextGrade:role==='catcher'?scenario.catcherGrade:role==='pitcher'?scenario.pitcherGrade:role==='relief'?'C':scenario.benchGrade,role.startsWith('runner')?scenario.runnerTrait:role==='batter'?scenario.buntTrait:'none');}
function getPlayer(){const role=$('role').value;return scenario.players[role]||(role.startsWith('runner')?scenario.players.runner:null)||gradeRaw(role);}
function editPlayer(){const role=$('role').value;scenario.players[role]??=JSON.parse(JSON.stringify(getPlayer()));return scenario.players[role];}
function presetNumber(root,key,spec){
 const wrapper=node('div',null,root),label=node('label',spec.label,wrapper),select=node('select',null,label);select.dataset.setting=key;
 options(select,[...spec.presets.map(n=>[n,spec.labels?.[n]||n+(spec.unit||'')]),['custom','Custom / カスタム']],spec.presets.includes(scenario[key])?scenario[key]:'custom');
 const customLabel=node('label',spec.label+' Custom',wrapper),input=node('input',null,customLabel);input.id=key+'Custom';input.type='number';input.inputMode='numeric';input.min=spec.min;input.max=spec.max;input.step='1';input.value=Number.isFinite(scenario[key])?scenario[key]:'';
 const error=node('span',null,wrapper);error.className='number-error';error.setAttribute('aria-live','polite');
 function sync(){customLabel.hidden=select.value!=='custom';try{scenario[key]=L.numericValue(select.value==='custom'?(input.value===''?NaN:Number(input.value)):Number(select.value),spec);input.setCustomValidity('');error.textContent='';}catch(e){scenario[key]=NaN;input.setCustomValidity(e.message);error.textContent=e.message;}updatePreview();}
 select.onchange=sync;input.oninput=sync;customLabel.hidden=select.value!=='custom';
}
function settings(){const root=$('settings');root.replaceChildren();function select(label,key,items){const l=node('label',label,root),s=node('select',null,l);s.dataset.setting=key;options(s,items,scenario[key]);s.onchange=()=>{scenario[key]=typeof scenario[key]==='number'?Number(s.value):s.value;};}
 select('回','inning',Array.from({length:9},(_,i)=>[i+1,`${i+1}回`]));select('表 / 裏','half',[['top','表'],['bottom','裏']]);select('アウト','outs',[[0,'0死'],[1,'1死'],[2,'2死']]);select('打順','order',Array.from({length:9},(_,i)=>[i+1,`${i+1}番`]));presetNumber(root,'fatigue',L.numericInputs.fatigue);select('観測範囲','horizon',[['half','半イニング終了まで'],['pa','1打席終了まで'],['game','試合終了まで']]);
 for(let i=0;i<2;i++){const l=node('label',i?'HOME score':'AWAY score',root),n=node('input',null,l);n.type='number';n.min=0;n.value=scenario.score[i];n.onchange=()=>scenario.score[i]=Number(n.value);}
 const l=node('label','走者配置',root),sel=node('select',null,l);options(sel,Array.from({length:8},(_,m)=>[m,m?['一','二','三'].filter((_,i)=>m&(1<<i)).join('・')+'塁':'走者なし']),scenario.bases.reduce((m,b,i)=>m+(b?(1<<i):0),0));sel.onchange=()=>scenario.bases=[0,1,2].map(i=>!!(Number(sel.value)&(1<<i)));
 const pitchLabel=node('label','投球数比較 Custom（例：90 / 100 / 110、空欄は0 / 80 / 140）',root),pitchInput=node('input',null,pitchLabel);pitchInput.id='comparisonPitchCounts';pitchInput.value=Array.isArray(scenario.comparisonPitchCounts)?scenario.comparisonPitchCounts.join(' / '):scenario.comparisonPitchCounts||'';pitchInput.oninput=()=>{if(pitchInput.value.trim())scenario.comparisonPitchCounts=pitchInput.value.trim();else delete scenario.comparisonPitchCounts;updatePreview();};
 const lr=node('label','救援候補',root),sr=node('select',null,lr);options(sr,[[0,'なし'],[1,'あり']],scenario.relief?1:0);sr.onchange=()=>scenario.relief=sr.value==='1';}
function players(){const p=getPlayer();const root=$('abilities');root.replaceChildren();for(const [k,title]of Object.entries({meet:'ミート',power:'パワー',speed:'走力',arm:'肩',fielding:'守備',catching:'捕球',velocity:'球速',control:'制球',stamina:'スタミナ'})){const group=['velocity','control','stamina'].includes(k)?'pitching':'batting',range=E.CONFIG.ranges[k]||[1,20],value=p[group]?.[k],l=node('label',`${title} / 現在 ${value??'未設定'}`,root),s=node('select',null,l);options(s,[['keep','現在値'],['S','HIGH / S'],['C','MID / C'],['G','LOW / G']],Object.keys(L.gradeValues[k]).find(g=>L.gradeValue(k,g)===value)||'keep');s.onchange=()=>{if(s.value==='keep')return;const raw=editPlayer();raw[group]??={};raw[group][k]=L.gradeValue(k,s.value);players();};}
 const trait=(p.specials||[]).find(x=>['盗塁○','盗塁×','バント○','バント×'].includes(x));$('trait').value=trait||'none';}
options($('role'),Object.entries(roles),'runner');options($('playerSource'),[['preset','TEST PRESET'],...dbPlayers.map((p,i)=>[i,`${p.name||'名称未設定'} / ${p.team||'—'}`])],'preset');
$('role').onchange=()=>{const raw=scenario.players[$('role').value],i=raw?dbPlayers.findIndex(p=>p.id!=null&&p.id===raw.id):-1;$('playerSource').value=i>=0?String(i):'preset';players();};$('playerSource').onchange=()=>{const role=$('role').value;scenario.players[role]=$('playerSource').value==='preset'?gradeRaw(role):JSON.parse(JSON.stringify(dbPlayers[Number($('playerSource').value)]));players();};
$('trait').onchange=()=>{const p=editPlayer();p.specials=(p.specials||[]).filter(x=>!['盗塁○','盗塁×','バント○','バント×'].includes(x));if($('trait').value!=='none')p.specials.push($('trait').value);};
options($('axis'),[['none','比較なし'],...Object.entries(L.axes).map(([k,a])=>[k,a.label])],'runnerSpeed');

options($('axisB'),[['','比較軸Bを選択'],...Object.entries(L.axes).map(([k,a])=>[k,a.label])],'nextMeet');
function selectedComparison(){return {axis:$('comparisonMode').value==='single'?'none':$('axis').value,axisB:$('comparisonMode').value==='matrix'?$('axisB').value:null};}
function setComparison(axis,axisB=null){$('axis').value=axis;$('axisB').value=axisB||'nextMeet';$('comparisonMode').value=axisB?'matrix':axis==='none'?'single':'axis';}
$('comparisonMode').onchange=()=>{if($('comparisonMode').value==='single')$('axis').value='none';else if($('axis').value==='none')$('axis').value=P.defaultAxes[scenario.id]!=='none'?P.defaultAxes[scenario.id]||'batterMeet':'batterMeet';if($('comparisonMode').value==='matrix'&&$('axisB').value===$('axis').value)$('axisB').value=$('axis').value==='nextMeet'?'batterMeet':'nextMeet';};
$('axis').onchange=()=>{if($('axis').value==='none')$('comparisonMode').value='single';else if($('comparisonMode').value==='single')$('comparisonMode').value='axis';};
for(const [id,role]of [['fixedBatterMeet','batter'],['fixedNextMeet','next']])$(id).onchange=()=>{const raw=JSON.parse(JSON.stringify(scenario.players[role]||gradeRaw(role)));raw.batting??={};raw.batting.meet=L.gradeValue('meet',$(id).value);scenario.players[role]=raw;players();};
function fixedControls(active){
 $('fixedMeetControls').hidden=scenario.id!=='walk'&&!['batterMeet','nextMeet','batterPower'].some(x=>active.has(x));
 for(const [id,role,axis,name]of [['fixedBatterMeet','batter','batterMeet','打者ミート'],['fixedNextMeet','next','nextMeet','次打者ミート']]){
  const select=$(id),vary=active.has(axis),raw=scenario.players[role]||gradeRaw(role),value=raw.batting?.meet,grade=Object.keys(L.gradeValues.meet).find(g=>L.gradeValue('meet',g)===value)||String(value);
  options(select,vary?[['vary','S / C / G（比較）']]:[['S','S'],['C','C'],['G','G']],vary?'vary':grade);select.disabled=vary;select.parentElement.firstChild.textContent=name+(vary?'（比較軸で変更）':'（固定値）');
 }
}
function countValue(){return Number($('count').value==='custom'?$('customCount').value:$('count').value);}
function updatePreview(){
 const {axis,axisB}=selectedComparison(),n=countValue(),active=new Set([axis,axisB].filter(Boolean));let spec,preview=[],problem='';
 $('axisAField').hidden=false;$('axisBField').hidden=$('comparisonMode').value!=='matrix';
 for(const option of $('axisB').options)option.disabled=option.value===axis;
 try{if($('comparisonMode').value==='matrix'&&!axisB)throw Error('比較軸Bを選択してください');spec=L.executionSize(axis,axisB,n,scenario);preview=L.compare(scenario,axis,axisB);}catch(e){problem=e.message;}
 const groups=spec?.conditionCount||0;fixedControls(active);$('configurationError').textContent=problem;$('run').disabled=!!worker||!!problem;
 $('comparisonInfo').textContent=spec?spec.axes.map(a=>a.label+'：'+a.values.length+'条件').join(' × ')+(spec.totalTrials>=10000?' ｜ 合計'+spec.totalTrials.toLocaleString()+'試行。処理時間と保存サイズが増えます。':''):'';
 options($('quickPreset'),Object.entries(L.scenarios).map(([id,s])=>[id,s.label]),scenario.id);$('testTitle').textContent=P.title(scenario);$('situation').textContent=P.situation(scenario);
 $('changeTitle').textContent=spec?.axes.length?spec.axes.map(a=>P.axisNames[a.id]||a.id).join(' × '):'単一条件';$('conditions').replaceChildren();$('conditions').classList.toggle('matrix-conditions',!!axisB);
 preview.forEach((g,i)=>{const c=node('div',null,$('conditions'));c.className='condition';c.dataset.conditionId=P.condition(g,i).id;node('small',P.condition(g,i).id+' 条件',c);node('strong',P.condition(g,i).label,c);const input=L.effectiveInputs(g.bundle);if(active.has('batterMeet')||active.has('nextMeet')||scenario.id==='walk')node('small','打者 '+input.batterMeet+' / 次打者 '+input.nextMeet,c);});
 const root=$('fixedConditions');root.replaceChildren();node('p','固定条件',root);const c=scenario.players.catcher||L.preset('CATCHER',scenario.catcherGrade),key='runner'+(scenario.bases.findIndex(Boolean)+1),r=scenario.players[key]||scenario.players.runner||L.preset('RUNNER',scenario.runnerGrade,scenario.runnerTrait);
 const rank=(stat,value)=>Object.keys(L.gradeValues[stat]).find(k=>L.gradeValue(stat,k)===value)||String(value??'未設定');
 const lines=[],id=scenario.id,batter=scenario.players.batter||L.preset('BATTER',scenario.batterGrade,scenario.buntTrait),pitcher=scenario.players.pitcher||L.preset('PITCHER',scenario.pitcherGrade);
 if(['steal','hitRun'].includes(id)){if(!active.has('catcherArm'))lines.push('捕手肩 '+rank('arm',c.batting?.arm));if(!active.has('runnerTrait'))lines.push('盗塁特殊能力 '+((r.specials||[]).filter(x=>['盗塁○','盗塁×'].includes(x)).join('・')||'なし'));}
 if(['steal','hitRun','pinchRun'].includes(id)&&!active.has('runnerSpeed')&&scenario.bases.some(Boolean))lines.push('走者走力 '+rank('speed',r.batting?.speed));
 if(!active.has('batterMeet'))lines.push('打者ミート '+rank('meet',batter.batting?.meet));
 if(['bunt','squeeze'].includes(id)&&!active.has('buntTrait'))lines.push('バント特殊能力 '+((batter.specials||[]).filter(x=>['バント○','バント×'].includes(x)).join('・')||'なし'));
 if(!active.has('nextMeet')){const next=scenario.players.next||L.preset('BATTER',scenario.nextGrade);lines.push('次打者ミート '+rank('meet',next.batting?.meet));}
 if(['pinchHit','pinchRun'].includes(id)){const stat=id==='pinchRun'?'speed':'meet';if(!active.has(id==='pinchRun'?'benchSpeed':'benchMeet')){const bench=scenario.players.bench||L.preset(id==='pinchRun'?'RUNNER':'BATTER',scenario.benchGrade);lines.push('控え'+(stat==='speed'?'走力 ':'ミート ')+rank(stat,bench.batting?.[stat]));}}
 if(id==='relief'){if(!active.has('pitcherControl'))lines.push('投手制球 '+rank('control',pitcher.pitching?.control));lines.push('救援候補 '+(scenario.relief||scenario.players.relief?'あり':'なし'));}
 if(!active.has('fatigue'))lines.push('投手 '+(scenario.fatigue===0?'fresh（0球）':Number.isFinite(scenario.fatigue)?scenario.fatigue+'球':'入力を確認'));
 node('p',lines.join(' ｜ '),root);node('p',groups>1?'その他の能力・選手・状況は同条件':'この設定のseedを変えて試行します',root);node('p','能力の個別設定はプリセット基準値より優先されます。比較対象の能力だけを条件ごとに置き換えます。',root);node('p','観測：'+({half:'半イニング終了まで',pa:'1打席終了まで',game:'試合終了まで'}[scenario.horizon]||scenario.horizon),root);

 $('runSummary').replaceChildren();for(const [title,value]of [['各条件',Number.isFinite(n)?n.toLocaleString()+'回':'—'],['比較条件',groups+'条件'],['合計',spec?spec.totalTrials.toLocaleString()+'試行':'—']]){const d=node('div',title,$('runSummary'));node('strong',value,d);}$('customCountLabel').hidden=$('count').value!=='custom';
}
function choosePreset(id){scenario=L.config(id);$('playerSource').value='preset';setComparison(P.defaultAxes[id]||'none');settings();players();$('advanced').open=false;for(const b of $('presets').children)b.setAttribute('aria-pressed',String(b.dataset.preset===id));updatePreview();}
for(const [id,s]of Object.entries(L.scenarios)){const b=node('button',s.label,$('presets'));b.dataset.preset=id;b.onclick=()=>choosePreset(id);}
$('quickPreset').onchange=()=>choosePreset($('quickPreset').value);
$('setupSection').addEventListener('change',()=>updatePreview());
$('readCustom').onclick=()=>$('custom').value=JSON.stringify(scenario,null,2);
$('applyCustom').onclick=()=>{try{const s=JSON.parse($('custom').value);L.setup(s);scenario=s;settings();players();updatePreview();status('CUSTOMを適用しました。実行前に条件を確認してください。');}catch(e){status(e.message);}};
function launch(input,axis,count,seed,axisB=null){try{const size=L.executionSize(axis,axisB,count,input);L.compare(input,axis,axisB);if(!Number.isInteger(count)||count<1||count>10000)throw Error('試行数は1〜10000');if(location.protocol==='file:')throw Error('Workerを利用するためHTTP(S)で開いてください。');worker?.terminate();worker=new Worker('engine-lab-worker.js');$('run').disabled=true;$('cancel').disabled=false;$('cancel').hidden=false;$('progress').hidden=false;$('progress').value=0;const total=size.totalTrials;status(`ENGINE TEST 実行中\n0 / ${total.toLocaleString()} ｜ 0%`);worker.onmessage=({data})=>{if(data.type==='progress'){status(`ENGINE TEST 実行中\n${data.completed.toLocaleString()} / ${data.total.toLocaleString()} ｜ ${Math.floor(data.completed/data.total*100)}%`);$('progress').value=data.completed/data.total;}if(data.type==='complete'){report=data.report;report.savedSeeds=[];candidateScope=null;renderReport();status(`${total.toLocaleString()}試行 完了 ｜ ${(report.elapsedMs/1000).toFixed(2)}秒`);$('progress').value=1;stop();$('results').scrollIntoView({behavior:'smooth'});}if(data.type==='error'){status(data.message);stop();}};worker.onerror=e=>{status(e.message||'Workerの読み込みに失敗しました');stop();};worker.postMessage({scenario:input,axis,axisB,count,seed});}catch(e){status(e.message);}}
function stop(){worker?.terminate();worker=null;$('cancel').disabled=true;$('cancel').hidden=true;updatePreview();}
$('run').onclick=()=>{const {axis,axisB}=selectedComparison();launch(scenario,axis,countValue(),$('seed').value,axisB);};$('cancel').onclick=()=>{stop();status('中止しました。未完了データは保存されていません。');};
const percent=(n,d)=>d?`${(100*n/d).toFixed(1)}%`:'—';
function metricTable(root,metrics,groups,showCode=false,offset=0){root.replaceChildren();if(groups.length>3){for(let i=0;i<groups.length;i+=3){const part=node('div',null,root);node('h4','条件 '+P.condition(groups[i],i).id+'〜'+P.condition(groups[Math.min(i+2,groups.length-1)],Math.min(i+2,groups.length-1)).id,part);const table=node('div',null,part);metricTable(table,metrics.map(m=>({...m,values:m.values.slice(i,i+3)})),groups.slice(i,i+3),showCode,i);}return;}const t=node('table',null,root);t.className='metrics-table';const cols=node('colgroup',null,t);for(let i=0;i<=groups.length;i++)node('col',null,cols);const head=node('tr',null,node('thead',null,t));node('th','指標',head).scope='col';groups.forEach((g,i)=>{const c=P.condition(g,i+offset),th=node('th',c.label,head);th.scope='col';node('small',c.id+' 条件',th);});const body=node('tbody',null,t);for(const m of metrics){const row=node('tr',null,body),th=node('th',m.label,row);th.scope='row';th.title=m.basis;if(showCode)node('code',m.id,th);for(const value of m.values){const td=node('td',percent(value.numerator,value.denominator),row);if(value.occurrences!=null)node('small',value.occurrences+'回 / '+value.numerator+'試行',td);td.title=`${value.numerator} / ${value.denominator} · ${m.basis}`;}}}
function renderReport(){const r=report;if(renderedReport!==r){$('allMetrics').open=false;$('trialDetails').open=false;candidateScope=null;renderedReport=r;}view=P.analysis(r,before);updateSolMeta();$('results').hidden=false;$('timing').textContent=`${view.totalTrialCount.toLocaleString()}試行 完了 ｜ ${(r.elapsedMs/1000).toFixed(2)}秒`;$('resultContext').textContent=`${view.testName} · ${view.comparison.label}\n${P.situation(r.groups[0].bundle.scenario)}`;$('resultMeta').textContent=r.version+' · '+r.date;$('resultSetup').textContent=JSON.stringify({scenario:r.groups[0].bundle.scenario,comparisonAxis:r.axis,comparisonAxisB:r.axisB,comparison:view.comparison,changedPaths:view.comparison.fixedConditions.changedPaths,seedPrefix:r.seedPrefix},null,2);metricTable($('primaryMetrics'),view.primaryMetrics,r.groups);$('metricNote').textContent=view.primaryMetrics.map(m=>m.basis).filter((v,i,a)=>a.indexOf(v)===i).join('。')+'。— は対象実行なし。';metricTable($('summary'),view.allMetrics.rates,r.groups,true);$('rawMetrics').textContent=JSON.stringify(view.allMetrics.rawByCondition,null,2);
 const d=$('diagnosis');d.replaceChildren();d.className='diagnosis '+(view.labDiagnosis.status==='candidate'?'critical':view.labDiagnosis.status);node('h3','LAB診断 · '+view.labDiagnosis.label,d);for(const f of view.labDiagnosis.facts)node('p',f,d);node('p','機械的な検査結果です。失敗・盗塁死・敗戦だけでは異常扱いしません。',d).className='note';
 const next=$('nextTest');next.replaceChildren();node('h3','次の推奨テスト',next);node('p',view.recommendedNextTest.label,next);node('p','条件を準備するだけで、自動実行はしません。',next).className='note';node('button','この条件で次のテストを作る',next).onclick=prepareNext;
 $('shareFallback').hidden=true;$('shareStatus').textContent='';$('copyFallback').hidden=true;renderCandidates();renderTrials();renderBeforeAfter();}
function prepare(config,axis,count,seed,axisB=null){scenario=JSON.parse(JSON.stringify(config));setComparison(axis,axisB);options($('count'),[[1,'1回'],[100,'100回'],[1000,'1,000回'],[10000,'10,000回'],['custom','CUSTOM']],[1,100,1000,10000].includes(count)?count:'custom');$('customCount').value=count;$('seed').value=seed;settings();players();updatePreview();$('advanced').open=false;$('setupSection').scrollIntoView({behavior:'smooth'});status('次の条件を準備しました。確認後に実行してください。');}
function prepareNext(){if(!view)return;const n=view.recommendedNextTest;prepare(n.scenario,n.axis,n.trialCountPerCondition,report.seedPrefix,n.axisB);}
$('nextAction').onclick=prepareNext;$('reviewAction').onclick=()=>{$('flags').scrollIntoView({behavior:'smooth'});$('flags').focus({preventScroll:true});};
function showSeeds(flag){candidateScope=flag;$('trialDetails').open=true;$('filter').value='all';$('search').value='';renderTrials();$('trialDetails').scrollIntoView({behavior:'smooth'});}
function renderCandidates(){const root=$('flags');root.replaceChildren();node('h3','要確認候補',root);const flags=view.anomalySummary.candidates;node('p',`CRITICAL ${view.anomalySummary.criticalCount}件 ｜ REVIEW ${view.anomalySummary.reviewCount}件`,root).className='note';if(!flags.length){node('p','現在、機械検査による要確認候補はありません。保存したseedや任意のseedは下の一覧から確認できます。',root).className='note';return;}
 const buckets=new Map();for(const f of flags){const key=f.rule+'|'+f.groupIndex;if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(f);}for(const list of [...buckets.values()].slice(0,30)){const f=list[0],card=node('article',null,root);card.className='candidate';node('span',f.severity==='CRITICAL'?'構造の確認':'要確認',card).className='badge '+f.severity;node('h4',f.heading+(list.length>1?`（${list.length}件）`:''),card);node('p',f.reason,card);if(f.detail)node('p',f.detail,card).className='note';node('code',f.rule,card);const group=Number.isInteger(f.groupIndex)?report.groups[f.groupIndex]:null,t=group?.trials.find(t=>t.seed===f.seed);node('p',t?`${group.label} · ${t.seed}`:'条件全体の候補です。特定seedの失敗を異常と判定したものではありません。',card).className='note';const actions=node('div',null,card);actions.className='toolbar';node('button',t?'対象seedを見る':'この条件のseedを見る',actions).onclick=()=>showSeeds(f);if(t)node('button','2Dで再生',actions).onclick=()=>play(group,t);}}
function renderTrials(){const root=$('trials');root.replaceChildren();if(!report)return;if(candidateScope){node('p','絞り込み：'+candidateScope.heading,root).className='note';node('button','絞り込みを解除',root).onclick=()=>{candidateScope=null;renderTrials();};}let shown=0;for(let gi=0;gi<report.groups.length;gi++){const g=report.groups[gi];for(const t of g.trials){if(candidateScope){const f=candidateScope;if(f.groupIndices&&!f.groupIndices.includes(gi))continue;if(f.groupIndex!=null&&!f.groupIndices&&f.groupIndex!==gi)continue;if(f.rule!=='ZERO_STEAL_CG'&&f.seed&&!(t.anomalies.some(a=>a.rule===f.rule)||t.seed===f.seed))continue;}const key=gi+'|'+t.seed,saved=report.savedSeeds?.includes(key);if($('filter').value==='flagged'&&!t.anomalies.length||$('filter').value==='saved'&&!saved||!t.seed.includes($('search').value))continue;if(shown++>=50)break;const row=node('div',null,root);row.className='trial';node('span',t.classification==='NORMAL'?'候補なし':t.classification==='CRITICAL'?'構造の確認':'要確認',row).className='badge '+t.classification;node('p',`${g.label} · ${t.seed}`,row);node('p',`初期判断：${P.label(t.initialDecision)} ｜ 観測全体H&R ${t.decision.HIT_AND_RUN||0}回 ｜ 終了スコア ${t.outcome.finalScore.join('–')}`,row);const actions=node('div',null,row);actions.className='toolbar';const save=node('button',saved?'★ 保存済み':'☆ seed保存',actions);save.onclick=async()=>{report.savedSeeds??=[];if(!report.savedSeeds.includes(key))report.savedSeeds.push(key);try{const savedName=await putReport($('saveName').value||report.seedPrefix||'saved-seeds',report);renderTrials();updateSolMeta();history();$('shareStatus').textContent='seedと再現条件を保存しました：'+savedName;}catch(e){$('shareStatus').textContent='保存失敗: '+e.message;}};node('button','2D再生',actions).onclick=()=>play(g,t);node('button','理由',actions).onclick=()=>{$('replaySection').hidden=false;$('trace').textContent=JSON.stringify(t,null,2);$('trace').parentElement.open=true;$('replaySection').scrollIntoView({behavior:'smooth'});};}}if(!shown)node('p','該当するseedはありません。',root).className='note';}
$('filter').onchange=()=>{candidateScope=null;renderTrials();};$('search').oninput=()=>{candidateScope=null;renderTrials();};
function verifyReplay(e){const t=replayTrial,s=replay.state,match=JSON.stringify(s.score)===JSON.stringify(t.outcome.finalScore)&&s.finished===t.outcome.gameFinished&&s.finishReason===t.outcome.finishReason;replayReport.uiChecks??=[];const key=replayGroupIndex+'|'+t.seed;replayReport.uiChecks=replayReport.uiChecks.filter(x=>x.key!==key);replayReport.uiChecks.push({key,seed:t.seed,groupIndex:replayGroupIndex,status:match?'matched':'mismatch',checkedFields:['finalScore','gameFinished','finishReason'],expected:t.outcome.finalScore,actual:[...s.score],checkedAt:new Date().toISOString()});$('replayLabel').textContent=match?'seed '+t.seed+'：終了スコア・試合終了情報が保存結果と一致しました。':'seed '+t.seed+'：保存結果との不一致を検出しました。';if(report===replayReport){view=P.analysis(report,before);if(!match){renderReport();$('shareStatus').textContent='保存結果とseed再実行が一致しません。要確認候補を確認してください。';}}}
function play(group,t){try{if(group.bundle.config.version!==E.CONFIG.version)throw Error('このENGINEでは別versionのseed再計算はできません。対応versionで開いてください。');replayTrial=t;replayReport=report;replayGroupIndex=report.groups.indexOf(group);replay=L.create(group.bundle,t.seed);viewer?.reset();$('replaySection').hidden=false;$('replayLabel').textContent=`${group.label} / ${t.seed} / 保存時の選手コピーで再生`;replayDone=false;replayScope=group;replayStartPA=replay.state.paCompleted;if(!viewer)viewer=SL_MATCH_VIEWER.create({root:$('matchViewer'),getGame:()=>replayDone?{...replay,state:{...replay.state,finished:true,finishReason:replay.state.finishReason||'scenarioReplayComplete'}}:replay,step:mode=>{if(replayDone)return [];const records=[];do{const e=E.onePitch(replay);if(!e)break;records.push(e);const s=replayScope.bundle.scenario;replayDone=replay.state.finished||(s.horizon==='half'&&(replay.state.inning!==s.inning||replay.state.half!==s.half))||(s.horizon==='pa'&&replay.state.paCompleted!==replayStartPA);if(replayDone)verifyReplay(e);if(mode!=='game')break;}while(!replayDone);return records;},onChange:()=>{}});$('trace').textContent=JSON.stringify(t,null,2);$('matchViewer').querySelector('[data-action="view"]').click();$('replaySection').scrollIntoView({behavior:'smooth'});}catch(e){status(e.message);}}

function openDB(){return new Promise((resolve,reject)=>{const q=indexedDB.open('sl_world_engine_lab_006',1);q.onupgradeneeded=()=>q.result.createObjectStore('reports',{keyPath:'name'});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function storage(mode,action){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('reports',mode),req=action(tx.objectStore('reports'));tx.oncomplete=()=>{db.close();resolve(req.result);};tx.onerror=()=>{db.close();reject(tx.error);};tx.onabort=()=>{db.close();reject(tx.error||Error('保存中断'));};});}
async function putReport(name,data){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('reports','readwrite'),store=tx.objectStore('reports');let suffix=1,savedName=name;function reserve(){const q=store.getKey(savedName);q.onsuccess=()=>{if(q.result!==undefined){savedName=name+' ('+(++suffix)+')';reserve();}else store.add({name:savedName,date:new Date().toISOString(),report:data});};}reserve();tx.oncomplete=()=>{db.close();resolve(savedName);};tx.onerror=()=>{db.close();reject(tx.error);};tx.onabort=()=>{db.close();reject(tx.error||Error('保存中断'));};});}
async function historySummaries(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('reports'),items=[],q=tx.objectStore('reports').openCursor();q.onsuccess=()=>{const cursor=q.result;if(!cursor)return;const item=cursor.value,r=item.report,s=r.groups?.[0]?.bundle?.scenario;items.push({name:item.name,date:item.date,testDate:r.date,axis:r.axis,axisB:r.axisB,count:r.trialCount,title:s?L.scenarios[s.id]?.label||s.label||'CUSTOM':'LABテスト'});cursor.continue();};tx.oncomplete=()=>{db.close();resolve(items);};tx.onerror=()=>{db.close();reject(tx.error);};});}
const loadHistory=name=>storage('readonly',s=>s.get(name));

function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=node('a',null);a.href=url;a.download=name;a.hidden=true;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function exportText(){return JSON.stringify(P.solReport(report,before));}
function updateSolMeta(){if(!report)return;const data=P.solReport(report,before),size=new Blob([JSON.stringify(data)]).size;$('solMeta').textContent='ソル解析用JSON\n'+(size/1024).toFixed(1)+' KB\n異常候補 '+data.anomalySummary.candidateCount+'件\n要確認seed '+data.interestingSeeds.length+'件（代表抽出）';}
function solFilename(){return P.filename(report).replace('.json','_sol.json');}
function downloadSol(){download(exportText(),solFilename(),'application/json');}
$('json').onclick=()=>download(JSON.stringify(P.exportReport(report,before),null,2),P.filename(report).replace('.json','_full.json'),'application/json');$('csv').onclick=()=>download(L.csv(report),P.filename(report).replace(/\.json$/,'.csv'),'text/csv');
$('solJson').onclick=async()=>{if(!report)return;$('shareStatus').textContent='解析用JSONを作成しています…';try{const text=exportText(),file=new File([text],solFilename(),{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});$('shareStatus').textContent='共有シートにJSONを渡しました。';return;}catch(e){if(e.name==='AbortError'){$('shareStatus').textContent='共有をキャンセルしました。';return;}}}download(text,solFilename(),'application/json');$('shareFallback').hidden=false;$('shareStatus').textContent='ファイル共有が利用できないため、JSONのダウンロードを開始しました。コピーも選べます。';}catch(e){$('shareFallback').hidden=false;$('shareStatus').textContent='共有できませんでした。ダウンロードまたはコピーを選んでください。 '+e.message;}};
$('solDownload').onclick=downloadSol;$('solCopy').onclick=async()=>{const text=exportText();try{if(!navigator.clipboard?.writeText)throw Error('clipboard unavailable');await navigator.clipboard.writeText(text);$('shareStatus').textContent='ソル解析用JSONをコピーしました。';}catch{const box=$('copyFallback');box.hidden=false;box.value=text;box.focus();box.select();$('shareStatus').textContent='自動コピーが利用できません。選択されたJSONをコピーしてください。';}};
$('save').onclick=async()=>{try{const savedName=await putReport($('saveName').value.trim()||report.seedPrefix||'engine-lab-'+Date.now(),report);$('shareStatus').textContent='履歴保存完了：'+savedName+'（既存の同名履歴は保持）';$('saveStatus').textContent='保存しました：'+savedName+'（同名の既存履歴は保持）';status('履歴保存完了');history();}catch(e){$('saveStatus').textContent='保存失敗。JSONを書き出して保存してください: '+e.message;}};
async function history(){try{const list=await historySummaries();$('history').replaceChildren();if(!list.length)node('p','保存したテストがここに並びます。', $('history')).className='note';for(const item of list.sort((a,b)=>b.date.localeCompare(a.date))){const row=node('article',null,$('history'));row.className='history-card';const open=node('button',null,row);node('strong',item.name,open);node('small',item.title+' ｜ '+[item.axis,item.axisB].filter(Boolean).map(axis=>P.axisNames[axis]||axis).join(' × '),open);node('small','各'+Number(item.count||0).toLocaleString()+'回 ｜ '+(item.testDate||item.date||'').slice(0,10),open);
 const act=fn=>async()=>{try{await fn((await loadHistory(item.name)).report);}catch(e){$('importStatus').textContent='履歴を開けません：'+e.message;}};
 open.onclick=act(r=>{report=r;candidateScope=null;$('saveName').value=item.name;renderReport();$('results').scrollIntoView({behavior:'smooth'});});const actions=node('div',null,row);actions.className='toolbar';node('button','BEFOREに指定',actions).onclick=act(r=>{before=r;renderBeforeAfter();if(report){view=P.analysis(report,before);updateSolMeta();}status('BEFOREを指定しました。');$('importStatus').textContent=item.name+' をBEFOREに指定しました。';});node('button','同じ条件を準備',actions).onclick=act(r=>{before=r;prepare(r.groups[0].bundle.scenario,r.axis,r.trialCount,r.seedPrefix,r.axisB);});}}catch(e){node('p','履歴が利用できません: '+e.message,$('history'));}}
function renderBeforeAfter(){const root=$('beforeAfter');root.replaceChildren();const data=report?P.beforeAfter(before,report)||report.beforeAfter:null;if(!data)return;node('h3','BEFORE / AFTER',root);node('p',`${data.before.version} → ${data.after.version}`,root).className='note';for(const c of data.conditions){const card=node('div',null,root);card.className='result-card';node('h3',c.condition.id+' / '+c.condition.label,card);node('p',c.sameScenario&&c.samePlayers&&c.sameSeedPrefix&&c.sameCount?'状況・選手・seed・試行数が同条件':'条件差があります。差を確認して比較してください。',card).className='note';const t=node('table',null,card);t.className='metrics-table';const cg=node('colgroup',null,t);[0,1,2].forEach(()=>node('col',null,cg));const tr=node('tr',null,node('thead',null,t));['初回判断','BEFORE','AFTER'].forEach(x=>node('th',x,tr));const body=node('tbody',null,t);for(const k of new Set([...Object.keys(c.before?.initialDecision||{}),...Object.keys(c.after.initialDecision)])){const row=node('tr',null,body);node('th',P.label(k),row).scope='row';node('td',percent(c.before?.initialDecision[k]||0,c.before?.trials||0),row);node('td',percent(c.after.initialDecision[k]||0,c.after.trials),row);}}}
$('import').onchange=async()=>{try{if(!$('import').files[0])return;report=P.importReport(JSON.parse(await $('import').files[0].text()));candidateScope=null;renderReport();$('importStatus').textContent='LAB JSONを読み込みました。元の履歴・選手DBは変更していません。保存する場合は「履歴を保存」を押してください。';$('results').scrollIntoView({behavior:'smooth'});}catch(e){$('importStatus').textContent='読み込めません: '+e.message;}finally{$('import').value='';}};
settings();players();updatePreview();history();
})();
