const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const server=http.createServer((req,res)=>{const f=path.join(__dirname,decodeURIComponent(req.url.split('?')[0]));fs.readFile(f,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const W=Worker;window.Worker=class extends W{constructor(...a){super(...a);this.addEventListener('message',({data})=>{if(data.type==='complete')window.lastReport=data.report;});}};});await page.goto('http://127.0.0.1:'+server.address().port+'/engine-lab.html');
async function run(){await page.evaluate(()=>window.lastReport=null);await page.locator('#run').click();await page.waitForFunction(()=>window.lastReport&&document.querySelector('#run').disabled===false,{},{timeout:180000});console.log('Worker completed');return page.evaluate(()=>({...window.lastReport,groups:window.lastReport.groups.map(g=>({...g,trials:{length:g.trials.length}}))}));}
await page.locator('#quickPreset').selectOption('walk');await page.locator('#axis').selectOption('batterMeet');await page.locator('#fixedNextMeet').selectOption('C');await page.locator('#count').selectOption('1');let r=await run();assert(r.groups.every(g=>g.bundle.scenario.players.next.batting.meet===7));
await page.locator('#axis').selectOption('nextMeet');await page.locator('#fixedBatterMeet').selectOption('C');r=await run();assert(r.groups.every(g=>g.bundle.scenario.players.batter.batting.meet===7));
await page.locator('#axis').selectOption('batterMeet');await page.locator('#comparisonMode').selectOption('matrix');await page.locator('#axisB').selectOption('nextMeet');assert(await page.locator('#axisB option[value=batterMeet]').evaluate(e=>e.disabled));assert.equal(await page.locator('#conditions .condition').count(),9);assert((await page.locator('#conditions').innerText()).includes('S × S'));await page.locator('#count').selectOption('1000');assert((await page.locator('#runSummary').innerText()).includes('9,000試行'));r=await run();assert.equal(r.groups.length,9);assert(r.groups.every(g=>g.trials.length===1000));
const result=await page.evaluate(()=>{const e=SL_LAB_PRESENTATION.exportReport(window.lastReport);const parsed=JSON.parse(JSON.stringify(e));return {total:e.totalTrialCount,conditions:e.comparison.conditions.length,counts:parsed.groups.map(g=>g.trials.length)};});assert.equal(result.total,9000);assert.equal(result.conditions,9);assert(result.counts.every(n=>n===1000));console.log('9000 JSON verified');const exported=await page.evaluate(()=>SL_LAB_PRESENTATION.exportReport({...window.lastReport,trialCount:1,groups:window.lastReport.groups.map(g=>({...g,trials:g.trials.slice(0,1),summary:SL_LAB.summarize(g.trials.slice(0,1))}))}));await page.setViewportSize({width:320,height:800});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-artifacts/lab-matrix-mobile.png',fullPage:false});
await page.locator('#import').setInputFiles({name:'matrix.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page.waitForFunction(()=>document.querySelector('#importStatus').textContent.includes('読み込みました'));
await page.locator('#nextAction').click();assert.equal(await page.locator('#comparisonMode').inputValue(),'matrix');assert.equal(await page.locator('#axisB').inputValue(),'nextMeet');assert.equal(await page.locator('#conditions .condition').count(),9);await page.locator('#setupSection').screenshot({path:'test-artifacts/lab-matrix-setup.png'});await page.locator('#quickPreset').selectOption('relief');await page.locator('#comparisonMode').selectOption('single');await page.locator('#count').selectOption('1');await page.locator('#advanced').evaluate(e=>e.open=true);
for(const n of [85,90,95,100,105]){await page.locator('[data-setting=fatigue]').selectOption('custom');await page.locator('#fatigueCustom').fill(String(n));r=await run();assert.equal(r.groups[0].bundle.scenario.fatigue,n);}
for(const n of [0,80,100,140]){await page.locator('[data-setting=fatigue]').selectOption(String(n));assert(!(await page.locator('#fatigueCustom').isVisible()));}
await page.locator('[data-setting=fatigue]').selectOption('custom');await page.locator('#fatigueCustom').fill('1.5');assert(await page.locator('#run').isDisabled());await page.locator('#fatigueCustom').fill('95');assert(!(await page.locator('#run').isDisabled()));assert.deepEqual(errors,[]);console.log('PASS browser: A/B fixed C, matrix 9 x 1000 real Worker trials, 9000 total, JSON import, 320px, Custom 85/90/95/100/105 execution, presets and validation');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});

