const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js','engine-diagnostic-core.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=SL_ENGINE,F=SL_FIELDING,T=SL_TACTICS,L=SL_LAB,D=SL_DIAGNOSTIC,copy=x=>JSON.parse(JSON.stringify(x));
const outputs={};for(const id of Object.keys(D.scenarios)){outputs[id]=D.conditions({id}).map(c=>D.trial({id},c,'diagnostic-paired'));assert(outputs[id].every(t=>t.finalResult));}
assert.deepEqual(outputs.A.map(x=>x.fielder),['SS','SS','SS']);assert(outputs.A[0].runnerETA<outputs.A[1].runnerETA&&outputs.A[1].runnerETA<outputs.A[2].runnerETA);assert(outputs.A.every(t=>t.ballETA===outputs.A[0].ballETA));assert(outputs.B[1].input.value===17);assert(outputs.B.every(t=>t.runnerETA===outputs.B[0].runnerETA));assert(outputs.B[1].reaction<outputs.B[2].reaction);
assert(outputs.C[0].exitVelocity>outputs.C.at(-1).exitVelocity);assert(outputs.C.every(t=>t.input.meet===outputs.C[0].input.meet&&t.input.pitchQuality===.5));
assert(outputs.D.filter(t=>t.pitchCount===0).every(t=>t.fatigue===0&&t.effectiveVelocity===t.rawVelocity));assert(outputs.D.find(t=>t.stamina===20&&t.pitchCount===140).fatigue>outputs.D.find(t=>t.stamina===195&&t.pitchCount===140).fatigue);
for(const t of outputs.E){assert(t.roleEvaluations.length>1);for(const row of t.roleEvaluations){assert(row.fielders.every(f=>Number.isFinite(f.estimatedArrival)));assert(row.fielders.filter(f=>['PRIMARY FIELDING','SECONDARY CHASE'].includes(f.assignedRole)).length<=2);}}
assert.equal(outputs.E[0].whoFielded,'SS');assert.equal(outputs.E[1].whoFielded,'2B');
const steals=[];for(const speed of ['S','C','G'])for(const arm of ['S','C','G']){const row={speed,arm,traits:[]};for(const trait of ['盗塁○','none','盗塁×']){const s=L.config('steal');Object.assign(s,{runnerGrade:speed,catcherGrade:arm,runnerTrait:trait});const g=L.create(L.setup(s),'steal'),r=g.state.bases[0],p=E.currentPitcher(g);let safe=0,eta=0;for(let i=0;i<5000;i++){const rng=E.createRNG('paired:'+i),x=F.stealExecution(g,r,p,1,{start:rng()*2-1,transfer:rng()*2-1,motion:rng()*2-1});assert(x.pitchArrival<x.releaseTime&&x.releaseTime<x.ballETA&&x.ballETA<x.tagAt);assert(x.accelerationTime>0&&x.runDistance>0);safe+=x.runnerETA<=x.tagAt;eta+=x.runnerETA;}row.traits.push({trait,safeRate:safe/5000,runnerETA:eta/5000});}assert(row.traits[0].runnerETA<row.traits[1].runnerETA&&row.traits[1].runnerETA<row.traits[2].runnerETA);assert(row.traits[0].safeRate>=row.traits[1].safeRate&&row.traits[1].safeRate>=row.traits[2].safeRate);steals.push(row);}console.log('steals',JSON.stringify(steals));
const bunts=[];for(const trait of ['バント○','none','バント×']){const s=L.config('bunt');Object.assign(s,{half:'top',horizon:'pa',buntTrait:trait});const bundle=L.setup(s),a={trait,count:5000,sacrifices:0,contact:0,quality:0,inPlay:0};for(let i=0;i<a.count;i++){const g=L.create(bundle,'bunt:'+i),b=E.currentBatter(g),p=E.currentPitcher(g);for(let j=0;j<100;j++){const ball=T.resolveBunt(g,p,b);if(ball.outcome==='inPlay'){a.inPlay++;a.quality+=ball.buntQuality;}const result=E.applyPitch(g,ball,b,p);if(result.ended){a.sacrifices+=result.result==='sacrificeBunt';break;}}}a.meanQuality=a.quality/a.inPlay;bunts.push(a);}assert(bunts[0].meanQuality>bunts[1].meanQuality&&bunts[1].meanQuality>bunts[2].meanQuality);assert(bunts[0].sacrifices>bunts[1].sacrifices&&bunts[1].sacrifices>bunts[2].sacrifices);console.log('bunts',bunts);
// A real role handoff releases the former primary into a support role.
{const seed=230,g=L.create(L.setup(L.config('alignment')),seed),rng=E.createRNG(seed),v=15+30*rng(),angle=5+65*rng(),hangTime=2*v*Math.sin(angle*Math.PI/180)/9.81,p={physical:{exitVelocity:v,launchAngle:angle,sprayAngle:(rng()-.5)*1.5,type:'FLY',hangTime,horizontalSpeed:v*5*Math.cos(angle*Math.PI/180)*.65,deceleration:62}};for(const f of F.defense(g))f.profile.batting.speed=2+Math.floor(rng()*19);F.geometry(g,p);const primary=row=>row.fielders.find(f=>f.assignedRole==='PRIMARY FIELDING').index,first=primary(p.roleEvaluations[0]),change=p.roleEvaluations.find(row=>primary(row)!==first);assert(change);assert(['CUTOFF','BACKUP','BASE COVER','HOLD','SECONDARY CHASE'].includes(change.fielders[first].assignedRole));F.process.defensePlan(g,p);for(let at=0;at<p.trajectory.fieldTime;at+=.04){const chasers=p.defensivePlan.tracks.filter(t=>t.legs.some(l=>l.start<=at&&l.end>at&&['primary','secondary'].includes(l.role)));assert(chasers.length<=2);}}
// RF to first remains an actual race even with a speed-20 batter.
{const races=[];for(const v of [40,45]){const g=L.create(L.setup(L.config('alignment')),'rf');g.state.bases=[null,null,null];g.rng=()=>.5;g.tacticalRng=()=>.999;const b=E.currentBatter(g);b.effective.speed=20;b.profile.batting.speed=20;F.defense(g)[8].profile.batting.arm=20;const p={outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:v,launchAngle:0,sprayAngle:.6,type:'GROUND',hangTime:0,horizontalSpeed:v*6,deceleration:48,height:0}},result=E.applyPitch(g,p,b,E.currentPitcher(g));assert.equal(p.fielderIndex,8);assert.equal(p.throws[0].toBase,1);assert.equal(result.result,p.throws[0].tagAt<p.throws[0].timing.runnerETA?'groundout':'single');races.push(result.result);}assert.deepEqual(races,['single','groundout']);}
const json=JSON.stringify({outputs,steals,bunts});assert.deepEqual(JSON.parse(json).outputs.A.length,3);fs.writeFileSync('test-artifacts/final-0914-process.json',json);console.log('PASS diagnostics A-E, paired ability process, 135000 steal races, 15000 bunt PAs, JSON round trip');
