const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),cp=require('child_process');
for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js','engine-diagnostic-core.js','custom-match-core.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=SL_ENGINE,F=SL_FIELDING,L=SL_LAB,D=SL_DIAGNOSTIC,R=SL_MATCH_REPLAY;
const game=seed=>E.newGame(['away','home'].map(side=>E.makeTeam('オールC',side,[],E.CONFIG)),seed);
const report={checks:[],diagnostics:[],matches:[],races:[]};
function check(name,fn){fn();report.checks.push(name);console.log('PASS',name);}
check('protected ability, ball generation, steal and DP formulas unchanged',()=>{const old=cp.execFileSync('git',['show','HEAD:engine006.js'],{encoding:'utf8'}),fresh=fs.readFileSync('engine006.js','utf8');assert.equal(fresh.slice(fresh.indexOf('const CONFIG'),fresh.indexOf('const STORAGE_KEY')),old.slice(old.indexOf('const CONFIG'),old.indexOf('const STORAGE_KEY')));for(const [file,from,to] of [['engine-fielding.js',' function generate(',' function ballAt('],['engine-fielding.js',' function stealExecution(',' // Legal single-runner'],['engine-tactics.js','   if(d.toBase===2','\n  }\n  // Removed']]){const before=cp.execFileSync('git',['show','HEAD:'+file],{encoding:'utf8'}),after=fs.readFileSync(file,'utf8');assert.equal(after.slice(after.indexOf(from),after.indexOf(to,after.indexOf(from))),before.slice(before.indexOf(from),before.indexOf(to,before.indexOf(from))));}});
check('relevant base tasks are unique; catcher preserves home',()=>{const g=game('roles'),f=F.defense(g),at=SL_TACTICS.alignment(g).positions;for(let primary=0;primary<9;primary++)for(let secondary=0;secondary<9;secondary++){if(primary===secondary)continue;const a=F.process.redistribute(g,at,f,primary,secondary,[530,210],[],0,{airborne:true});const covered=a.filter(x=>x.base).map(x=>x.base);assert.equal(covered.length,new Set(covered).size);assert(!covered.includes(2)&&!covered.includes(3));if(primary!==1&&secondary!==1)assert.equal(a[1].base,4);assert.equal(a[primary].role,'PRIMARY FIELDING');assert.equal(a[secondary].role,'SECONDARY CHASE');}});
check('LAB-E role reasons and base necessity diagnostics',()=>{for(const c of D.conditions({id:'E'})){const t=D.trial({id:'E'},c,'0915');for(const row of t.roleEvaluations){assert(row.baseEvaluations);assert.equal(row.fielders[1].base,4);assert.equal(row.fielders.filter(x=>x.assignedRole==='PRIMARY FIELDING').length,1);}report.diagnostics.push({direction:c.value,fielder:t.whoFielded,result:t.finalResult,evaluations:t.roleEvaluations.length});}});
check('same-team independent players; S-G official ranges and CUSTOM representatives',()=>{for(const rank of E.DIAGNOSTIC_LETTERS){const teams=['away','home'].map(side=>E.makeTeam('オール'+rank,side,[],E.CONFIG));assert.equal(teams[0].lineup.length,9);assert(teams[0].bench.length>=6);assert(teams.every(t=>[...t.lineup,...t.bench].every(p=>p.specials.length===0)));assert.notEqual(teams[0].pitcher.key,teams[1].pitcher.key);const preset=SL_CUSTOM_MATCH.preset(rank);assert.equal(teams[0].lineup[0].effective.power,preset.power);assert.equal(teams[0].pitcher.effective.velocity,preset.velocity);}});
check('G20 diagnostic rank',()=>assert.equal(D.conditions({id:'C',values:[20]})[0].rank,'G'));
check('liner intercept seeks catch point before landing',()=>{const g=game('liner'),f=F.defense(g)[3],current=SL_TACTICS.alignment(g).positions[3],p={physical:{exitVelocity:50,launchAngle:8,sprayAngle:.4,type:'LINER',hangTime:2*50*Math.sin(8*Math.PI/180)/9.81,horizontalSpeed:50*5*Math.cos(8*Math.PI/180)*.86,deceleration:62}};const x=F.process.interceptEstimate(p,f,3,current,.04);assert(x.airborne);assert(x.time<p.physical.hangTime);F.geometry(g,p);assert.equal(p.fielderIndex,3);const leg=p.pursuit.tracks[3][0];assert(p.pursuit.tracks[3].reduce((d,l)=>d+Math.hypot(l.to[0]-l.from[0],l.to[1]-l.from[1]),0)<=Math.hypot(p.fieldingPoint[0]-current[0],p.fieldingPoint[1]-current[1])+.01,'liner route must take the direct catch path');assert(Math.hypot(x.point[0]-current[0],x.point[1]-current[1])<Math.hypot(F.process.ballAt(p,2.4).point[0]-current[0],F.process.ballAt(p,2.4).point[1]-current[1]));});
check('RF-first retains safe/out races and full process timestamps',()=>{for(const v of [40,45]){const g=L.create(L.setup(L.config('alignment')),'rf');g.state.bases=[null,null,null];g.rng=()=>.5;g.tacticalRng=()=>.999;const b=E.currentBatter(g);b.effective.speed=20;b.profile.batting.speed=20;F.defense(g)[8].profile.batting.arm=20;const p={outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:v,launchAngle:0,sprayAngle:.6,type:'GROUND',hangTime:0,horizontalSpeed:v*6,deceleration:48,height:0}},result=E.applyPitch(g,p,b,E.currentPitcher(g));assert.equal(p.fielderIndex,8);assert(p.rfFirstRace);assert(p.rfFirstRace.pickupComplete<=p.rfFirstRace.releaseTime);assert.equal(result.result,p.rfFirstRace.raceMargin>0?'groundout':'single');report.races.push({v,...p.rfFirstRace,result:result.result});}assert.deepEqual(report.races.map(r=>r.result),['single','groundout']);});
check('physical DP preserves two transfers and display handles catch DP',()=>{const g=game('dp');g.state.bases[0]=g.teams[0].lineup[3];g.rng=()=>.5;g.tacticalRng=()=>.999;const p={outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:35,launchAngle:0,sprayAngle:-.35,type:'GROUND',hangTime:0,horizontalSpeed:210,deceleration:48,height:0}};assert.equal(E.applyPitch(g,p,E.currentBatter(g),E.currentPitcher(g)).result,'doublePlay');assert.deepEqual(p.throws.map(t=>t.toBase),[2,1]);assert.equal(g.state.outs,2);assert.equal(R.bannerLabel({result:'flyout',doublePlay:true}),'DOUBLE PLAY');assert(R.resultLabel({result:'flyout',doublePlay:true}).includes('併殺'));});
check('FC classifier uses preceding runner attempt and first-base opportunity, including two outs',()=>{const b={key:'b'},p={interception:{airborne:false},throws:[{runnerKey:'r',kind:'force'}],firstBaseOpportunity:true};assert.equal(F.process.classify(p,[],b),'fieldersChoice');p.firstBaseOpportunity=false;assert.equal(F.process.classify(p,[],b),'single');});
check('fly runner intent has minimum state duration; physical tracks remain continuous',()=>{for(let i=0;i<20;i++){const g=game('jitter'+i);g.state.bases[1]=g.teams[0].lineup[2];const p=F.process.generate(g,E.currentBatter(g),{score:.6,grade:'normal'});p.outcome='inPlay';E.applyPitch(g,p,E.currentBatter(g),E.currentPitcher(g));for(const r of p.runnerDecisions||[]){const reads=r.decisions.filter(d=>['GO_ON_CONTACT','TWO_OUT_RUN','TAG_UP_PREP','STAY','READ_HOLD'].includes(d.decision));for(let n=1;n<reads.length;n++)assert(reads[n].at-reads[n-1].at>=.359);}for(const track of p.defensivePlan.tracks){for(let n=1;n<track.legs.length;n++){const a=track.legs[n-1],b=track.legs[n];assert(b.start>=a.end-.001);assert(Math.hypot(a.to[0]-b.from[0],a.to[1]-b.from[1])<.01);}}}});
check('forced sacrifice bunt reaches physical defense and vacated bases',()=>{let inPlay=0,sacrifices=0;for(let i=0;i<40;i++){const config=L.config('bunt');config.half='top';const g=L.create(L.setup(config),'bunt0915:'+i),b=E.currentBatter(g),pitcher=E.currentPitcher(g);for(let n=0;n<50;n++){const p=SL_TACTICS.resolveBunt(g,pitcher,b),result=E.applyPitch(g,p,b,pitcher);if(p.outcome==='inPlay'){inPlay++;assert(p.physical);assert(p.defensivePlan);assert(p.defenseDecision||p.record);sacrifices+=result.result==='sacrificeBunt';}if(result.ended)break;}}assert(inPlay>0&&sacrifices>0);report.bunts={inPlay,sacrifices};});
for(const [a,b]of [['C','C'],['S','G'],['G','S']]){const g=E.newGame([E.makeTeam('オール'+a,'away',[],E.CONFIG),E.makeTeam('オール'+b,'home',[],E.CONFIG)],'0915:'+a+b);E.advance(g,'game');assert(g.state.finished);assert(g.state.score.every(Number.isFinite));const anomalies=g.state.events.flatMap(e=>SL_CUSTOM_MATCH.anomalies(e));assert.deepEqual(anomalies,[]);for(const e of g.state.events){for(const leg of e.play?.transfers||[]){const before=F.samplePlay(e.play,leg.start-1e-7);assert.equal(before.ballOwner,leg.throwerKey);assert(Math.hypot(before.positions[leg.fromIndex][0]-leg.fromPoint[0],before.positions[leg.fromIndex][1]-leg.fromPoint[1])<.01,'throw begins at current owner position');}}report.matches.push({teams:[a,b],score:g.state.score,events:g.state.events.length,finished:g.state.finished});console.log('PASS completed',a,b,g.state.score);}
fs.writeFileSync('test-artifacts/emergency-preserve-process.json',JSON.stringify(report,null,2));

