const fs=require('fs'),vm=require('vm'),http=require('http'),path=require('path'),cp=require('child_process'),crypto=require('crypto'),assert=require('node:assert/strict');
const baseline='c92c4367976a3003d6049189b3a14a243ab8007b',old=f=>cp.execFileSync('git',['show',baseline+':'+f],{encoding:'utf8'}).replaceAll('\r\n','\n'),html=fs.readFileSync('index.html','utf8').replaceAll('\r\n','\n'),prior=old('index.html');
const section=(s,a,b)=>s.slice(s.indexOf(a),s.indexOf(b,s.indexOf(a)));
assert.equal(section(html,'const teams = [','const STORAGE ='),section(prior,'const teams = [','const STORAGE ='));
assert.equal(html.slice(html.indexOf('// ===== SL WORLD STABLE 3/3 END =====')),prior.slice(prior.indexOf('// ===== SL WORLD STABLE 3/3 END =====')),'historical articles unchanged');
const hashes=JSON.parse(fs.readFileSync('test-artifacts/teams-view-protected.json','utf8'));for(const [f,hash]of Object.entries(hashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),hash,f+' protected');
const c=vm.createContext({});for(const f of ['team-registry.js','lineup-display.js','special-abilities.js','teams-view.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});const R=c.SL_TEAM_REGISTRY,V=c.SL_TEAMS_VIEW,plain=x=>JSON.parse(JSON.stringify(x));
const o=vm.createContext({});vm.runInContext(section(prior,'const SL_TEAM_REGISTRY =','/* END CURRENT TEAM REGISTRY */')+'\nglobalThis.r=SL_TEAM_REGISTRY;',o);assert.deepEqual(plain(R.clubs),plain(o.r.clubs),'same 22 teams, regions, aliases');
const editorOld=old('player-editor.html'),start=editorOld.indexOf('const SPECIALS = {'),end=editorOld.indexOf('\n};',start)+3;vm.runInContext(editorOld.slice(start,end)+'\nglobalThis.specials=SPECIALS;',o);assert.deepEqual(plain(c.SL_SPECIALS),plain(o.specials),'all category definitions identical');
assert.equal(new Set(R.clubs.map(t=>t.id)).size,22);assert.equal(R.forLeague('SL').length,12);assert.equal(R.forLeague('TL').length,10);const club=R.byId('club-002');club.league='TL';assert.equal(R.forLeague('SL').length,11);assert.equal(R.forLeague('TL').length,11);club.league='EL';assert(R.forLeague('EL').includes(club));club.league='SL';assert.equal(club.id,'club-002');
const fixtures=[
 {id:'legacy',name:'同名選手',team:'納東一',isFielder:true,isPitcher:false,mainPosition:'OF',subPositions:[],batting:{meet:10,power:120,speed:14,arm:16,fielding:18,catching:2},pitching:{velocity:null,control:null,stamina:null},specials:['アベレージヒッター','人気者','三振癖','安打製造機','勝負師'],pitchRepertoire:{straight:[],slider:[],curve:[],fork:[],sinker:[],shoot:[]}},
 {id:'explicit',name:'同名選手',teamId:'club-003',team:'納東一',batting:{meet:1,power:40,speed:7,arm:10,fielding:13,catching:20},specials:['存在しない○']},
 {id:0,name:'TL登録選手',teamId:'club-013',batting:{meet:null,power:201,speed:12},specials:[]}
];
const text=JSON.stringify(fixtures),storage={getItem:()=>text},roster=V.readRoster(storage);assert.deepEqual(plain(roster.byTeam.get('club-002')),['legacy']);assert.deepEqual(plain(roster.byTeam.get('club-003')),['explicit']);assert.deepEqual(plain(roster.byTeam.get('club-013')),[0]);assert.equal(JSON.stringify(fixtures),text);
assert.equal(V.readRoster({getItem:()=>'{bad'}).error!=null,true);assert.equal(V.readRoster({getItem:()=>JSON.stringify([{id:'x',teamId:'unknown',team:'納東一'}])}).byId.size,0);assert.equal(V.readRoster({getItem:()=>JSON.stringify([{id:'x',team:'納東一'},{id:'x',team:'納東一'}])}).byId.size,0);assert.equal(V.readRoster({getItem:()=>JSON.stringify({players:fixtures})}).byId.size,3);
assert.equal(c.SL_TRAITS.get('存在しない○'),null);for(const [name,color]of [['アベレージヒッター','blue'],['人気者','green'],['三振癖','red'],['安打製造機','gold'],['勝負師','rainbow']])assert.equal(c.SL_TRAITS.get(name).color,color);
for(const f of ['index.html','player-editor.html'])for(const [,code]of fs.readFileSync(f,'utf8').matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(code);
console.log('PASS data: 22 preserved teams; SL/TL/EL membership; typed player IDs, legacy alias bridge and explicit-ID precedence; exact original trait catalogue; '+Object.keys(hashes).length+' protected files and history unchanged');
if(process.argv.includes('--data-only'))process.exit(0);
const {chromium}=require('playwright');
(async()=>{const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.resolve(__dirname,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(__dirname+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':file.endsWith('.webmanifest')?'application/manifest+json':'text/html');res.end(data);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;let browser;
try{browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{errors.push(d.message());await d.dismiss();});
 await page.addInitScript(text=>{sessionStorage.setItem('sl_world_opening_played','1');if(localStorage.getItem('sl_world_players_v01')===null)localStorage.setItem('sl_world_players_v01',text);},text);await page.goto(url+'/index.html#management');const saved=await page.evaluate(()=>JSON.stringify({...localStorage}));
 await page.locator('[data-view="history"]').click();assert.equal(await page.locator('#history [data-archive$="-clubs"]').count(),0);for(const tab of ['sl','cc','jc','king','timeline','legend']){await page.locator('[data-archive="'+tab+'"]').click();assert(await page.locator('#archive-'+tab).isVisible());}
 await page.locator('[data-view="teams"]').click();assert((await page.locator('#teamsBrowser').innerText()).includes('SUPER LEAGUE'));assert((await page.locator('#teamsBrowser').innerText()).includes('TECHNICAL LEAGUE'));
 const action=id=>page.locator('[data-teams-action="'+id+'"]'),league=id=>page.locator('[data-league-id="'+id+'"]'),team=id=>page.locator('[data-team-id="'+id+'"]'),player=id=>page.locator('[data-player-id="'+id+'"]');
 for(const lg of ['SL','TL']){await league(lg).click();assert.equal(await action('team').count(),R.forLeague(lg).length);for(const club of R.forLeague(lg)){await team(club.id).click();const body=await page.locator('#teamsBrowser').innerText();assert(body.includes(club.currentName));assert(body.includes(R.leagues[lg].name));assert(body.includes('地域：'+club.region));if(!roster.byTeam.has(club.id))assert(body.includes('選手データ未登録'));await action('teams-back').click();}await action('leagues-back').click();}
 await league('SL').click();await page.evaluate(()=>SL_TEAM_REGISTRY.byId('club-002').league='TL');assert.equal(await team('club-002').count(),0);await action('leagues-back').click();await league('TL').click();assert.equal(await team('club-002').count(),1);await page.evaluate(()=>SL_TEAM_REGISTRY.byId('club-002').league='EL');assert.equal(await team('club-002').count(),0);await page.evaluate(()=>SL_TEAM_REGISTRY.byId('club-002').league='SL');await action('leagues-back').click();
 await league('SL').click();await team('club-002').click();assert.equal(await action('player').count(),1);await player('legacy').click();assert.equal(await page.locator('.player-ability-card').count(),6);assert.deepEqual(await page.locator('.player-ability-card .ability-rank').allTextContents(),['S','D','C','B','A','G']);assert.deepEqual(await page.locator('.player-ability-value').allTextContents(),['10','120','14','16','18','2']);
 const colors=await page.evaluate(()=>Object.fromEntries(SL_ABILITY_DISPLAY.RANKS.map(rank=>{const e=document.createElement('span');e.className='ability-rank rank-'+rank;document.body.append(e);const color=getComputedStyle(e).color;e.remove();return [rank,color];})));assert.deepEqual(colors,{G:'rgb(182, 190, 200)',F:'rgb(113, 183, 255)',E:'rgb(118, 215, 155)',D:'rgb(241, 229, 105)',C:'rgb(255, 182, 107)',B:'rgb(255, 133, 133)',A:'rgb(247, 165, 211)',S:'rgb(233, 195, 93)'});assert.notEqual(colors.D,colors.S);
 assert(!(await page.locator('.player-traits').evaluate(e=>e.open)));assert(!(await page.locator('.trait-badge').first().isVisible()));await page.locator('.player-traits summary').click();assert.deepEqual(await page.locator('.trait-badge').evaluateAll(es=>es.map(e=>e.dataset.traitCategory)),['blue','green','red','gold','rainbow']);assert((await page.locator('.trait-badge.red').innerText()).includes('マイナス'));assert.equal(await page.locator('.trait-badge.gold').evaluate(e=>getComputedStyle(e).borderTopColor),'rgb(255, 200, 61)');assert((await page.locator('.trait-badge.rainbow').evaluate(e=>getComputedStyle(e).backgroundImage)).includes('linear-gradient'));
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow '+width);const rects=await page.locator('.player-ability-card').evaluateAll(es=>es.map(e=>({y:e.getBoundingClientRect().top,x:e.getBoundingClientRect().left})));assert.equal(new Set(rects.map(r=>r.y)).size,2);assert.equal(new Set(rects.map(r=>r.x)).size,3);}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-artifacts/teams-player-traits.png',fullPage:true});await action('team-back').click();assert.equal(await page.evaluate(()=>document.activeElement.dataset.playerId),'legacy');await action('teams-back').click();await team('club-003').click();await player('explicit').click();assert.equal(await page.locator('[data-ability="meet"] .ability-rank').innerText(),'G');await page.locator('.player-traits summary').click();assert.equal(await page.locator('.trait-badge').getAttribute('data-trait-category'),'unknown');await action('team-back').click();await action('teams-back').click();await action('leagues-back').click();
 await league('TL').click();await team('club-013').click();await player('0').click();assert.equal(await page.locator('[data-ability="meet"] .player-ability-value').innerText(),'未設定');assert.equal(await page.locator('[data-ability="power"] .ability-rank').innerText(),'対象外');await action('team-back').click();await action('teams-back').click();await action('leagues-back').click();await page.screenshot({path:'test-artifacts/teams-league-selector.png',fullPage:true});assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage})),saved);
 await page.reload();await page.locator('[data-view="teams"]').click();assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage})),saved);assert.deepEqual(errors,[]);
 // Editor continues to use the exact same definitions and saves ID + legacy-compatible name.
 const editPage=await context.newPage();editPage.on('pageerror',e=>errors.push(e.message));await editPage.goto(url+'/player-editor.html');await editPage.evaluate(()=>editPlayer('legacy'));assert.equal(await editPage.locator('#team').inputValue(),'アステリア');await editPage.locator('#saveBtn').click();let savedPlayer=await editPage.evaluate(()=>JSON.parse(localStorage.getItem('sl_world_players_v01')).find(p=>p.id==='legacy'));assert.equal(savedPlayer.teamId,'club-002');assert.deepEqual(savedPlayer.batting,fixtures[0].batting);assert.deepEqual(savedPlayer.specials,fixtures[0].specials);await editPage.evaluate(()=>editPlayer('legacy'));await editPage.locator('#team').selectOption('霞ヶ浦セイラーズ');await editPage.locator('#saveBtn').click();savedPlayer=await editPage.evaluate(()=>JSON.parse(localStorage.getItem('sl_world_players_v01')).find(p=>p.id==='legacy'));assert.equal(savedPlayer.teamId,'club-013');assert.equal(savedPlayer.team,'霞ヶ浦セイラーズ');assert.deepEqual(savedPlayer.batting,fixtures[0].batting);assert.deepEqual(savedPlayer.specials,fixtures[0].specials);assert.deepEqual(errors,[]);
 // New shared resources are included in the existing offline cache.
 const offline=await browser.newContext();const op=await offline.newPage();await op.addInitScript(()=>sessionStorage.setItem('sl_world_opening_played','1'));await op.goto(url+'/index.html#management');await op.waitForFunction(()=>navigator.serviceWorker.controller!=null);await offline.setOffline(true);await op.reload();await op.locator('[data-view="teams"]').click();await op.locator('[data-league-id="TL"]').click();assert.equal(await op.locator('[data-team-id]').count(),10);await op.goto(url+'/player-editor.html');assert.equal(await op.locator('#team option').count(),22);await offline.close();
 console.log('PASS browser: History separated; 22 teams/details; dynamic SL/TL/EL; registered and empty rosters; IDs; six values/ranks and exact eight colors; five trait categories; 2x3 at 320/390/1280px; storage unchanged by viewing; editor saves teamId without changing abilities/traits; offline dependencies');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
