const fs=require('fs'),vm=require('vm'),http=require('http'),path=require('path'),cp=require('child_process'),crypto=require('crypto'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8').replaceAll('\r\n','\n');
const prior=cp.execFileSync('git',['show','be73bb264fd062117fb91414c60b57d5d669265f:index.html'],{encoding:'utf8'}).replaceAll('\r\n','\n');
const section=(s,a,b)=>s.slice(s.indexOf(a),s.indexOf(b,s.indexOf(a)));
assert.equal(section(html,'const teams = [','const STORAGE ='),section(prior,'const teams = [','const STORAGE ='),'legacy teams, managers, points and historical data unchanged');
assert.equal(html.slice(html.indexOf('// ===== SL WORLD STABLE 3/3 END =====')),prior.slice(prior.indexOf('// ===== SL WORLD STABLE 3/3 END =====')),'all complete historical articles unchanged');
const hashes=JSON.parse(fs.readFileSync('test-artifacts/team-history-protected.json','utf8'));
for(const [f,hash]of Object.entries(hashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),hash,'engine/LAB unchanged this task: '+f);
const c=vm.createContext({});vm.runInContext(section(html,'const SL_TEAM_REGISTRY =','/* END CURRENT TEAM REGISTRY */')+'\nglobalThis.registry=SL_TEAM_REGISTRY;',c);const R=c.registry;
const expected={SL:[['デビルスターズ','東東京'],['アステリア','徳島'],['東京アスレチックス','東東京'],['桐蔭フロンティア','大阪'],['ブルーマリナーズ','静岡'],['東海ユナイテッド','神奈川'],['明道仁球会','福井'],['明訓ベースボールクラブ','神奈川'],['武勇館','石川'],['キューバ・リベルタード','福岡'],['知略野球研究所','兵庫'],['鳥取野球倶楽部','鳥取']],TL:[['霞ヶ浦セイラーズ','茨城'],['邦成重工','大分'],['福島レガリア','福島'],['火乃国球道会','熊本'],['倉敷鋼業','岡山'],['西東京オリオンズ','西東京'],['紀州パイレーツ','和歌山'],['関西電機','大阪'],['幕張アストロズ','千葉'],['飛騨製作所','岐阜']]};
assert.equal(R.clubs.length,22);assert.equal(new Set(R.clubs.map(t=>t.id)).size,22);for(const league of ['SL','TL'])assert.deepEqual(JSON.parse(JSON.stringify(R.forLeague(league).map(t=>[t.currentName,t.region]))),expected[league]);
for(const team of R.clubs){assert.deepEqual(Object.keys(team),['id','currentName','league','region','formerName','aliases']);assert.equal(R.byId(team.id),team);for(const name of [team.currentName,team.formerName,...team.aliases].filter(Boolean))assert.equal(R.resolve(name,team.league),team);assert(Object.isFrozen(team));}
assert.equal(R.resolve(null),null);assert.equal(R.resolve(''),null);assert.equal(R.resolve('存在しないチーム'),null);assert.equal(R.resolve('能体工','SL'),null);assert.equal(R.resolve('日本体育大荏原').id,R.resolve('日体荏原').id);
for(const [,code] of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(code);
console.log('PASS registry: exact 12 SL + 10 TL, unique immutable IDs, aliases only, no invented match/player fields; historical source and '+Object.keys(hashes).length+' protected files unchanged');
if(process.argv.includes('--data-only'))process.exit(0);
const {chromium}=require('playwright');
(async()=>{const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');const f=path.resolve(__dirname,'.'+decodeURIComponent(url.pathname));if(!f.startsWith(__dirname+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'text/html');res.end(data);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{errors.push(d.message());await d.dismiss();});
 const saved={'sl34_tournaments':'[]','sl_relationships':JSON.stringify([{a:'納東一',b:'日本体育大荏原',level:'通常'}]),'sl_transfers_complete':JSON.stringify([{player:'既存選手',from:'納東一',to:'大阪桐蔭',type:'完全移籍',memo:'当時の記録'}]),'sl_world_players_v01':JSON.stringify([{id:'existing',name:'既存選手',team:'納東一'}]),'sl_world_memo':'保存メモ'};
 await page.addInitScript(saved=>{sessionStorage.setItem('sl_world_opening_played','1');for(const [key,value]of Object.entries(saved))if(localStorage.getItem(key)===null)localStorage.setItem(key,value);},saved);
 await page.goto('http://127.0.0.1:'+server.address().port+'/index.html#management');await page.locator('[data-view="history"]').click();
 const storage=()=>page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)])));const initialStorage=await storage();for(const [key,value]of Object.entries(saved))assert.equal(initialStorage[key],value);
 for(const league of ['SL','TL']){const prefix=league.toLowerCase();await page.locator('[data-archive="'+prefix+'-clubs"]').click();assert.equal(await page.locator('#'+prefix+'ClubList [data-club-id]').count(),expected[league].length);assert.deepEqual(await page.locator('#'+prefix+'ClubList [data-club-id]').allTextContents(),expected[league].map(x=>x[0]));
  for(const [name,region]of expected[league]){const button=page.locator('#'+prefix+'ClubList button').filter({hasText:name});await button.click();const detail=page.locator('#'+prefix+'ClubDetail');assert(await detail.isVisible());assert.equal(await detail.locator('h3').innerText(),name);assert((await detail.innerText()).includes('所属リーグ：'+league));assert((await detail.innerText()).includes('地域：'+region));if(league==='TL')assert(!/選手|監督|成績|勝率|順位|試合結果/.test(await detail.innerText()));await detail.locator('button').click();assert(await button.isVisible());assert(await button.evaluate(b=>document.activeElement===b));}
 }
 // Historical edition labels remain old; club aggregate labels are current.
 await page.locator('[data-archive="sl"]').click();assert((await page.locator('#slChampionArchive .box').innerText()).includes('アステリア'));assert((await page.locator('#slChampionArchive').innerText()).includes('納東一'));
 for(const tab of ['cc','jc','king','timeline','legend']){await page.locator('[data-archive="'+tab+'"]').click();assert(await page.locator('#archive-'+tab).isVisible());assert((await page.locator('#archive-'+tab).innerText()).length>20);}
 await page.locator('[data-view="teams"]').click();const names=await page.locator('#teamCards h2').allTextContents();assert.deepEqual(names.map(s=>s.trim()).sort(),expected.SL.map(x=>x[0]).sort());assert((await page.locator('#relationshipList').innerText()).includes('アステリア'));assert((await page.locator('#relationshipList').innerText()).includes('東京アスレチックス'));
 await page.locator('[data-view="history"]').click();for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});for(const prefix of ['sl','tl']){await page.locator('[data-archive="'+prefix+'-clubs"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);await page.locator('#'+prefix+'ClubList button').first().click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'detail overflow '+width);await page.locator('#'+prefix+'ClubDetail button').click();}}
 await page.setViewportSize({width:390,height:844});await page.locator('[data-archive="tl-clubs"]').click();await page.screenshot({path:'test-artifacts/history-tl-clubs.png',fullPage:true});await page.locator('#tlClubList button').first().click();await page.screenshot({path:'test-artifacts/history-tl-detail.png',fullPage:true});
 assert.deepEqual(await storage(),initialStorage);await page.reload();await page.locator('[data-view="history"]').click();await page.locator('[data-archive="sl-clubs"]').click();assert.equal(await page.locator('#slClubList button').count(),12);assert.deepEqual(await storage(),initialStorage);assert.deepEqual(errors,[]);
 console.log('PASS browser: all 22 details/back/focus, both leagues, 6 old archives, current club labels, 320/390/1280px, reload; stored player/team/history data unchanged; no page errors');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
