const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
for(const file of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js','custom-match-core.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});
const E=SL_ENGINE,F=SL_FIELDING,P=F.process,C=SL_CUSTOM_MATCH,copy=x=>JSON.parse(JSON.stringify(x));
const settings={runCount:1,teams:[C.preset(),C.preset()]};
const make=()=>{const g=E.newGame(C.teams(settings),'night');g.rng=()=>.5;g.tacticalRng=()=>.999;return g;};
function ball(v,angle,spray=0,type='FLY'){const rad=angle*Math.PI/180;return {outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:v,launchAngle:angle,sprayAngle:spray,type,hangTime:type==='GROUND'?0:2*v*Math.sin(rad)/9.81,horizontalSpeed:v*(type==='GROUND'?6:5*Math.cos(rad)*(type==='LINER'?.86:.65)),deceleration:type==='GROUND'?48:62,height:0}};}
const shallow=()=>ball(34,40),deep=()=>ball(41,50),infield=()=>ball(22,55),liner=()=>ball(35,15,.4,'LINER');
function run(p,outs=0,occupied=[1],speed=14,arm=14){const g=make();g.state.outs=outs;for(const base of occupied){const r=g.teams[0].lineup[base+1];r.profile.batting.speed=speed;r.effective.speed=speed;g.state.bases[base-1]=r;}for(const f of F.defense(g).slice(6)){f.profile.batting.arm=arm;f.effective.arm=arm;}const b=E.currentBatter(g),before=copy(g.state.bases),result=E.applyPitch(g,p,b,E.currentPitcher(g)).result;const event={...p,result,batter:{key:b.key},outsBefore:outs,outsAfter:g.state.outs,runnersBefore:before,runnersAfter:copy(g.state.bases),actions:copy(g.state.playActions)};F.annotate(g,event);assert.deepEqual(C.anomalies(event),[]);return {g,p,event,result,runner:base=>p.runnerDecisions.find(r=>r.from===base)};}
const results=[];
let x=run(infield(),0,[1]);assert(x.runner(1).decisions.some(d=>d.decision==='STAY'));assert(x.runner(1).legs.every(l=>l.toBase<=1.001));assert.equal(x.p.throws.length,0);results.push(['infield',x.result]);
x=run(shallow(),1,[2]);assert(x.p.interception.airborne);assert(x.runner(2).decisions.some(d=>d.decision==='READ_HOLD'));assert(x.runner(2).legs.filter(l=>l.start<x.p.trajectory.fieldTime).every(l=>l.toBase<=2.28));assert.equal(x.runner(2).lastSafe,2);results.push(['shallow',x.runner(2).decisions.map(d=>d.decision)]);
x=run(deep(),0,[2],20,2);assert(x.p.interception.airborne);assert(x.runner(2).decisions.some(d=>d.decision==='TAG_UP_PREP'));let start=x.runner(2).legs.find(l=>l.toBase===3);assert(Math.abs(start.start-x.p.trajectory.fieldTime)<1e-6);assert(x.runner(2).legs.filter(l=>l.start<start.start).every(l=>l.toBase===2));results.push(['deep second',x.result,x.runner(2).lastSafe]);
x=run(deep(),1,[3],20,2);assert(x.runner(3).decisions.some(d=>d.decision==='TAG_UP_START'));assert.equal(x.runner(3).lastSafe,4);assert.equal(x.result,'sacrificeFly');results.push(['deep third',x.result]);
// Identical contact and runner: catcher/throw arrival, not intent, decides the tag.
{const safe=run(ball(38,40),1,[3],20,14),out=run(ball(38,40),1,[3],20,20);assert(safe.runner(3).tagReleased&&out.runner(3).tagReleased);assert.equal(safe.result,'sacrificeFly');assert(out.runner(3).out);assert.equal(out.g.state.outs,3);assert(safe.p.throws[0].tagAt>safe.p.throws[0].timing.runnerETA);assert(out.p.throws[0].tagAt<out.p.throws[0].timing.runnerETA);results.push(['same contact tag race',safe.p.throws[0].tagAt,out.p.throws[0].tagAt,safe.p.throws[0].timing.runnerETA]);}
const first=run(deep(),0,[1],20,2);assert(!first.runner(1).decisions.some(d=>d.decision==='TAG_UP_PREP'),'first-to-second has different tradeoff');
{const g=make(),r={runner:g.teams[0].lineup[2],from:1};r.runner.effective.speed=20;F.defense(g)[8].profile.batting.arm=1;F.defense(g)[8].profile.batting.catching=1;const observation={remaining:2,candidate:{index:8,point:[655,175],depth:360,current:[610,190],at:6,effort:1,arm:0},source:'observed corner trajectory'};assert.equal(P.flyRunningRead(g,deep(),r,0,observation).mode,'TAG_UP_PREP','first-to-second is possible in a deep corner with poor throwing posture');}
for(let mask=1;mask<8;mask++){const occupied=[1,2,3].filter(b=>mask&(1<<(b-1))),x=run(deep(),2,occupied);assert.equal(x.g.state.outs,3);assert.equal(x.g.state.score[0],0);for(const b of occupied){const r=x.runner(b);assert(r.legs.some(l=>l.toBase>l.fromBase&&l.start<x.p.trajectory.fieldTime));assert(!r.decisions.some(d=>d.decision==='TAG_RETURN'));}assert.equal(x.p.throws.length,0);}
x=run(liner(),0,[]);assert(x.p.interception.airborne);assert.equal(x.p.throws.length,0);assert.equal(x.event.transfers.length,0,'annotation must not invent a return');
// Observed catch + a displaced runner. No success label: the return leg races the throw.
function appeal(returnFraction,arm=14,outs=1){
 const g=make(),p=liner();g.state.outs=outs;P.geometry(g,p);P.defensePlan(g,p);const at=p.trajectory.fieldTime,runner=g.teams[0].lineup[3],duration=P.runTime(g,runner,2),start=at-returnFraction*duration;
 const r={runner,from:2,lastSafe:2,at:2,target:3,legs:[{fromBase:2,toBase:3,start,end:start+duration}],decisions:[]};g.state.bases[1]=r.runner;
 P.retouchAfterCatch(g,[r],at);const owner=p.fielderIndex;F.defense(g)[owner].profile.batting.arm=arm;
 const choices=P.runningTargets(g,p,[r],owner,p.fieldingPoint,at+.5);
 if(choices.length){const a=choices[0],transfer={...a,runnerKey:r.runner.key,result:'safe'};P.retireOnTransfer(g,[r],transfer,E.currentPitcher(g));return {g,r,transfer};}return {g,r};
}
let a=appeal(.85);assert(a.transfer&&a.transfer.kind==='appeal');assert(a.transfer.tagAt<a.transfer.runnerETA);assert(a.r.out);assert.equal(a.g.state.outs,2);assert.equal(a.g.state.playActions.at(-1).type,'retouchOut');results.push(['appeal',a.transfer.tagAt,a.transfer.runnerETA]);
a=appeal(.08);assert(!a.transfer,'already returning in time: hold');
a=appeal(.85,14,2);assert.equal(a.g.state.outs,3);
// Same runner and throw, crossing the arrival boundary changes the putout.
{const g=make(),r={runner:g.teams[0].lineup[3],from:2,target:2,retouchRequired:true,legs:[{fromBase:2.8,toBase:2,start:4,end:6}]};assert(P.outAtTransfer(r,{kind:'appeal',toBase:2,tagAt:5.9}));assert(!P.outAtTransfer(r,{kind:'appeal',toBase:2,tagAt:6.1}));}
// Base responsibilities are handed off even when there is no immediate throw.
function cover(primary,point,spray=0,secondary=null){const g=make(),p=ball(30,0,spray,'GROUND');Object.assign(p,{fielderIndex:primary,fieldingPoint:point,landingPoint:point,interception:{point,time:2},trajectory:{fieldTime:2},chase:{secondary,until:.7,point},handling:{effort:.5}});P.defensePlan(g,p);return {g,p};}
for(const [primary,middle] of [[3,5],[5,3]]){const {p}=cover(primary,F.layout.positions[primary],0,middle);assert.equal(p.defensivePlan.responsibilities.second,middle);assert(p.defensivePlan.tracks[middle].legs.find(l=>l.role==='baseCover').start<p.chase.until);assert(p.defensivePlan.tracks[middle].legs.some(l=>l.role==='baseCover'&&l.to[0]===400&&l.to[1]===225));}
{const {p}=cover(4,[205,285],-.6,5);assert(p.defensivePlan.tracks[5].legs.some(l=>l.role==='backup'));assert.equal(p.defensivePlan.responsibilities.second,3);assert.equal(p.defensivePlan.tracks[3].legs.at(-1).role,'baseCover');}
{const {p}=cover(2,[510,235],.5);const c=p.defensivePlan.responsibilities;assert([0,3].includes(c.first));assert.notEqual(c.first,c.second);assert.equal(c.second,5);assert.deepEqual(p.defensivePlan.tracks[c.first].legs.at(-1).to,F.layout.bases[1]);}
{const {g,p}=cover(2,[510,235],.5,3);F.defense(g)[0].profile.batting.speed=20;F.defense(g)[3].profile.batting.speed=1;g.state.bases[0]=g.teams[0].lineup[3];P.defensePlan(g,p);assert.equal(p.defensivePlan.responsibilities.first,0);assert.equal(p.defensivePlan.responsibilities.second,3);}
for(const [direction,primary,middle] of [[.4,3,5],[-.35,5,3]]){const x=run(ball(35,0,direction,'GROUND'),0,[1]);assert.equal(x.p.fielderIndex,primary);assert(x.event.play.tracks[middle].legs.some(l=>l.roleCode==='BASE COVER'&&l.to[0]===400&&l.to[1]===225));}
// Ground scoring is checked against completed throws and out identities.
function ground(seed,velocity=35){const g=make();g.tacticalRng=()=>seed;g.state.outs=1;g.state.bases[0]=g.teams[0].lineup[3];const b=E.currentBatter(g);b.profile.batting.speed=20;b.effective.speed=20;const p=ball(velocity,0,-.35,'GROUND'),result=E.applyPitch(g,p,b,E.currentPitcher(g)).result;return {g,p,result,b};}
const outcomes=[20,21,22,26,30,35].flatMap(v=>[0,.2,.4,.6,.8,.999].map(seed=>ground(seed,v)));const normal=outcomes.find(x=>x.result==='groundout');assert(normal);assert.equal(normal.p.throw.toBase,1);assert(normal.p.record.actions.some(a=>a.runner.key===normal.b.key&&a.result==='out'));const fc=outcomes.find(x=>x.result==='fieldersChoice');assert(fc);assert.equal(fc.p.throw.toBase,2);assert.equal(fc.g.state.bases[0].key,fc.b.key);assert.equal(fc.p.record.classificationReason,'another runner targeted; batter remains safe');
// The trajectory generator remains byte-identical to the pre-fix implementation.
const old=require('child_process').execFileSync('git',['show','HEAD:engine006-fielding.js'],{encoding:'utf8'}),current=fs.readFileSync('engine006-fielding.js','utf8');const generator=s=>s.slice(s.indexOf(' function generate(g,b,quality'),s.indexOf(' function geometry(',s.indexOf(' function generate(g,b,quality')));assert.equal(generator(current),generator(old).replace(/\r\n/g,'\n'));
fs.writeFileSync('test-artifacts/night-regression.json',JSON.stringify({passed:true,version:E.CONFIG.version,scenes:results,coverage:['2B -> SS','SS -> 2B','3B line -> SS backup','1B vacated -> first/second handoff'],fc:{normal:normal.p.record,choice:fc.p.record}},null,2));console.log('PASS night regression',results);


