const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=globalThis;for(const file of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js','custom-match-core.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});
const E=c.SL_ENGINE,F=c.SL_FIELDING,C=c.SL_CUSTOM_MATCH,L=c.SL_LAB,R=c.SL_MATCH_REPLAY,copy=x=>JSON.parse(JSON.stringify(x));
const batchCount=process.argv.includes('--quick')?10:100;const settings={runCount:batchCount,seed:'process-regression',teams:[C.preset(),C.preset()]};
const make=seed=>E.newGame(C.teams(settings),seed);let g=make('physical');const spec=E.resolveFinalResult(g,E.currentBatter(g),{}, {score:.5,grade:'normal'},{});assert.equal(spec.battedResult,null);assert(spec.physical&&spec.physical.exitVelocity>0);
const points=new Set();for(let i=0;i<64;i++){const h=make(i),p=F.process.generate(h,E.currentBatter(h),{score:.5,grade:'normal'});p.battedResult=i%2?'triple':'out';F.geometry(h,p);points.add(p.landingPoint.map(n=>n.toFixed(3)).join());assert(p.trajectory.candidates.every(c=>Number.isFinite(c.time)));}assert(points.size>60);
// A label cannot affect an otherwise identical physical ball or pursuit.
{const a=make('blind'),b=make('blind'),x=F.process.generate(a,E.currentBatter(a),{score:.5,grade:'normal'}),y=F.process.generate(b,E.currentBatter(b),{score:.5,grade:'normal'});x.battedResult='triple';y.battedResult='groundout';F.geometry(a,x);F.geometry(b,y);assert.deepEqual(copy(x.interception),copy(y.interception));assert.deepEqual(copy(x.chase),copy(y.chase));}
// Fast catcher/quick delivery can beat a runner; speed and traits change actual arrival times.
const races=[];for(const speed of [2,20])for(const arm of [2,20]){const h=make('race'),r=h.teams[0].lineup[2],p=E.currentPitcher(h);r.effective.speed=speed;r.profile.batting.speed=speed;F.defense(h)[1].profile.batting.arm=arm;const x=F.stealExecution(h,r,p,1);races.push({speed,arm,...x,safe:x.runnerETA<=x.tagAt});assert(x.startTime<x.pitchArrival);assert(x.throwStart>x.pitchArrival);}
assert(races.some(r=>r.safe)&&races.some(r=>!r.safe));assert(races[0].runnerETA>races[2].runnerETA);assert(races[0].tagAt>races[1].tagAt);
{const h=make('steal'),r=h.teams[0].lineup[2],p=E.currentPitcher(h);h.state.bases[0]=r;const before=h.state.bases.map(x=>x&&({key:x.key,name:x.name}));h.state.playBefore=before;const event=F.steal(h,p,{fromBase:1});Object.assign(event,{runnersBefore:before,runnersAfter:h.state.bases.map(x=>x&&({key:x.key})),outsBefore:0,outsAfter:h.state.outs,actions:copy(h.state.playActions),batter:{key:E.currentBatter(h).key}});F.annotate(h,event);const replay=R.toReplayEvent(event),plan=R.animationPlan(replay),runner=event.play.runners.find(r=>r.runner.key===event.runner.key);assert(plan.pitchEnd+runner.start*1000<plan.pitchEnd);assert(Math.abs(event.play.transfers[0].tagAt-(event.stealExecution.tagAt-event.stealExecution.pitchArrival))<1e-6);assert.equal(event.stolenBase,event.stealExecution.runnerETA<=event.stealExecution.tagAt);}
// Protect the existing force-to-second, transfer-to-first and third-out sequence.
for(const outs of [0,1,2]){const h=make('dp'+outs);h.state.outs=outs;h.state.bases[0]=h.teams[0].lineup[3];h.rng=()=>.5;h.tacticalRng=()=>.999;const p={ballType:'ground',battedResult:'groundout',fielderIndex:5,landingPoint:[325,250],battedQuality:.5};const result=F.field(h,p,E.currentBatter(h),E.currentPitcher(h));assert(h.state.outs<=3);assert(p.forceTrace);if(outs<2)assert(p.doublePlay,'protected second-to-first double play');if(p.doublePlay){assert.equal(h.state.outs-outs,2);assert.equal(p.throws[0].toBase,2);assert.equal(p.throws[1].toBase,1);}if(outs===2)assert.equal(h.state.outs,3);}

// Physical ground-ball regression: actual two-base cover and transfer order.
{const h=make('physical-dp'),b=E.currentBatter(h),pitcher=E.currentPitcher(h);h.state.bases[0]=h.teams[0].lineup[3];h.rng=()=>.5;h.tacticalRng=()=>.999;const ball={outcome:'inPlay',battedQuality:.5,physical:{exitVelocity:35,launchAngle:0,sprayAngle:-.35,type:'GROUND',hangTime:0,horizontalSpeed:210,deceleration:48,height:0}},result=E.applyPitch(h,ball,b,pitcher);assert.equal(result.result,'doublePlay');assert.equal(h.state.outs,2);assert.equal(ball.throws[0].toBase,2);assert.equal(ball.throws[1].toBase,1);assert(ball.defensivePlan);}
for(const [a,b] of [['G','G'],['S','S'],['B','E']]){const r=C.create({runCount:1,seed:'preset-'+a+b,teams:[C.preset(a),C.preset(b)]});C.step(r);assert.equal(r.runCount,1);assert.equal(r.anomalyCount,0);assert(Object.values(r.averages).every(Number.isFinite));}
// A second baseman initially pursues an overhead liner, then switches roles.
{const h=make('overhead'),b=E.currentBatter(h),p={outcome:'inPlay',battedResult:'triple',battedQuality:.5,physical:{exitVelocity:35,launchAngle:20,sprayAngle:.4,type:'LINER',hangTime:2.4,horizontalSpeed:180,deceleration:62,height:30}};F.geometry(h,p);assert.equal(p.chase.secondary,3);assert(p.fielderIndex>=6);F.process.defensePlan(h,p);const legs=p.defensivePlan.tracks[3].legs;assert.equal(legs[0].role,'secondary');assert(legs.some(l=>l.role==='relay'||l.role==='baseCover'));assert(legs[0].to[1]<legs[0].from[1]);assert(p.defensivePlan.tracks.filter(tr=>tr.legs[0]?.role==='primary'||tr.legs[0]?.role==='secondary').length<=2);}
// No runner / late hold is a hit, never a fielder's choice.
{const h=make('late'),b=E.currentBatter(h),p={ballType:'ground',fielderIndex:3,landingPoint:[473,253],trajectory:{fieldTime:5},battedQuality:.5};h.rng=()=>.5;assert.equal(F.field(h,p,b,E.currentPitcher(h)),'single');assert(!p.fieldersChoice);assert.equal(p.defenseDecision.decision,'HOLD_BALL');}
// Same observable steal condition can resolve differently without a success roll.
{const h=make('variation'),r=h.teams[0].lineup[2],pitcher=E.currentPitcher(h);const fast=F.stealExecution(h,r,pitcher,1,{start:-1,transfer:1,motion:1}),slow=F.stealExecution(h,r,pitcher,1,{start:1,transfer:-1,motion:-1});assert(fast.runnerETA<=fast.tagAt);assert(slow.runnerETA>slow.tagAt);}
assert(F.process.speed({profile:{batting:{speed:20}}},3)/F.process.speed({profile:{batting:{speed:1}}},3)<1.3);
const cutoff=F.relayFormation([400,100],2);assert(cutoff.relayPoint[1]<200&&cutoff.relayPoint[1]>155);
let inspected=0,summary={};for(let seed=0;seed<4;seed++){const h=make('audit'+seed);E.advance(h,'game');const hits=[0,0],runs=[0,0];for(const e of h.state.events){inspected++;summary[e.result]=(summary[e.result]||0)+1;assert.deepEqual(copy(C.anomalies(e)),[]);const side=e.half==='top'?0:1;hits[side]+=e.hit;runs[side]+=e.runsScored;if(e.physical){assert.equal(e.record.source,'completed-play-history');if(e.result==='fieldersChoice')assert(e.runnersBefore.some(Boolean));}if(e.play){for(const leg of e.play.transfers){assert(leg.start>=e.play.caught-.001);if(leg.timing)assert(Math.abs(leg.tagAt-leg.timing.ballETA)<.001,JSON.stringify({result:e.result,leg}));}assert(e.play.resetAt>e.play.completeAt);}}assert.deepEqual(copy(h.state.hits),hits);assert.deepEqual(copy(h.state.score),runs);}
const report=C.create(settings),start=performance.now();while(report.runCount<batchCount){C.step(report);assert(report.details.length<=8);assert(report.scenes.length<=32);assert(report.anomalies.length<=40);}const bytes=Buffer.byteLength(JSON.stringify(report));assert(bytes<2e6,'bounded JSON: '+bytes);assert.equal(report.games.length,batchCount);assert(Object.values(report.averages).every(Number.isFinite));assert.equal(report.anomalyCount,0);
for(const s of report.scenes){const scenario=C.labScenario(report,s),bundle=L.setup(scenario),exact=L.create(bundle,s.seed),e=E.onePitch(exact);assert.equal(e.result,s.result,'scene result '+s.seed+':'+s.sequence);assert.equal(e.sequence,s.sequence);const changed=copy(scenario);changed.outs=(scenario.outs+1)%3;changed.fatigue=scenario.fatigue+10;const altered=L.create(L.setup(changed),s.seed+'|changed');assert.equal(altered.state.outs,changed.outs);assert.equal(altered.state.pitching[E.currentPitcher(altered).key].pitches,changed.fatigue);assert.equal(e.tactics.decision,s.candidates.find(c=>c.tactic===s.selected&&c.probability>0)?.decision||e.tactics.decision);const varied=L.create(bundle,s.seed+'|new');assert.notEqual(varied.rng.getState(),exact.rng.getState());}
const result={passed:true,inspected,races:races.map(({speed,arm,runnerETA,tagAt,safe})=>({speed,arm,runnerETA,tagAt,safe})),results:summary,batch:{runCount:report.runCount,bytes,ms:performance.now()-start,sceneCount:report.scenes.length,detailCount:report.details.length,averages:report.averages}};fs.writeFileSync('test-artifacts/process-regression.json',JSON.stringify(result,null,2));fs.writeFileSync('test-artifacts/custom-match-'+batchCount+'.json',JSON.stringify(report));console.log(result);
