(()=>{'use strict';const $=id=>document.getElementById(id),JP=SL_DECISION_TRACE.JP;let worker=null,watchdog=null,lastWorkerMessage=0,report=null,detail=null,previous=null,viewer=null;
const purposeLabels={outfield:'外野打球の守備連携',ground:'内野ゴロの守備判断',cover:'ベースカバー',relay:'中継プレー',free:'自由に条件を設定'};
const ballValues={ground:{exitVelocity:32,launchAngle:0,hangTime:0,label:'ゴロ'},line:{exitVelocity:32,launchAngle:12,hangTime:1.8,label:'低い打球'},fly:{exitVelocity:30,launchAngle:38,hangTime:3.8,label:'フライ'}};
const positions={P:'投手',C:'捕手','1B':'一塁手','2B':'二塁手','3B':'三塁手',SS:'遊撃手',LF:'左翼手',CF:'中堅手',RF:'右翼手',NONE:'なし'};
function radio(name){return document.querySelector(`[name=${name}]:checked`);}
function selectPurpose(kind){$('purposeStep').hidden=true;$('setup').hidden=false;$('purposeName').textContent=purposeLabels[kind];$('setup').dataset.purpose=kind;const presets={outfield:['.55','line'],ground:['-.20','ground'],cover:['.10','ground'],relay:['.55','line'],free:['.55','line']},[direction,ball]=presets[kind];document.querySelector(`[name=directionChoice][value="${direction}"]`)?.click();document.querySelector(`[name=ballChoice][value="${ball}"]`)?.click();if(kind==='free')document.querySelector('.advanced').open=true;syncSimple();$('setup').scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('[data-purpose]').forEach(b=>b.onclick=()=>selectPurpose(b.dataset.purpose));$('changePurpose').onclick=()=>{$('setup').hidden=true;$('purposeStep').hidden=false;$('purposeStep').scrollIntoView({behavior:'smooth'});};
function syncSimple(){const direction=Number(radio('directionChoice').value),ball=ballValues[radio('ballChoice').value];$('direction').value=direction;$('exitVelocity').value=ball.exitVelocity;$('launchAngle').value=ball.launchAngle;$('hangTime').value=ball.hangTime;const directionName=radio('directionChoice').nextElementSibling.textContent;$('label').value=`${directionName}方向・${ball.label}`;renderRunSummary();}
function renderRunSummary(){if($('setup').hidden)return;const outs=radio('outsChoice')?.value??0,runners=[['一塁',$('runner1').checked],['二塁',$('runner2').checked],['三塁',$('runner3').checked]].filter(x=>x[1]).map(x=>x[0]),direction=radio('directionChoice')?.nextElementSibling.textContent,ball=radio('ballChoice')?.nextElementSibling.textContent,count=radio('count')?.value;$('runnerSummary').textContent=runners.length?`走者：${runners.join('・')}`:'走者なし';$('runSummary').textContent=`${outs}アウト / ${runners.join('・')||'走者なし'} / ${direction} / ${ball} / ${count==='1'?'1プレー詳細':count+'回'}`;}
document.querySelectorAll('[name=directionChoice],[name=ballChoice]').forEach(x=>x.onchange=syncSimple);document.querySelectorAll('[name=outsChoice],#runner1,#runner2,#runner3').forEach(x=>x.onchange=renderRunSummary);document.querySelectorAll('[name=count]').forEach(x=>x.onchange=()=>{$('customWrap').hidden=x.value!=='custom'||!x.checked;renderRunSummary();});
function settings(){const choice=radio('count').value,count=choice==='custom'?Number($('customCount').value):Number(choice);return {outs:Number(radio('outsChoice').value),runner1:$('runner1').checked,runner2:$('runner2').checked,runner3:$('runner3').checked,fielding:Number($('fielding').value),arm:Number($('arm').value),catching:Number($('catching').value),direction:Number($('direction').value),exitVelocity:Number($('exitVelocity').value),launchAngle:Number($('launchAngle').value),hangTime:Number($('hangTime').value),seed:$('seed').value,label:$('label').value,count};}
function stop(){worker?.terminate();worker=null;if(watchdog)clearInterval(watchdog);watchdog=null;$('run').disabled=false;$('cancel').hidden=true;}
$('cancel').onclick=()=>{stop();$('status').textContent='中止しました。';};
$('setup').onsubmit=e=>{e.preventDefault();try{const s=SL_RESPONSIBILITY_LAB.validate(settings());stop();$('run').disabled=true;$('cancel').hidden=false;$('results').hidden=true;$('progress').value=0;if(s.count===1){const start=performance.now(),trial=SL_RESPONSIBILITY_LAB.trial(s,`${s.seed}:0`,true),a=SL_RESPONSIBILITY_LAB.accumulator(s);SL_RESPONSIBILITY_LAB.collect(a,trial);report=SL_RESPONSIBILITY_LAB.finish(a);report.metadata.elapsedMs=performance.now()-start;report.detailedTrial=trial.trace;detail=trial;stop();render();return;}worker=new Worker('responsibility-lab-worker.js');lastWorkerMessage=performance.now();watchdog=setInterval(()=>{if(worker&&performance.now()-lastWorkerMessage>60000){stop();$('status').textContent='診断を完了できませんでした。Workerから60秒以上応答がありません。もう一度お試しください。';}},5000);worker.onmessage=({data})=>{lastWorkerMessage=performance.now();if(data.type==='progress'){$('progress').value=data.completed/data.total;$('status').textContent=`診断中… ${data.completed} / ${data.total}（${Math.floor(100*data.completed/data.total)}%）`;}else if(data.type==='complete'){report=data.report;detail=null;stop();render();}else{stop();$('status').textContent='診断を完了できませんでした。'+data.message;}};worker.onerror=e=>{stop();$('status').textContent='診断を完了できませんでした。Workerエラー: '+e.message;};worker.onmessageerror=()=>{stop();$('status').textContent='診断を完了できませんでした。Workerとの通信に失敗しました。';};worker.postMessage(s);}catch(err){stop();$('status').textContent='診断を完了できませんでした。'+err.message;}};
const pct=(n,total)=>`${n}回（${(100*n/total).toFixed(1)}%）`,escapeHtml=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function finalAssignments(){const decisions=detail.trace.decisionTimeline.at(-1)?.decisions||[],bases=detail.trace.baseNeedsTimeline.at(-1)?.bases||[],primary=decisions.find(x=>x.role==='PRIMARY FIELDING')?.fielder.position,relay=decisions.find(x=>['CUTOFF','RELAY'].includes(x.role))?.fielder.position;return {primary,relay,bases:Object.fromEntries(bases.map(x=>[x.base,x.assignedFielder?.position||null])),decisions};}
function plainDetail(){const x=finalAssignments(),items=[['打球処理',x.primary],['中継',x.relay],['一塁',x.bases['1B']],['二塁',x.bases['2B']],['三塁',x.bases['3B']],['本塁',x.bases.HOME]];return `<div class="lead-result"><strong>${positions[x.primary]||x.primary||'判定情報なし'}が打球を処理</strong><p>${x.relay?`${positions[x.relay]||x.relay}が中継を担当しました。`:'中継担当の記録はありません。'}</p></div><div class="assignment-grid">${items.map(([label,value])=>`<div class="assignment-card"><small>${label}</small><b>${positions[value]||value||'判定情報なし'}</b></div>`).join('')}</div>`;}
function rows(title,map,n){const entries=Object.entries(map||{}).sort((a,b)=>b[1]-a[1]);if(!entries.length)return'';return `<div class="trend-group"><h3>${title}</h3>${entries.map(([name,count])=>`<div class="trend-row"><span>${positions[name]||JP[name]||name}</span><meter min="0" max="${n}" value="${count}"></meter><b>${pct(count,n)}</b></div>`).join('')}</div>`;}
function bulkSummary(){const n=report.aggregate.trials,primary=report.roleDistribution['PRIMARY FIELDING']||{},secondary=report.roleDistribution['SECONDARY CHASE']||{},relay=report.relayDistribution||{},bases={};for(const [key,count] of Object.entries(report.baseNeedsDistribution)){const [base,,fielder]=key.split(':');bases[base]??={};bases[base][fielder]=(bases[base][fielder]||0)+count;}return `<h3>${n}回の診断結果</h3>${rows('打球処理担当',primary,n)}${rows('補助処理担当',secondary,n)}${rows('中継担当',relay,n)}${rows('一塁担当',bases['1B'],n)}${rows('二塁担当',bases['2B'],n)}${rows('三塁担当',bases['3B'],n)}${rows('本塁担当',bases.HOME,n)}${rows('プレー結果',report.aggregate.results,n)}`;}
function render(){const n=report.aggregate.trials,one=!!detail;$('resultHeading').textContent=one?'このプレーで何が起きたか':`${n}回の守備傾向`;$('plainSummary').innerHTML=one?plainDetail():'';$('statistics').innerHTML=one?'':bulkSummary();viewer?.destroy();viewer=null;$('diagnosticViewer').hidden=!one;if(one){viewer=SL_MATCH_VIEWER.create({root:$('diagnosticViewer'),getGame:()=>detail.game,step:()=>[]});viewer.renderEvent(detail.event,detail.event.play?.completeAt||0);const x=finalAssignments();$('technicalDetail').innerHTML=`<h3>最終役割</h3><div class="assignment-grid">${x.decisions.map(d=>`<div class="assignment-card"><small>${positions[d.fielder.position]||d.fielder.position}</small><b>${JP[d.role]||d.role}</b></div>`).join('')}</div><h3>Decision Timeline / responsibility</h3><pre>${escapeHtml(JSON.stringify({decisionTimeline:detail.trace.decisionTimeline,responsibilityTransitions:detail.trace.responsibilityChanges},null,2))}</pre><h3>baseNeeds / relay / throw / scoring</h3><pre>${escapeHtml(JSON.stringify({baseNeeds:detail.trace.baseNeedsTimeline,relay:detail.trace.relayTimeline,throwHistory:detail.trace.throwDecision,scoring:detail.trace.scoringDecision},null,2))}</pre>`;}else $('technicalDetail').innerHTML=`<h3>責任遷移の生集計</h3><pre>${escapeHtml(JSON.stringify(report.responsibilityTransitions,null,2))}</pre>`;$('flags').innerHTML=report.flaggedTrials.length?report.flaggedTrials.map((f,i)=>`<div class="flag"><b>${f.seed}</b><p>${f.reason}</p><button data-retry="${i}">このプレーを詳しく見る</button></div>`).join(''):'<p>今回の条件では要確認プレーはありません。</p>';$('flags').querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>retry(report.flaggedTrials[Number(b.dataset.retry)]));$('flagsSection').hidden=n===1&&!report.flaggedTrials.length;$('results').hidden=false;$('progress').value=1;$('status').textContent=`${n}回の診断が完了しました。`;$('results').scrollIntoView({behavior:'smooth',block:'start'});}
function retry(item){const original=report,trial=SL_RESPONSIBILITY_LAB.trial({...original.settings,count:1},item.seed,true),a=SL_RESPONSIBILITY_LAB.accumulator({...original.settings,count:1});SL_RESPONSIBILITY_LAB.collect(a,trial);previous=original;report=SL_RESPONSIBILITY_LAB.finish(a);report.detailedTrial=trial.trace;detail=trial;render();$('status').textContent=`${item.seed} を同じ条件・同じseedで詳しく再診断しました。`;}
$('save').onclick=()=>{if(!report)return;const s=report.settings,n=report.aggregate.trials,name=`守備責任診断_${s.label}_${n===1?s.seed+'_1回':n+'回'}.json`.replace(/[\\/:*?"<>|]/g,'_'),url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
$('compare').onclick=()=>{if(!previous){previous=report;$('comparison').textContent='現在結果を比較元として保持しました。条件を少し変えて再実行してください。';return;}const a=previous.representativeTrials[0]?.roles||{},b=report.representativeTrials[0]?.roles||{},diff=Object.fromEntries(SL_DECISION_TRACE.POS.filter(p=>a[p]!==b[p]).map(p=>[p,{条件A:JP[a[p]]||a[p]||null,条件B:JP[b[p]]||b[p]||null}]));$('comparison').textContent=Object.keys(diff).length?JSON.stringify(diff,null,2):'最終役割に差はありません。';};
})();
