(()=>{'use strict';const $=id=>document.getElementById(id),JP=SL_DECISION_TRACE.JP;let worker=null,report=null,detail=null,previous=null,viewer=null;
function settings(){const choice=document.querySelector('[name=count]:checked').value,count=choice==='custom'?Number($('customCount').value):Number(choice);return {outs:Number($('outs').value),runner1:$('runner1').checked,runner2:$('runner2').checked,runner3:$('runner3').checked,fielding:Number($('fielding').value),arm:Number($('arm').value),catching:Number($('catching').value),direction:Number($('direction').value),exitVelocity:Number($('exitVelocity').value),launchAngle:Number($('launchAngle').value),hangTime:Number($('hangTime').value),seed:$('seed').value,label:$('label').value,count};}
$('direction').oninput=()=>$('directionValue').textContent=Number($('direction').value).toFixed(2);document.querySelectorAll('[name=count]').forEach(x=>x.onchange=()=>$('customWrap').hidden=x.value!=='custom'||!x.checked);
function stop(){worker?.terminate();worker=null;$('run').disabled=false;$('cancel').hidden=true;}
$('cancel').onclick=()=>{stop();$('status').textContent='中止しました。';};
$('setup').onsubmit=e=>{e.preventDefault();try{const s=SL_RESPONSIBILITY_LAB.validate(settings());stop();$('run').disabled=true;$('cancel').hidden=false;$('results').hidden=true;$('progress').value=0;if(s.count===1){const start=performance.now(),trial=SL_RESPONSIBILITY_LAB.trial(s,`${s.seed}:0`,true),a=SL_RESPONSIBILITY_LAB.accumulator(s);SL_RESPONSIBILITY_LAB.collect(a,trial);report=SL_RESPONSIBILITY_LAB.finish(a);report.metadata.elapsedMs=performance.now()-start;report.detailedTrial=trial.trace;detail=trial;stop();render();return;}worker=new Worker('responsibility-lab-worker.js');worker.onmessage=({data})=>{if(data.type==='progress'){$('progress').value=data.completed/data.total;$('status').textContent=`${data.completed} / ${data.total}`;}else if(data.type==='complete'){report=data.report;detail=null;stop();render();}else{stop();$('status').textContent=data.message;}};worker.onerror=e=>{stop();$('status').textContent='実行エラー: '+e.message;};worker.postMessage(s);}catch(err){stop();$('status').textContent=err.message;}};
const pct=(n,total)=>`${n} / ${total} (${(100*n/total).toFixed(1)}%)`;
function render(){const n=report.aggregate.trials;$('summary').replaceChildren();for(const [role,counts] of Object.entries(report.roleDistribution)){const box=document.createElement('div');box.className='metric';box.innerHTML=`<b>${JP[role]||role}</b> `+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([p,c])=>`${p} ${pct(c,n)}`).join(' / ');$('summary').append(box);}viewer?.destroy();viewer=null;$('diagnosticViewer').hidden=!detail;if(detail){viewer=SL_MATCH_VIEWER.create({root:$('diagnosticViewer'),getGame:()=>detail.game,step:()=>[]});viewer.renderEvent(detail.event,detail.event.play?.completeAt||0);}$('detail').innerHTML=detail?`<h3>最終role構成</h3><div class="role-grid">${Object.entries(detail.roles).map(([p,r])=>`<div class="role-card"><b>${p}</b><br>${JP[r]||r}</div>`).join('')}</div><details open><summary>Decision Timeline</summary><pre>${escapeHtml(JSON.stringify(detail.trace.decisionTimeline,null,2))}</pre></details><details><summary>baseNeeds / relay / throw / scoring</summary><pre>${escapeHtml(JSON.stringify({baseNeeds:detail.trace.baseNeedsTimeline,relay:detail.trace.relayTimeline,throwDecision:detail.trace.throwDecision,scoringDecision:detail.trace.scoringDecision},null,2))}</pre></details>`:'<p>大量試行では詳細timelineを保持せず、集計と再診断用seedだけを保存します。</p>';$('flags').innerHTML='<h3>要確認 '+report.flaggedTrials.length+'試行</h3>'+report.flaggedTrials.map((f,i)=>`<div class="flag"><b>${f.seed}</b><p>${f.reason}</p><button data-retry="${i}">この試行を詳しく見る</button></div>`).join('');$('flags').querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>retry(report.flaggedTrials[Number(b.dataset.retry)]));$('results').hidden=false;$('progress').value=1;$('status').textContent=`${n}試行完了 / ${(report.metadata.elapsedMs/1000).toFixed(2)}秒 / 詳細timeline保持 ${report.storage.fullTimelinesHeld}本`;}
function retry(item){const s={...report.settings,count:1,seed:item.seed.replace(/:\d+$/,'')},trial=SL_RESPONSIBILITY_LAB.trial(s,item.seed,true),a=SL_RESPONSIBILITY_LAB.accumulator(s);SL_RESPONSIBILITY_LAB.collect(a,trial);previous=report;report=SL_RESPONSIBILITY_LAB.finish(a);report.detailedTrial=trial.trace;detail=trial;render();$('status').textContent=`${item.seed} を同条件で詳細再実行しました。`;}
const escapeHtml=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
$('save').onclick=()=>{if(!report)return;const s=report.settings,n=report.aggregate.trials,name=`守備責任診断_${s.label}_${n===1?s.seed+'_1回':n+'回'}.json`.replace(/[\\/:*?"<>|]/g,'_'),url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
$('compare').onclick=()=>{if(!previous){previous=report;$('comparison').textContent='現在結果を比較元として保持しました。条件を少し変えて再実行してください。';return;}const a=previous.representativeTrials[0]?.roles||{},b=report.representativeTrials[0]?.roles||{},diff=Object.fromEntries(SL_DECISION_TRACE.POS.filter(p=>a[p]!==b[p]).map(p=>[p,{条件A:JP[a[p]]||a[p]||null,条件B:JP[b[p]]||b[p]||null}]));$('comparison').textContent=Object.keys(diff).length?JSON.stringify(diff,null,2):'最終role構成に差はありません。';};
})();
