const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006.js','engine-lab-core.js','decision-trace-core.js','responsibility-lab-core.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const R=SL_RESPONSIBILITY_LAB,base={outs:0,runner1:false,runner2:false,runner3:false,fielding:14,arm:14,catching:14,direction:.5,exitVelocity:30,launchAngle:6,hangTime:1.8,count:1,seed:'fixture',label:'fixture'};
function fixture(name,changes,verify){const t=R.trial({...base,...changes},'fixture:'+name,true);verify(t);console.log('PASS FIXTURE-'+name,t.result,t.primary);return t;}
const A=fixture('A',{},t=>{assert(t.primary);assert.equal(Object.keys(t.roles).length,9);assert(t.trace.baseNeedsTimeline.length);assert(t.trace.responsibilityChanges.length);});
fixture('B',{direction:-.5},t=>assert(t.trace.relayTimeline));
fixture('C',{direction:-.35,launchAngle:42,hangTime:4.2},t=>{assert(t.trace.decisionTimeline.length);assert(t.trace.responsibilityChanges.some(x=>x.changeTime>0));});
fixture('D',{runner1:true,direction:-.25,launchAngle:0,hangTime:0},t=>{assert(Array.isArray(t.trace.throwDecision.candidates));assert(t.trace.throwDecision.throws.length);assert.equal(typeof t.trace.throwDecision.doublePlayContinuationPossible,'boolean');});
fixture('E',{runner1:true,direction:-.3,launchAngle:0,hangTime:0},t=>{assert(t.trace.scoringDecision.classification);assert(t.trace.scoringDecision.classificationReason);});
function bulk(n){const s={...base,count:n},a=R.accumulator(s),start=performance.now();for(let i=0;i<n;i++)R.collect(a,R.trial(s,`bulk:${n}:${i}`));const report=R.finish(a);assert.equal(report.aggregate.trials,n);assert(Object.keys(report.roleDistribution).length);assert(Object.keys(report.responsibilityTransitions).length);assert(Array.isArray(report.flaggedTrials));assert.equal(report.storage.fullTimelinesHeld,0);assert(!('_trials' in report));return {report,ms:performance.now()-start,bytes:Buffer.byteLength(JSON.stringify(report))};}
const hundred=bulk(100);console.log('PASS FIXTURE-F',hundred.ms.toFixed(1)+'ms',hundred.bytes+' bytes');
const thousand=bulk(1000);console.log('PASS FIXTURE-G',thousand.ms.toFixed(1)+'ms',thousand.bytes+' bytes');
const chosen=thousand.report.flaggedTrials[0]||thousand.report.representativeTrials[0],rerun=R.trial({...base,count:1},chosen.seed,true);assert.equal(rerun.seed,chosen.seed);assert(rerun.trace.decisionTimeline.length);console.log('PASS FIXTURE-H',chosen.seed);
const g=SL_ENGINE.newGame(['away','home'].map(side=>SL_ENGINE.makeTeam('C',side,[],SL_ENGINE.CONFIG)),'live');SL_DECISION_TRACE.configure(g,{enabled:true,gameId:'live'});for(let i=0;i<100&&!SL_DECISION_TRACE.state(g).records.length;i++){const e=SL_ENGINE.onePitch(g);SL_DECISION_TRACE.capture(g,e);}assert(SL_DECISION_TRACE.state(g).records.every(x=>x.battedBall.trajectory));console.log('PASS live playId capture',SL_DECISION_TRACE.state(g).records[0].metadata.playId);
fs.mkdirSync('test-artifacts',{recursive:true});fs.writeFileSync('test-artifacts/responsibility-lab-performance.json',JSON.stringify({hundred:{ms:hundred.ms,bytes:hundred.bytes},thousand:{ms:thousand.ms,bytes:thousand.bytes},sample:A.trace.metadata},null,2));
