const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const plain=x=>JSON.parse(JSON.stringify(x)),dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const results=[];
for(const lab of [false,true]){
 const c=vm.createContext({console});for(const f of lab?['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js']:['engine-fielding.js','engine-tactics.js','match-replay.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});if(!lab)vm.runInContext(fs.readFileSync('engine-test.html','utf8').match(/<script>\s*([\s\S]*?)<\/script>/)[1],c);
 const E=c.SL_ENGINE,F=c.SL_FIELDING,T=c.SL_TACTICS,R=c.SL_MATCH_REPLAY,teams=[E.makeTeam('A','away',[],E.CONFIG),E.makeTeam('B','home',[],E.CONFIG)],make=seed=>E.newGame(teams,seed);
 const tally={lab,events:0,plays:0,fcThird:0,hitGround:0,steal:0,bunt:0,hitRun:0,ownershipChecks:0,phases:{}};
 function inspect(e){if(!e.play)return;const q=e.play,r=R.toReplayEvent(e),p=R.animationPlan(r);tally.plays++;
  assert.equal(e.fieldEvent.actorKey,q.actualFielder);assert.equal(e.ballOwnerAtCatch,q.actualFielder);assert.equal(q.timeline.find(x=>x.type==='PLAY_COMPLETE').ballOwner,e.ballOwner);
  for(const leg of q.transfers){const before=F.samplePlay(q,leg.start-1e-7);assert.equal(before.ballOwner,leg.throwerKey,JSON.stringify({result:e.result,leg,before}));assert(dist(before.positions[leg.fromIndex],leg.fromPoint)<.01,'throw from current owner position');assert(dist(F.samplePlay(q,leg.end).positions[leg.toIndex],leg.toPoint)<.01,'receiver actually at catch point');if(leg.timing)assert(Math.abs(leg.tagAt-leg.timing.ballETA)<.001,'judgment clock equals receive/tag clock');tally.ownershipChecks++;}
  assert(q.completeAt>=(q.transfers.at(-1)?.tagAt||0));assert(q.resetAt>q.completeAt);
  let previous=F.samplePlay(q,0);for(let time=.04;time<=q.resetEnd;time+=.04){const now=F.samplePlay(q,time);for(let i=0;i<9;i++){assert(dist(now.positions[i],previous.positions[i])<=((time>=q.resetAt?1000:e.defense[i].moveSpeed)+1)*.04+.01,'position discontinuity '+JSON.stringify({i,time,result:e.result,track:q.tracks[i]}));}if(time<q.completeAt)assert.equal(now.phase,'PLAY_ACTIVE');previous=now;}
  for(const time of [p.caught,p.throwStart,p.throwEnd,p.resultAt,p.returnAt]){const ball=R.ballAnimation(r,p,time),s=F.samplePlay(q,(time-p.pitchEnd)/1000);if(ball.ballOwner){assert.equal(ball.ballOwner,s.ballOwner);assert(dist(ball.ground,R.fieldingAnimation(r,p,time,s.ownerIndex).position)<.01);}assert(ball.ground.every(Number.isFinite));}
  if(e.result==='fieldersChoice'&&e.outsAfter===3){tally.fcThird++;const runner=q.runners.find(x=>x.runner.key===e.batter.key);assert(runner);assert(runner.toBase===1);const at=R.runnerAnimation(r,p,p.pitchEnd+(runner.start+.2)*1000).find(x=>x.who.key===e.batter.key);assert(at&&at.running);assert(!R.batterVisible(r,p,p.pitchEnd+(runner.start+.2)*1000));assert(e.nextState?.runners.every(x=>!x)||e.nextState?.finished||!e.nextState);}
 }
 for(const index of [5,3,4]){const x=make(index),b=E.currentBatter(x),p=E.currentPitcher(x);x.rng=()=>.5;x.tacticalRng=()=>0;const ball={battedResult:'groundout',ballType:'ground',fielderIndex:index,landingPoint:[...F.layout.positions[index]],battedQuality:.5};assert.equal(F.field(x,ball,b,p),'groundout');assert(ball.defenseDecision.timing.margin>.4);}
 for(const [time,speed,expected] of [[3,10,'single'],[2.2,20,'single'],[2.2,2,'groundout']]){const x=make(4),b=E.currentBatter(x),p=E.currentPitcher(x);b.effective.speed=speed;b.profile.batting.speed=speed;x.rng=()=>.5;x.tacticalRng=()=>0;const ball={battedResult:'groundout',ballType:'ground',fielderIndex:5,landingPoint:[325,250],battedQuality:.5,trajectory:{fieldTime:time}};assert.equal(F.field(x,ball,b,p),expected,'time race '+speed);}
 // A forced-choice third out must still include the batter's started attempt.
 {const x=make(6),b=E.currentBatter(x),p=E.currentPitcher(x);x.state.outs=2;x.state.bases[0]=x.teams[0].lineup[2];x.state.playBefore=x.state.bases.map(r=>r&&({key:r.key,name:r.name}));x.rng=()=>.5;x.tacticalRng=()=>.99999;const ball={outcome:'inPlay',battedResult:'groundout',ballType:'ground',fielderIndex:5,landingPoint:[325,250],battedQuality:.5};const result=F.field(x,ball,b,p);assert.equal(result,'fieldersChoice');const e={...ball,result,outsBefore:2,outsAfter:3,batter:{key:b.key,name:b.name},runnersBefore:x.state.playBefore,runnersAfter:[],actions:plain(x.state.playActions)};F.annotate(x,e);inspect(e);}
 for(const [index,point] of [[6,[210,190]],[7,[400,190]],[8,[590,190]],[7,[400,70]]]){const x=make(index),b=E.currentBatter(x),e={outcome:'inPlay',result:'single',ballType:'line',fielderIndex:index,landingPoint:point,batter:{key:b.key},outsBefore:0,outsAfter:0,runnersBefore:[null,null,null],runnersAfter:[{key:b.key}],actions:[{runner:{key:b.key},fromBase:0,toBase:1,result:'safe'}]};F.annotate(x,e);inspect(e);assert(e.play.anticipation.recognizedAt<e.play.caught);assert(dist(e.returnFormation.relayPoint,[400,430])<240);const variant={...e,result:'flyout',transfers:[],play:null};variant.play=F.buildPlay(variant);for(let t=0;t<Math.min(e.play.caught,variant.play.caught);t+=.1)assert.deepEqual(plain(F.samplePlay(e.play,t).positions),plain(F.samplePlay(variant.play,t).positions),'no future outcome in initial defense');}
 for(let seed=0;seed<20;seed++){const x=make('round2:'+seed);E.advance(x,'game');assert(x.state.finished);for(const e of x.state.events){tally.events++;tally.steal+=!!e.stealExecution;tally.bunt+=!!e.buntAttempt;tally.hitRun+=!!e.hitAndRun;tally.hitGround+=e.hit&&e.ballType==='ground'&&e.fielderIndex>=6;inspect(e);assert(e.outsAfter<=3);assert.equal(new Set(e.runnersAfter.filter(Boolean).map(r=>r.key)).size,e.runnersAfter.filter(Boolean).length);}if(seed<2){const y=make('round2:'+seed);while(!y.state.finished)E.advance(y,'pitch');assert.equal(JSON.stringify(y.state),JSON.stringify(x.state));}}

 // A resolved catcher may differ from the initial primary; the catcher cannot also be sent on a secondary leg.
 {const x=make('resolved-catcher'),b=E.currentBatter(x),e={outcome:'inPlay',result:'single',infieldHit:true,ballType:'line',fielderIndex:7,fieldingFielderIndex:5,catchCandidates:[{index:5,time:1}],landingPoint:[325,250],batter:{key:b.key},outsBefore:0,outsAfter:0,runnersBefore:[null,null,null],runnersAfter:[{key:b.key}],actions:[{runner:{key:b.key},fromBase:0,toBase:1,result:'safe'}],throw:{toBase:1}};F.annotate(x,e);assert.notEqual(e.primaryFielder.key,e.actualFielder.key);assert.equal(e.play.transfers[0].throwerKey,e.actualFielder.key);inspect(e);}
 // Identical observable balls must have identical paths before landing, even if the recorded outcome differs.
 {const x=make('blind'),base={outcome:'inPlay',ballType:'line',fielderIndex:7,landingPoint:[400,170],battedQuality:.5,batter:{key:E.currentBatter(x).key},outsBefore:0,outsAfter:0,runnersBefore:[null,null,null],runnersAfter:[],actions:[]},a={...base,result:'single'},b={...base,result:'flyout'};F.annotate(x,a);F.annotate(x,b);for(let time=0;time<Math.min(a.play.flight,b.play.flight);time+=.04)assert.deepEqual(plain(F.samplePlay(a.play,time).positions),plain(F.samplePlay(b.play,time).positions));}
 // Real roster: audit the full tactical funnel, without prescribing usage rates.
 const db=JSON.parse(fs.readFileSync('SL_WORLD_PLAYERS_2026-09-10.json','utf8')).players,names=[...new Set(db.map(p=>p.team))],realTeams=names.map((name,i)=>E.makeTeam(name,i?'home':'away',db,E.CONFIG));
 const audit={games:12,selected:{},funnel:{},examples:{}};
 for(let seed=0;seed<12;seed++){const x=E.newGame(realTeams,'real-r2:'+seed);E.advance(x,'game');for(const e of x.state.events){inspect(e);const d=e.tactics.offense;audit.selected[d.decision]=(audit.selected[d.decision]||0)+1;for(const option of d.candidates){const f=audit.funnel[option.decision]??={generated:0,eligible:0,positive:0};f.generated++;f.eligible+=option.legal;f.positive+=option.weight>0;}const kind=e.hitAndRun?'hitAndRun':e.result==='fieldersChoice'&&e.outsAfter===3?'fcThird':e.returnDecision?.mode|| (e.defenseDecision?.timing?'groundRace':null);if(kind&&!audit.examples[kind])audit.examples[kind]={sequence:e.sequence,result:e.result,decision:d,defenseDecision:e.defenseDecision,play:e.play};}}
 assert(audit.selected.HIT_AND_RUN>0,'real-roster hit-and-run execution');assert(audit.examples.direct&&audit.examples.relay);assert(audit.examples.fcThird); tally.realRoster=audit;
 const choices=new Set();for(let seed=0;seed<200;seed++){const x=make('tactics:'+seed),b=E.currentBatter(x);x.state.inning=8;x.state.bases[0]=x.teams[0].lineup[2];b.effective.meet=8;b.effective.power=20;x.state.bases[0].effective.speed=20;F.defense(x)[1].profile.batting.arm=1;const d=T.offenseDecision(x,b,E.currentPitcher(x));choices.add(d.decision);assert(d.candidates.find(x=>x.decision==='HIT_AND_RUN'));assert(d.candidates.every(c=>c.trace));x.state.outs=2;assert.equal(T.hitRunOption(x,b).weight,0);assert.equal(T.buntOption(x,b).weight,0);}assert(choices.has('SAC_BUNT')&&choices.has('STEAL_2B')&&choices.has('HIT_AND_RUN'),[...choices].join(','));
 results.push(tally);console.log(tally);
}
fs.writeFileSync('test-artifacts/round2-regression.json',JSON.stringify(results,null,2));console.log('PASS both engines: ownership, continuous tracks, FC third out, time races, early relay, resets and tactical gates');
