const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),cp=require('child_process');
for(const f of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=SL_ENGINE,F=SL_FIELDING,R=SL_MATCH_REPLAY,report={fixtures:[],protected:[],hold:[]};
const game=()=>E.newGame(['away','home'].map(s=>E.makeTeam('オールC',s,[],E.CONFIG)),'second-cover-hold');
function fixture(angle,runner=false,hang=3){const g=game();if(runner)g.state.bases[0]=g.teams[0].lineup[2];const p={outcome:'inPlay',physical:{exitVelocity:hang*9.81/(2*Math.sin(Math.PI/4)),launchAngle:45,sprayAngle:angle,type:'FLY',hangTime:hang,horizontalSpeed:(180+60/.55)/hang,deceleration:62}};F.geometry(g,p);F.process.defensePlan(g,p);p.play=F.buildPlay(p);return {g,p};}
for(const [name,angle,primary,cover]of [['TEST-1',.5,3,5],['TEST-2',-.5,5,3]]){const {g,p}=fixture(angle,true);assert.equal(p.fielderIndex,primary);for(const row of p.roleEvaluations){assert.notEqual(row.baseEvaluations[1].requiredState,'NOT_CURRENTLY_REQUIRED');assert.equal(row.baseEvaluations[1].assignedFielder,cover);}const track=p.defensivePlan.tracks[cover];assert.deepEqual(F.trackPosition(track,2.6),F.layout.bases[2]);report.fixtures.push({name,primary,cover,arrival:track.legs.find(l=>l.movementState==='HOLD').start,base:p.roleEvaluations[0].baseEvaluations[1]});console.log('PASS',name);}
for(const angle of [.5,-.5]){const {p}=fixture(angle);assert(p.roleEvaluations.every(r=>r.baseEvaluations[1].requiredState==='NOT_CURRENTLY_REQUIRED'&&r.baseEvaluations[1].assignedFielder===null));}report.fixtures.push({name:'TEST-3',unnecessarySecondCover:false});console.log('PASS TEST-3');
// Missing next-play input is different from an empty but irrelevant base.
{const g=game(),current=F.layout.positions.map(p=>[...p]),f=F.defense(g);for(const primary of [3,5])for(const context of [{airborne:true,batterMayAdvanceSecond:true},{nextThrowBase:2}]){const a=F.process.redistribute(g,current,f,primary,null,[470,180],[],0,context);assert.equal(a.baseEvaluations[1].requiredState,'POTENTIAL');assert.equal(a.findIndex(x=>x.base===2),primary===3?5:3);}const a=F.process.redistribute(g,current,f,3,null,[470,180],[],0,{secured:true});assert.equal(a.baseEvaluations[1].assignedFielder,null);report.fixtures.push({name:'batter/return second-base context',passed:true});}
// Geometry and competing responsibilities can change the successor: not a position pair rule.
{const g=game();g.state.bases[0]=g.teams[0].lineup[2];g.state.outs=2;const current=F.layout.positions.map(p=>[...p]);current[5]=[80,100];current[0]=[400,226];const a=F.process.redistribute(g,current,F.defense(g),3,null,[480,180],[],0,{airborne:true});assert.equal(a.findIndex(x=>x.base===2),0);assert.equal(a[1].base,4);report.fixtures.push({name:'successor follows current ETA and available responsibilities',cover:0});}
for(const hang of [3,6]){const {g,p}=fixture(.5,false,hang),f=F.defense(g);for(const [index,base,name]of [[1,4,'TEST-4'],[2,1,'TEST-5']]){const track=p.defensivePlan.tracks[index],held=track.legs.find(l=>l.movementState==='HOLD');assert(held);const v=F.process.speed(f[index],index)/(1+.16*(1-F.ability(f[index],'fielding'))),expected=F.process.reaction(f[index])+Math.hypot(track.origin[0]-F.layout.bases[base][0],track.origin[1]-F.layout.bases[base][1])/v;assert(Math.abs(held.start-expected)<1e-7);assert(held.start<1.2);for(let t=held.start+.001;t<p.interception.time-.02;t+=.01){assert.deepEqual(F.trackPosition(track,t),F.layout.bases[base]);const frame=R.fieldingAnimation(p,{pitchEnd:0,transfers:[],caught:p.interception.time*1000},t*1000,index);assert.equal(frame.pose.running,false,'arrived cover must not keep stepping');}assert(track.legs.every(l=>Math.hypot(l.to[0]-l.from[0],l.to[1]-l.from[1])>0||l.end===l.start));report.hold.push({name,hang,arrivedAt:held.start,expected,legs:track.legs});console.log('PASS',name,'hang',hang,'arrival',held.start);}}
// Reissued tiny target changes hold; a real receiving assignment wakes movement.
{const {g,p}=fixture(.5);const i=1,at=1.3,b=F.layout.bases[4];F.process.moveTrack(g,p,i,[b[0]+.02,b[1]-.02],at,'baseCover');assert.deepEqual(F.trackPosition(p.defensivePlan.tracks[i],1.4),b);assert.equal(p.defensivePlan.tracks[i].legs.at(-1).movementState,'HOLD');F.process.moveTrack(g,p,i,[410,420],1.5,'receive');assert.notDeepEqual(F.trackPosition(p.defensivePlan.tracks[i],1.6),b);report.fixtures.push({name:'stable target and real receive wake-up',passed:true});}
// The repaired pursuit decisions and all protected formulas are byte-for-byte unchanged.
const source=fs.readFileSync('engine-fielding.js','utf8'),old=cp.execFileSync('git',['show','HEAD:engine-fielding.js'],{encoding:'utf8'});
for(const [from,to]of [[' function naturalAt(',' function baseNeeds('],[' function interceptEstimate(',' function pursueAir('],['    const qualifications=','    const previousAssignments='],[' function generate(',' function ballAt('],[' function classify(',' // Read only'],[' function flyObservation(',' F.process=']]){assert.equal(source.slice(source.indexOf(from),source.indexOf(to,source.indexOf(from))),old.slice(old.indexOf(from),old.indexOf(to,old.indexOf(from))));report.protected.push(from.trim());}
for(const file of ['engine006-tactics.js','engine006-replay.js','match-replay.js','engine006.js','match-viewer.js','engine006-viewer.js'])assert.equal(fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),cp.execFileSync('git',['show','HEAD:'+file],{encoding:'utf8'}).replace(/\r\n/g,'\n'));
fs.writeFileSync('test-artifacts/second-cover-hold.json',JSON.stringify(report,null,2));console.log('PASS protected pursuit, runner, classification, tactics and renderer sources');
