const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');for(const file of ['engine006-fielding.js','engine006-tactics.js','engine006-replay.js','engine006.js','engine-lab-core.js','custom-match-core.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});const E=SL_ENGINE,F=SL_FIELDING,T=SL_TACTICS,L=SL_LAB,R=SL_MATCH_REPLAY,C=SL_CUSTOM_MATCH,copy=x=>JSON.parse(JSON.stringify(x));
function check(e){const x=e.stealExecution||e.runningExecution?.stealExecution;if(!x||x.toBase!==2||e.stealInterrupted||e.runningExecution?.stealInterrupted)return false;assert.equal(x.coverIndex,3);assert.equal(x.receiverIndex,3);assert.equal(x.taggerIndex,3);assert.equal(x.receivingFielder.position,'2B');assert.equal(e.receiver.index,3);assert.equal(e.tag.fielderIndex,3);assert.equal(e.tag.fielder.index,3);const leg=e.play.transfers[0];assert.equal(leg.fromIndex,1);assert.equal(leg.toIndex,3);assert.equal(leg.receiver.position,'2B');assert.equal(leg.receiverKey,e.defense[3].key);assert.equal(e.assignedRoles.find(r=>r.index===3).assignedRole,'BASE COVER');assert.equal(e.assignedRoles.find(r=>r.index===5).assignedRole,'BACKUP');assert(e.play.tracks[5].legs.every(l=>l.role==='backup'));assert(e.play.tracks[3].legs.some(l=>l.roleCode==='BASE COVER'));assert.deepEqual(F.trackPosition(e.play.tracks[3],leg.end),copy(F.layout.bases[2]));assert(Math.hypot(...F.trackPosition(e.play.tracks[5],leg.end).map((v,i)=>v-F.layout.bases[2][i]))>20);assert(Math.abs(leg.tagAt-(x.tagAt-x.pitchArrival))<1e-8);const tag=e.play.timeline.find(t=>t.type==='TAG');assert.equal(tag.actorIndex,3);assert.equal(tag.actorKey,e.defense[3].key);assert.equal(F.samplePlay(e.play,leg.end).ownerIndex,3);const replay=R.toReplayEvent(e),plan=R.animationPlan(replay);assert.equal(replay.play.transfers[0].toIndex,3);const receiveTime=plan.pitchEnd+(leg.end+.001)*1000,tagTime=plan.pitchEnd+(leg.tagAt-.001)*1000;assert.deepEqual(copy(R.fieldingAnimation(replay,plan,receiveTime,3).position),copy(F.layout.bases[2]));assert(R.fieldingAnimation(replay,plan,tagTime,3).tagging);assert(!R.fieldingAnimation(replay,plan,tagTime,5).tagging);const running=e.runningExecution||e;assert.equal(running.throw.toIndex,3);assert.equal(running.throw.target.key,e.defense[3].key);assert.equal(running.tag.fielderIndex,3);assert.equal(running.stolenBase,x.runnerETA<=x.tagAt);assert.equal(running.caughtStealing,x.runnerETA>x.tagAt);return true;}
const scenario=L.config('steal');Object.assign(scenario,{runnerGrade:'S',runnerTrait:'盗塁○',half:'top',inning:6});const bundle=L.setup(scenario),counts={direct:0,safe:0,out:0,lab:0,custom:0,normal:0,hitRun:0};let representative;
for(let seed=0;seed<300;seed++){const g=L.create(bundle,seed),before=copy(g.state.bases),outs=g.state.outs,e=F.steal(g,E.currentPitcher(g),{fromBase:1,noPitch:true});Object.assign(e,{outsBefore:outs,outsAfter:g.state.outs,runnersBefore:before,runnersAfter:copy(g.state.bases),actions:copy(g.state.playActions),batter:{key:E.currentBatter(g).key}});F.annotate(g,e);assert(check(e));counts.direct++;counts.safe+=e.stolenBase;counts.out+=e.caughtStealing;representative??=e;
 if(seed===0){const h=L.create(bundle,'hitRun'),before=copy(h.state.bases),running=F.steal(h,E.currentPitcher(h),{fromBase:1,noPitch:true}),event={runningExecution:running,hitAndRun:true,outcome:'swingingStrike',eventType:'pitch',result:'swingingStrike',outsBefore:1,outsAfter:h.state.outs,runnersBefore:before,runnersAfter:copy(h.state.bases),actions:copy(h.state.playActions),batter:{key:E.currentBatter(h).key}};F.annotate(h,event);assert(check(event));counts.hitRun++;}}
assert(counts.safe>0&&counts.out>0);
// Only the 2B's position and speed contribute to steal coverage ETA.
{const g=L.create(bundle,0),r=g.state.bases[0],p=E.currentPitcher(g),fielders=F.defense(g),original=T.alignment;T.alignment=game=>{const a=original(game);a.positions=copy(a.positions);a.positions[3]=[650,100];return a;};try{fielders[3].profile.batting.speed=2;const slow=F.stealExecution(g,r,p,1);fielders[5].profile.batting.speed=20;const ss=F.stealExecution(g,r,p,1);assert.equal(slow.coverETA,ss.coverETA);fielders[3].profile.batting.speed=20;const fast=F.stealExecution(g,r,p,1);assert(fast.coverETA<slow.coverETA);assert(slow.ballETA>=slow.coverETA);assert(Math.abs(slow.releaseTime+slow.throwTime-slow.ballETA)<1e-9);assert.deepEqual(copy(slow.assignedRoles[0].origin),[650,100]);}finally{T.alignment=original;}}
// Third-base steal and ordinary/DP receiving rules remain separate.
{const g=L.create(bundle,0),r=g.state.bases[0];g.state.bases=[null,r,null];const e=F.steal(g,E.currentPitcher(g),{fromBase:2,noPitch:true});assert.equal(e.throw.toIndex,4);assert.equal(e.tag.fielderIndex,4);assert.equal(e.stealExecution.coverIndex,4);assert.equal(F.receiverIndex(2,1,[400,462]),5);assert.equal(F.receiverIndex(2,5,[325,250]),3);}
for(let seed=0;seed<60;seed++){const t=L.trial(bundle,'cover-lab:'+seed,{events:true});for(const e of t.events)if(check(e))counts.lab++;}
for(const kind of ['normal','custom'])for(let seed=0;seed<3;seed++){const teams=kind==='custom'?C.teams({runCount:1,teams:[{...C.preset('C'),speed:20,steal:'盗塁○'},{...C.preset('C'),speed:20,steal:'盗塁○'}]}):[E.makeTeam('A','away',[],E.CONFIG),E.makeTeam('B','home',[],E.CONFIG)];if(kind==='normal')for(const team of teams)for(const player of team.lineup){player.effective.speed=20;player.profile.batting.speed=20;player.specials.push('盗塁○');}const g=E.newGame(teams,'cover-'+kind+seed);E.advance(g,'game');for(const e of g.state.events){assert.deepEqual(copy(C.anomalies(e)),[]);if(check(e))counts[kind]++;}}
console.log(counts);assert(counts.lab>0&&counts.custom>0&&counts.normal>0);fs.writeFileSync('test-artifacts/steal-cover-0914.json',JSON.stringify({passed:true,version:E.CONFIG.version,counts,representative:copy(representative)},null,2));console.log('PASS second-base steal coverage, receiver/tag actor, SAFE/OUT clock, backup, shifted position/speed, third-base unchanged, LAB/CUSTOM/normal/HitRun',counts);
